### ISSUE TITLE
Difficulty pairing a second PSMove controller

### ISSUE THREAD

**Issue by jmb1304** [cboulay/PSMoveService#103]
If you try to pair an additional controller the whole thing hangs up and the server window keeps spitting out:
`[2016-07-06 08:51:21.113952]: AsyncBluetoothPairDeviceRequest - No Bluetooth device found matching the given address: xx:xx:xx:xx:xx:xx`

**Comment by HipsterSloth** [comment]
When pairing in windows you'l frequently see the controller disconnect a few times during the pairing process. You can thank windows bluetooth stack for that. See that message is a normal part of the process as it attempts to search for the device. Here are some questions for you that will help me figure out what's going on:

* Is the config tool window with the progress bar crashing/exiting? Or is it just stuck waiting for the server?
* Is the small red light on the controller blinking during the pairing process? Are you pressing the PS Button if the blinking stops?
* What bluetooth adapter are you using? Is it the ASUS BT-400 or some other adapter?
* Have you disconnected the controller from USB once the bluetooth pairing started?
* Have you tried turning off the other controller (holding down the PS button for 10 seconds) while pairing the other controller?
* Has the controller that's having trouble pairing been charged overnight?

If this pairing tool isn't working for you, you could try using the older pairing tools in PSMove-Unity5:
https://github.com/HipsterSloth/psmove-unity5/tree/master/Assets/Plugins/x86_64

Instructions for usage can be found here:
https://github.com/HipsterSloth/psmove-unity5/wiki/PSMove-Setup-%28Windows%29

Fortunately once you get the controllers paired you don't need to go through that process again.

**Comment by jmb1304** [comment]
Ok thank you!

**Comment by jmb1304** [comment]
It paired perfectly when i turned off the first controller. Now I don't think that my Bluetooth dongle can accept more than 1 connection at once.

**Comment by ZedVR** [comment]
@jmb1304 Hello! I know it's been 4 years, but I'm wondering: was it the case? Mine cannot connect two controllers at the same time too, maybe just a new bt adapter is needed.
