### ISSUE TITLE
Send the first data frame with the reply to the controller stream start

### ISSUE THREAD

**Issue by cboulay** [cboulay/PSMoveService#105]
As mentioned in #96, the first data frame should be sent with the reply to controller stream start. I'm running into this now developing the CAPI. After issuing a blocking call to `PSM_StartControllerDataStream` I try to immediately `PSM_UpdateController` but it doesn't know its type yet. For now I'll write checks to make sure the type matches in `PSM_UpdateController`.

**Comment by HipsterSloth** [comment]
Ah right. Well now is as good a time as any to make the controller stream start request do the right thing. I'll fix this tonight. Let me know if there is anything else on the CAPI branch you'd like me to jump in and help with.

**Comment by HipsterSloth** [comment]
This is now fixed in the CAPI branch with change a20ebb123160e4324f1d4e05349ec6de0b5f5315.
