### ISSUE TITLE
MotionInJoy pair generic bluetooth but PS Move Service don't

### ISSUE THREAD

**Issue by andregm3** [cboulay/PSMoveService#107]
is it possible to integrate with Motion In Joy Driver, because my generic bluetooth dongle has been recognized with MotionInJoy and is working perfectly !

**Comment by HipsterSloth** [comment]
I'm not very familiar with the MotionInJoy drivers. The list of con's on this page make me nervous about adding support for it:

From here: http://emulation-general.wikia.com/wiki/MotioninJoy
> Cons
* Sets your homepage to a site called sh.com, which is a Chinese website full of malware. 
* It overrides your USB and Bluetooth drivers (Such as the Logitech Unifying Receiver) and can * render them useless until you remove MotioninJoy and uninstall its associated drivers.
* Must open DS3 Tool every time you plug your controller in.
* Must select a profile each time.
* Updated very infrequently.
* Is very difficult to remove once installed.
* It does not work sometimes and gives a lot of errors.

Also it appears to be a proprietary driver. I can't find any documentation for how to integrate it.

**Comment by andregm3** [comment]
MotionInJoy is working very stable here, all buttons and etc are working and i just press PS Home button it syncs anytime. You should try it, to uninstall just press revert drive on DS3 Tool

**Comment by HipsterSloth** [comment]
What does the MotionInJoy driver provide that you don't get with PSMoveService?

**Comment by andregm3** [comment]
i have a generic USB Dongle, and PSMoveService don't recognize it.

**Comment by HipsterSloth** [comment]
Did it not recognize it before or after you installed MotionInJoy? I ask because MotionInJoy installs a custom bluetooth driver that prevents anything but motion in joy from accessing the bluetooth adapter.

**Comment by andregm3** [comment]
Before and after, i first triyed PS Move Service, and with no response i went to MotionInJoy then.

**Comment by zelmon64** [comment]
I've also heard that it is limited to connecting only one PSMove per adapter. I haven't tested that myself as I'm not letting MotionInJoy anywhere near my computer. I got this information when using MoveFramework.

**Comment by HipsterSloth** [comment]
This isn't inspiring me with confidence: http://www.neogaf.com/forum/showthread.php?t=510044. 

I feel much better about supporting bluetooth adapters that don't require people to install software with a known history of malware.

Even if I felt good about supporting this driver, it would take at least a month for me to get to supporting this. There are a lot of other higher priority things to work on at the moment. 

I've had good luck with the ASUS BT-400 bluetooth adapter: 
https://www.amazon.com/Bluetooth-Adapter-Dongle-Integrated-USB-BT400/dp/B00CM83SC0.

**Comment by andregm3** [comment]
i bought another dongle a CSR one, but i will try different drivers tonight too and see if does anyone makes PS Move Service recognize it

**Comment by andregm3** [comment]
See 2 Ps Move connected at the same time on MotionInJoy =]

https://goo.gl/photos/wpDmFGPfb8CSsZzk9

**Comment by andregm3** [comment]
I just force update my generic bluetooth driver from a 2006 driver to 2.3.0.0	2013-10-09 on Windows 10 and now PS Move Service recognized it !!

**Comment by HipsterSloth** [comment]
Oh excellent! Do you happen to know what chipset your bluetooth adapter is? Maybe it will say in the device manager? I want to add your info to the troubleshooting page for anyone else who comes across the same problem.

**Comment by andregm3** [comment]
![imageproxy](https://cloud.githubusercontent.com/assets/4154732/16705377/8dce2750-455e-11e6-8eea-1cacf9a9364f.jpeg)

**Comment by andregm3** [comment]
My next Step is to make it work with RiftCat / VRidge for Google VR Cardboard devices !

**Comment by andregm3** [comment]
Generic Bluetooth USB Driver Download:

https://drive.google.com/file/d/0B_FcWl4MpE_BSzRlTWloNzg3Tnc/view?usp=sharing

**Comment by andregm3** [comment]
MotionInJoy + ipisoft recorder:

https://www.youtube.com/watch?v=Brxvz4Xsios

**Comment by cboulay** [comment]
We won't be supporting MotionInJoy.

I don't think it's yet time to start a table of BT dongles known to work with PSMove in Windows10, but if we do then I need to remember to come back to this issue.
