### ISSUE TITLE
Can I use 2 PS eye camera instead of 1?

### ISSUE THREAD

**Issue by booty156** [cboulay/PSMoveService#110]
Will I be able to get positional tracking from 1 camera or do I need 2 cameras to do so.

Also is room scaling possible with this

**Comment by HipsterSloth** [comment]
You can get positional tracking from just one camera, but it has to use the bulb size in screen to estimate distance so it's more noisy than if you have two or more cameras to triangulate the controller. We currently support up to 4 cameras. The max tracking distance from the camera is a not 5-6 feet. The fov is 75 degrees which is a bit on the narrow size. So I wouldn't say you could get room scale per se, but you can get 360 degree coverage with 3 cameras.

**Comment by booty156** [comment]
Ok, thank you. So will 3 camera be able to do room scale? Where would I put them?

**Comment by HipsterSloth** [comment]
I guess it depends on what you define as "room scale". If your room is a tiny office like the room I tested in, then sure. You could so something like this:

![layout](https://cloud.githubusercontent.com/assets/16793853/16716421/3238cb58-46b1-11e6-8a70-39c211340524.jpg)

But definitely not Vive or Oculus tracking volume sizes. I am working on supporting higher resolution cameras that will help with range, but for the time being the best volume size you are going to get is around 6 feet x 6 feet

**Comment by booty156** [comment]
Ok only have a area of 6feet x 6 feet. Thank you

**Comment by booty156** [comment]
Would this work with Vridge?

**Comment by HipsterSloth** [comment]
PSMoveService doesn't explicitly support VRidge, but there is another SteamVR plugin for VRidge that you can use along side PSMoveService. I have no experience with that. But @zelmon64 and few others who have posted on here have set that up.

**Comment by HipsterSloth** [comment]
I'm closing the issue for tracking purposes since it looks like we answered the original question, but please feel free to continue discussion if you have any other questions related to this issue.
