### ISSUE TITLE
Controller not tracking on Steam VR

### ISSUE THREAD

**Issue by andregm3** [cboulay/PSMoveService#111]
I'm getting this error: Controller not tracking
This controller is connected but not tracking. Make sure it can see a base station.

I can see the camera image on PSMoveConfigTool.exe

![er](https://cloud.githubusercontent.com/assets/4154732/16719516/a4a2cf22-4701-11e6-9d74-723af0d9a5bf.png)

**Comment by andregm3** [comment]
i bought CL EYE, but how to use that instead of LibUSB ?

**Comment by HipsterSloth** [comment]
Some questions for you:
* Are you using 1 camera or more than one camera? If just one camera you shouldn't need to do anything more than install the CLEye driver. The camera should show up when you run the test_camera.exe tool.
* Have you run the color calibration steps from here: https://github.com/cboulay/PSMoveService/wiki/Color-Filter-Calibration
* Have you already run the SteamVR setup steps from here:
https://github.com/cboulay/PSMoveService/wiki/Steam-VR-Setup
In particular the part where you add the `"activateMultipleDrivers" : true` line to steamvr.vrsettings?

**Comment by andregm3** [comment]
it says failled to start controller stream, when i try to calibrate colors,

i was using LibUSB then decided to buy CL Eye, but on Tracker Settings says: Controller Type: LIBUSB   how to turn it to CL Eye now ?

**Comment by HipsterSloth** [comment]
Oh sorry, showing "LibUSB" when you have installed CLEYE is a UI bug. If you see "CL Eye Driver being used with native DShow. Setting m_index to 0" in the log then you are using the CLEye driver. 

If you see "failed to start controller stream" that means that it's not getting data from the controller and is refusing to proceed with the color calibration. 

Do you see the controller in the "Controller Settings" panel? Do you have the controller turned on (i.e. is the red light on?)

**Comment by andregm3** [comment]
The controller works on every other test, rotates and lights

**Comment by andregm3** [comment]
Also, how to pair the second controller ? because after i paired one, the only option it shows is to unpair remove, not to add other

**Comment by andregm3** [comment]
somehow all started to work ! 

![0665bc8e-f530-4dba-8a10-914c0ad78d3c](https://cloud.githubusercontent.com/assets/4154732/16722418/bd67e874-471c-11e6-97c4-8fd96565d762.jpeg)

**Comment by HipsterSloth** [comment]
Oh excellent! Glad you got that working. Sorry the setup process is so complicated. We're trying to work on improving that. 

> The controller works on every other test, rotates and lights

Is it still doing this or is it working consistently now?

> Also, how to pair the second controller ? because after i paired one, the only option it shows is to unpair remove, not to add other

It should only show the unpair option when you have a controller plugged into usb that is currently paired. So if you had both controllers plugged into USB and one of them was paired and the other wasn't, you would still see the "unpair" option.

**Comment by andregm3** [comment]
yes, now i know how to set it UP ! =D just fot both tracking on Steam VR !!

**Comment by HipsterSloth** [comment]
Good to hear. If it's ok with you I'm going to close the issue for tracking purposes. But feel free to re-open it if something else comes up.

**Comment by andregm3** [comment]
i had some pair problems, but i discovered if i close the PSMoveConfigTool.exe and pair on the windows bluetooth it pairs !
