### ISSUE TITLE
The tracker is reversed in SteamVR

### ISSUE THREAD

**Issue by demonixis** [cboulay/PSMoveService#114]
Hi,

I use the latest release with SteamVR and I try to calibrate my moves. The tracking origin seems reversed as you can see on this screenshot

![2016-07-12-pm_01_23_57-layer](https://cloud.githubusercontent.com/assets/1017126/16767114/29a55900-483e-11e6-9e19-3f69ac0e5c92.png)

How to fix that? I'm pretty close to use it :)

Thanks.

**Comment by zelmon64** [comment]
Do you mean reversed as in the PSEye is upside-down? Try redoing calibration and making sure SteamVR is running when you do for co-registration.

**Comment by demonixis** [comment]
Yes but I tried without success. When the camera as the good place, the tracking space is inversed on the Z axis. I use calibration mat with one or two tracker.

**Comment by zelmon64** [comment]
Are you sure that the tracker calibration is working correctly (ie. that the masks are set correctly)? 

The z axis calculation works differently when there is only one tracker compared with multiple trackers. This should't have a major difference only that whe using only one the position of the PSMoves may be a bit more jittery. When you tried it with two were they shown in relatively correct positions? 

Do you have the mat orientated correctly (numbers 4 and 5 to the front)?

**Comment by demonixis** [comment]
If I use one or two cameras, masks are correct.

I did a simple test, using one camera and attaching a move to my HMD. When the calibration is done, I can't see my move, I have to turn my head (180°) and I can see it. I can try to make a video to show you.

**Comment by HipsterSloth** [comment]
If you open the "Test Tracker Video Feed" in the Config Tool for one of your cameras, then write "Hello" on a piece of paper and hold it in front of the the tracker you see this correct?

![configtool](https://cloud.githubusercontent.com/assets/16793853/16547907/9c95850c-4131-11e6-87fd-e2e98fc90df4.jpg)

Basically I'm wondering if your video feed is not getting flipped like it's supposed to.

**Comment by andregm3** [comment]
![helo](https://cloud.githubusercontent.com/assets/4154732/16831980/6c52fdb6-497e-11e6-8515-efc0e120ee6f.png)
