### ISSUE TITLE
Tracking is way behind when trying to calibrate position

### ISSUE THREAD

**Issue by jlk36** [cboulay/PSMoveService#117]
My controllers sync and the orientation works beautifully but when i try to do the positional tracking with the calibration mat the cross hair does not seem to follow the bulb in a timely matter with upwards of a 30 second delay. It seems that it gets behind when the calibration starts and it makes it near impossible to calibrate.

**Comment by HipsterSloth** [comment]
Woah. That sounds crazy. My best guess is that the USB root hub the ps3eye camera is plugged into has too much traffic. Is the camera plugged into the motherboard or a hub? Do you have any other cameras plugged in? You might try switching usb ports. If you do, check Zadig to make sure that the libusb driver is still installed as the libusb driver.

**Comment by jlk36** [comment]
Thanks for the quick response. I have two pseye cameras plugged directly into my motherboard switched usb ports and reinstalled drivers but it is still has that lag. i don't have any cameras plugged in but i do have a lot of usb devices plugged in.

**Comment by HipsterSloth** [comment]
Before you unplug anything I'd be curious to see if you are experiencing the same lag in the video feed when running the test_camera.exe

**Comment by jlk36** [comment]
Nope, test_camera.exe works without any stutters or spikes.

**Comment by HipsterSloth** [comment]
Interesting. What happens if you run test_camera.exe and the launch psmoveservice.exe? I would expect psmoveservice.exe to complain about not being able to open the cameras (because they are in use). But i'm curious to see if connecting to the controllers is causing the problem.

**Comment by jlk36** [comment]
So when i opened the service test_camera.exe stop reciving video and was just frozen on the last frame i coppied the startup message and put it into a text file here.
[Psmoveservice_startup.txt](https://github.com/cboulay/PSMoveService/files/362823/Psmoveservice_startup.txt)

**Comment by cboulay** [comment]
How is the tracker color calibration working for you in masked view?
I'm wondering if maybe what you're seeing isn't lag, but rather the tracker isn't getting ANY position except once every 30 seconds or so.

**Comment by HipsterSloth** [comment]
Ah ok. Maybe PSMoveService isn't actually opening the camera exclusively. So that ended up not being a helpful test. Next I would try moving your bluetooth adapter to a different port. If that doesn't work, you might also try unplugging devices one at a time to see if another device is interfering.

**Comment by jlk36** [comment]
thanks i'll try that out now.

**Comment by jlk36** [comment]
Hey Cboulay here are my two masked screens if you wanna take a look
![masked view](https://cloud.githubusercontent.com/assets/20448707/16824936/f705bd68-493d-11e6-9eaf-94aa06ab925d.jpg)

**Comment by HipsterSloth** [comment]
Those look correct to me.

**Comment by HipsterSloth** [comment]
How is the tracking in the color calibration screen btw? That has a single video feed and the controller feed active.

**Comment by jlk36** [comment]
Works like a charm, No stutters or drops.

**Comment by HipsterSloth** [comment]
If you only have one camera connected does the positional tracking calibration work without lag?

**Comment by jlk36** [comment]
it seems to  have slightly less lag i took a picture of the lag here.
![lag](https://cloud.githubusercontent.com/assets/20448707/16825309/935c8a2c-4941-11e6-9c49-e48eed367d74.jpg)

**Comment by HipsterSloth** [comment]
That is crazy. So just to be clear the video fees is fine it's just the white dot that's trailing behind?

**Comment by jlk36** [comment]
yep that's my problem

**Comment by jlk36** [comment]
The tracking seems to work ok in steam vr just it i s high above my headset. but i think others have had that problem and there is a fix by editing one of the config files correct?

**Comment by HipsterSloth** [comment]
In issue #113 I refer to the hmd tracking space offset. Though that didn't seem to fix it for them. I'd be curious if adjusting that worked for you.

If the tracking isn't laggy in steamvr that makes me think that the config tool is getting a super buffered controller data stream for some reason. 

What happens if you uninstall the steamvr psmove plugin and then run the position config tool?

**Comment by jlk36** [comment]
so changing the height in the TrackerManagerConfig.json config file did work for me after restarting the service.

**Comment by jlk36** [comment]
Still getting approximately a 10 sec lag on tracking calibration

**Comment by cboulay** [comment]
What are your PC's specs?
Which version of PSMoveService are you using? A release or did you build yourself?
@HipsterSloth Any chance one of the releases were built with a version of OpenCV that requires some specific instruction sets that older processors might not have?

**Comment by jlk36** [comment]
I currently am running an i5-2500k @ 4.2Ghz w/ 12gb of 1600Mhz ram, and a GTX980

**Comment by HipsterSloth** [comment]
@cboulay so far every release has been built using the opencv 3.0 binary release (msvc 2013). I don't know what processor specific options that has.

**Comment by cboulay** [comment]
Yeah and I didn't think when I posted but @jlk36 said the tracking works in SteamVR, so it's not the tracker algorithm. I'm just grasping at straws.

**Comment by HipsterSloth** [comment]
@cboulay yeah i'm out of ideas too. I think we just need some perf logging people can turn on. How long it's taking to process frame, at what time the client and server are getting each data frame, etc.

**Comment by jlk36** [comment]
just wanted to chime in that i did a fresh install of windows today and the tracking is fixed. Thanks for the responses.
