### ISSUE TITLE
tracker & controller need information from each other to calculate most recent pose.

### ISSUE THREAD

**Issue by cboulay** [cboulay/PSMoveService#12]
Currently the device managers call `.update()` and that's it. However, to calculate pose, the tracker(s) needs to know the controller colours from the controllers, and the controllers need to know the latest position from the tracker(s). So we need to replace the device manager .update() with 3 steps, and change the order around a little.

```
void DeviceManager::update()
{
    m_controller_manager.update();
    m_tracker_manager.update();
    m_hmd_manager.update();
}
```

becomes

```
void DeviceManager::update()
{
    m_tracker_manager.poll(); // Update tracker count and poll video frames
    m_controller_manager.poll(); // Update controller counts and poll button/IMU state
    m_hmd_manager.poll(); // Update tracker count
 
    m_tracker_manager.updateStateAndPredict(); // Get controller colors and update tracking blob positions/predictions
    m_controller_manager.updateStateAndPredict(); // Compute pose/prediction of tracking blob+IMU state
    m_hmd_manager.updateStateAndPredict(); // Get the pose + prediction for HMD
 
    m_tracker_manager.publish(); // publish tracker state to any listening clients (probably only used by ConfigTool)
    m_controller_manager.publish(); // publish controller state to any listening clients  (common case)
    m_hmd_manager.publish(); // publish hmd state to any listening clients (probably only used by ConfigTool)
}
```

The device managers still need information from each other. Maybe they can do this via the DeviceManager singleton (i.e., `DeviceManager::getInstance()->getControllers`) or we can pass in context arguments to the `updateStateAndPredict` functions.

**Comment by HipsterSloth** [comment]
The framework for this is now in place and running. You can see the position data being feed through here in the tracker calibration tool: https://www.youtube.com/watch?v=FFJqLH_dkRw

I'm going to create separate tasks/bugs for the DS4 tracking and the ellipse fitting issue
