### ISSUE TITLE
Controller appears behind me, or other odd places.

### ISSUE THREAD

**Issue by ToppestOfDogs** [cboulay/PSMoveService#120]
I've been having trouble tracking my controller. the actual movements are working fine, but it's always appearing in the wrong place. It's worse when I use the tracking mat, it always appears way off in the distance and usually points in the wrong direction, but when I use HMD tracking, it almost works, but the position relative to my body is just a bit off.
I've recorded a video of it in Tabletop Simulator, as you can see it tracks alright, but the controller appears behind me and a bit too high.

[Tabletop Simulator 7_16_2016 11_00_08 AM (2).zip](https://github.com/cboulay/PSMoveService/files/367333/Tabletop.Simulator.7_16_2016.11_00_08.AM.2.zip)

I'm using only one camera, which also appears in the wrong location in Steam VR.

**Comment by cheddle** [comment]
I found redoing the pose calibration a few times finally landed me a calibration that was usable. I think a single camera can only use the sphere size to guess the distance... and thats a tricky thing. Maybe the ps3 uses some logic to fine tune to exposure/gain/colour calibration on the fly to do a better job of this than this service can do.

**Comment by papalasarou** [comment]
Im having the same prob i get the controllers picked up etc.. but they are appearing behind and above me - ive tried calibrating using the mat several times no joy -any tips on how i should be claibrating.  my camera is on a tripod abput a meter and half away from my game area etc..

**Comment by onkkos** [comment]
I am having  the same problem and I tried to calibrate with the psmove controller on the left side of headset instead of the right, but my headset on the PsMoveConfigTool always  ends looking to the oposite side related to the controller. Would be interesting if we could rotate the headset axes, but I dont know if this is hard to implement.

**Comment by Gary00** [comment]
Having the same problem using the tracking mat. Everything seems fine until this step. Everytime it seems like they're in a different spot.

**Comment by HipsterSloth** [comment]
I think something changed in OpenVR recently that affects the raw HMD tracking space I use to align the psmove tracking space OpenVR. I was able to repro this issue last night, but couldn't figure out what the problem was. Stay tuned...

**Comment by HipsterSloth** [comment]
Closing old support issues. If this is still a problem please post a request to the google group:

https://groups.google.com/forum/#!forum/psmoveservice
