### ISSUE TITLE
SteamVR not detecting PS MOVE

### ISSUE THREAD

**Issue by Joakia12** [cboulay/PSMoveService#125]
Hello :) I cant connect my move controllers and camera to steamvr. I have completed the whole calibration and I followed the tutorial, but the controllers are still grayed out in steamvr. What can I do to solve this? 

Also, I cant find the steamvr.vrsettings in my steam folder, so I cant set "activateMultipleDrivers" to true.

**Comment by orangy57** [comment]
how did you fix the problem?

**Comment by Joakia12** [comment]
I dont remember. I kinda gave up and bought a HTC VIVE :P
