### ISSUE TITLE
PS Move Controller Not Detecting

### ISSUE THREAD

**Issue by Figuration** [cboulay/PSMoveService#129]
The PSMoveService launches and the camera works, but the software (or maybe PC) does not properly detect the move controller. Don't know what to do.

PSMoveService Text
[2016-07-22 15:45:24.797530]: main - Starting PSMoveService
Config file name: "C:\Users\Ryan\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
[2016-07-22 15:45:24.813158]: bluetooth_get_host_address - Found a bluetooth radio
[2016-07-22 15:45:24.813158]: bluetooth_get_host_address - Retrieved radio info
Config file name: "C:\Users\Ryan\AppData\Roaming\PSMoveService\TrackerManagerConfig.json"
[2016-07-22 15:45:24.954215]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\6\0, camera_index=0)
ps3eye::PS3EYECam::getDevices() found 1 devices.
Config file name: "C:\Users\Ryan\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b2_p3.json"
Config file name: "C:\Users\Ryan\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b2_p3.json"
Config file name: "C:\Users\Ryan\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b2_p3.json"
[2016-07-22 15:45:25.129548]: SharedMemory::initialize() - Allocating shared memory: tracker_view_0
[2016-07-22 15:45:25.145196]: DeviceTypeManager::update_connected_devices - Device device_id 0 (PSEYE) opened
[2016-07-22 15:45:28.153011]: ClientConnection::start - Starting client connection id 0
[2016-07-22 15:45:28.155013]: ClientConnection::send_connection_info - Sending connection id to client 0

PSMoveConfigTool
ERROR [OpenVRContext::startup] Failed to initialize OpenVR: Hmd Not Found Presence Failed (126)!
INFO [App::init] Failed to initialize OpenVR!
INFO [Renderer::init()] Initializing Renderer Context
[INFO] ClientNetworkManager::start_tcp_connect - Connecting to: 127.0.0.1:9512...
[INFO] ClientPSMoveAPI - Successfully initialized ClientPSMoveAPI
[INFO] ClientNetworkManager::handle_tcp_connect - Connected to 127.0.0.1:9512
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 1
[INFO] ClientNetworkManager::handle_tcp_connection_info_notification - Got connection_id: 0
[INFO] ClientNetworkManager::send_udp_connection_id - Sending connection id to server over UDP: 0
[INFO] ClientNetworkManager::handle_udp_write_connection_id - Successfully sent UDP connection id
[INFO] ClientNetworkManager::handle_udp_read_connection_result - UDP Connect Success!
[INFO] handle_server_connection_opened - Connected to service
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 2

**Comment by cboulay** [comment]
What happens when you try to [pair the controller](https://github.com/cboulay/PSMoveService/wiki/PSMove-Bluetooth-Pairing)?

**Comment by Figuration** [comment]
It won't even show it in the service. Or bluetooth. The pc detects the
controller as HID compliant keyboard and mouse. As I looked into it some of
the drivers it auto installer were motioninjoy but I removed that.

**Comment by Figuration** [comment]
On Fri, Jul 22, 2016 at 3:53 PM, Ryan Silva <thegamingdatabase1934@gmail.com

**Comment by cboulay** [comment]
Do you mean that when you plug it in via USB cable, Windows installs it as a KB+M, and PSMoveService can't detect it?

When I plug my PSMove into my Windows 10 PC via USB windows installs it as a "Motion Controller".

My guess is that you didn't fully uninstall MotionInJoy. You probably have some .inf's lying around that are being used by Windows whenever you plug in the device. I think MotionInJoy is difficult to uninstall fully.

**Comment by Figuration** [comment]
Ah okay thank you  I'll try. I'll get back to you.

**Comment by Figuration** [comment]
Forgot to get back, but uninstalling the drivers worked. Thank you!

**Comment by HipsterSloth** [comment]
Closing since it sounds like this is fixed for you. But feel free to continuing commenting in the issue if need be.

**Comment by SuicideLoser** [comment]
As far as I understand, the problem was that the PC was installed as a mothion controller device? If so, how do I fix it? Uninstalling the driver caused it to reinstall the device with the same name
