### ISSUE TITLE
Is it possible to add kinect as position tracker for psmove service?

### ISSUE THREAD

**Issue by Nirvanana** [cboulay/PSMoveService#132]
I guess you are using part of OSVR functions for communication?
If so I found a project works on OSVR that uses kinect as the position tracker for head/body:
https://github.com/simlrh/OSVR-KinectV2
Is it possible to combine them so controllers can be calibrated to move with respect to headset but not PS3 eye.
I will look more into it and make a pull request if I can.
Thanks.

**Comment by cboulay** [comment]
Can you describe what you mean in more detail?

**Comment by Nirvanana** [comment]
I have a VR headset now but I don't have HMD tracking like lighthouse.

When I use psmove service I can only use the mat to calibrate controllers and their position is in respective of PS3 eye.

When I seat even a little bit left/right I feel uncomfortable cuz controllers are not at the right position with respect of my headset(body) anymore. e.g. the controller goes further forward if I move forward a little bit.

Kinect v2 is a powerful IR camera which is able to detect people's body. 

If we can use kinect v2 to track the position of HMD and use the "Coregistration with HMD" method to calibrate the poses it would be a perfect solution (for me at least).

**Comment by toto5100** [comment]
How Kinect could track an HMD ? As far as i know, the sdk is made for tracking bodies. The main problem is the integration with OpenVR. If your headset is not position tracked, it do not really makes sense to do a coregistration. A simple offset option would be enough.

**Comment by Nirvanana** [comment]
I think it just track the head instead of HMD.

Here is a video of a demo:
https://www.youtube.com/watch?v=KFcZ4NNDod4

And a link to some instructions:
https://www.reddit.com/r/OSVR/comments/4rof7n/using_kinect_v2_as_a_position_tracker_for_the_hdk/

**Comment by zelmon64** [comment]
@Nirvanana I believe the controllers use a OpenVR plugin instean of OSVR. For the kinect to provide positional data it would need to be supported by the software used by your HMD not PSMoveService (such as how VRidge can be fed data via FreeTrack).

**Comment by Nirvanana** [comment]
@zelmon64 
I haven't looked into the code

but the readme file https://github.com/simlrh/OSVR-KinectV2 says :
"An OSVR plugin providing Kinect SDK v2 position and orientation joint tracking, for use with a Kinect for Xbox One."

I guess it draws data from kinect by kinect SDK and pass it to OSVR, and OSVR has another plugin for openvr that's why it worked on steam.

For my headset, it is just like a cracked version of oculus dk2 which is compatible with oculus runtime and openvr.

Anyway it's glad to see this solution is plausible.

Here is one more video of that guy using psmove service and kinect tracking at the same time:
https://www.youtube.com/watch?v=UrlbAuRo5q8

**Comment by godbyk** [comment]
@Nirvanana The PSMoveService doesn't (yet) use OSVR. It takes directly to SteamVR.

So what is happening is that the PS controllers are in a different coordinate frame (they have a different origin) than the HMD. And since SteamVR doesn't know where the PSMove's cameras are in relation to the HMD's camera, it can't align them. It just assumes both cameras are in the same place. (If you move the PSMove camera and the HMD camera so they're right next to each other, it should help align things better.)

Once there is a PSMoveService plugin for OSVR, we can align the controllers' coordinate frame with the HMD's coordinate frame and feed these adjusted coordinates to SteamVR so everything will be aligned properly. (I'm working on the controller code for SteamVR-OSVR and on writing a utility to handle this coordinate frame alignment.)

**Comment by HipsterSloth** [comment]
Since we already have issue #44 for adding OSVR support and (Kinect support is outside the scope of PSMoveService's planned work) I'm going to close this issue, but feel free to continue chatting here.

**Comment by imeetyouagain1** [comment]
I know I'm a year and half late, but if you haven't found a way yet (perhaps you have, ignore me if so), Driver4VR allows you to use either Kinect version to track head/hands/body with support for PSMS, I believe with either PS Eye cameras or replacing them with the Kinect. 
Best Regards,
imeetyouagain1
