### ISSUE TITLE
Expose Velocity and Acceleration to SteamVR plugin

### ISSUE THREAD

**Issue by farid00** [cboulay/PSMoveService#133]
Noticed that in SelfieTennis and opening part of budget cuts(didn't play past opening). When I would try to throw the racket, ball, or cans, they would just fall to the floor from where I released the trigger.  Does PsMoveService track acceleration/velocity for throwing things? I had this happen with one and two camera setups if that makes any difference.

**Comment by HipsterSloth** [comment]
The acceleration and velocity are currently zero'd out in the steamvr plugin. That data won't be available until the Kalman filter is finished. As one point I was estimating the velocity and acceleration using a simple smoohted position difference / dt but the result was too noisy so I pulled it out.

**Comment by cheddle** [comment]
Is this why the Nvidia Fun house does not work?

**Comment by cboulay** [comment]
@farid00 

The velocity and acceleration come from a state-space model. The state space model is currently not being built or updated, but I'm working towards that. The basic premise is that we feed sensor values into a Kalman filter and then use that to update the model.

Head on over to #13 Get caught up. Try out different Kalman filter parameters. (Ask any further questions in #13)

**Comment by HipsterSloth** [comment]
@farid00 In addition to this issue, there are a lot of other tasks we could use help with. If you are interested and have time, look through all of the issues posted (particularly with those labeled "help wanted") and see if that's something you might be interested in. If so, ask questions in that issue about how the implementation should be done. Then make a fork of PSMoveService, work on the issue in your fork, and then submit a pull request for your change when done.

**Comment by farid00** [comment]
@cboulay my very limited C++ and VR positional knowledge makes most of this seem pretty over my head but i'll continue to dig into in my spare time and see if/where I could help.

**Comment by cboulay** [comment]
Closing this issue in favour of #13.
