### ISSUE TITLE
Steam VR Controller not rotating at all.

### ISSUE THREAD

**Issue by Figuration** [cboulay/PSMoveService#145]
In Steam VR the controller position tracks, just not any rotational data at all.

**Comment by HipsterSloth** [comment]
Have you already done the magnetometer calibration for your controller?

**Comment by Figuration** [comment]
@HipsterSloth yes. When I test tracking it rotates, but not in steam.

**Comment by HipsterSloth** [comment]
Closing old support issues. If this is still a problem please post a request to the google group:

https://groups.google.com/forum/#!forum/psmoveservice
