### ISSUE TITLE
SteamVR "The Lab" Slingshot button?

### ISSUE THREAD

**Issue by jimrooney** [cboulay/PSMoveService#147]
Anyone gotten the "Slingshot" game in SteamVR's "The Lab" to work?
For some reason, I can't grab the slingshot.
I can with my Leap Motion controller when I use that, but not with the PS Move. Everything else works and I can "Grip" things in other games... just not the slingshot for some reason. Is it mapped to a different button?

**Comment by HipsterSloth** [comment]
I hadn't tried the Slingshot game myself. You might have to grab using the "grip" button which is mapped to "square" button on the psmove controller.

Here are the default button mappings for SteamVR:
From https://github.com/cboulay/PSMoveService/wiki/Steam-VR-Setup:
```
   "psmove" : {
      "ps" : "system",
      "move" : "touchpad",
      "trigger" : "trigger",
      "triangle" : "application_menu",
      "square" : "grip",
      "circle" : "a",
      "cross" : "button_8",
      "select" : "button_9",
      "start" : "button_10"
   }
```

You can change the button mappings in steamvr.vrsettings if you want to assign "grip" to something else.

**Comment by jimrooney** [comment]
"grip" itself doesn't appear to work in The Lab.
It does seem to function in the SteamVR interface, although it can be hard to tell as there's nothing specifically to "grip"... it does go "up a level", which is what Leap Motion appears to do as well.

In The Lab, the "grip" function appears to be nonfunctional with PS Move.
"grip" in Leap Motion does work in The Lab.

Both of these are true not only in the Slingshot game, but in the Lab in general. I can pick up objects on the desk with the Leap, but not with the PS Move "grip"... I can with "trigger". "trigger" however does not function as a "grip" in the Slingshot game.

With the Leap, when I'm close to the Slingshot device, the Leap controller glows yellow indicating that I can grip. With the PS Move, it does not.

I can successfully remap buttons on PS Move but it doesn't fix the problem unfortunately.

It's a strange disparity.

**Comment by cheddle** [comment]
I can 'grab' the hanging control thing to the right of the sling shot however I cannot do anything with it once I have it - I imagine it wants to use the tactile pad as a quandrant'ed button.

My config below.

   "psmove" : {
      "circle" : "a",
      "cross" : "button_8",
      "move" : "touchpad",
      "ps" : "system",
      "select" : "button_9",
      "square" : "grip",
      "start" : "button_10",
      "triangle" : "application_menu",
      "trigger" : "trigger"
   },

**Comment by ReallyDiskun** [comment]
For me it works only the first time with the trigger. Other items in the room seem to work well too. However for some reason the slingshot stops interacting with my PSMove controller after the first shot.

The Lab also crashes pretty frequently on me, specially on the Longbow stage. Seems it has something to do with PSMoveService, but I don't know why. I'm going to build from the latest source which has some bugfixes and try again.

**Comment by HipsterSloth** [comment]
Closing old support issues. If this is still a problem please post a request to the google group:

https://groups.google.com/forum/#!forum/psmoveservice
