### ISSUE TITLE
PSMoveService doesn't work after restart

### ISSUE THREAD

**Issue by NyanBlade** [cboulay/PSMoveService#149]
I had this issue before but now it happens after every restart.

[2016-08-03 19:50:55.332336]: main - Starting PSMoveService
Config file name: "C:\Users#####\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
[2016-08-03 19:50:55.342845]: bluetooth_get_host_address - Found a bluetooth radio
[2016-08-03 19:50:55.347348]: bluetooth_get_host_address - Retrieved radio info
Config file name: "C:\Users#####\AppData\Roaming\PSMoveService\TrackerManagerConfig.json"
[2016-08-03 19:50:55.367869]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\8\0, camera_index=0)
ps3eye::PS3EYECam::getDevices() found 3 devices.
Config file name: "C:\Users#####\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b3_p9.3.json"
Config file name: "C:\Users#####\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b3_p9.3.json"
Config file name: "C:\Users#####\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b3_p9.3.json"
[2016-08-03 19:50:55.551505]: SharedMemory::initialize() - Allocating shared memory: tracker_view_0
[2016-08-03 19:50:55.556009]: EXCEPTION - PSMoveService - boost::interprocess::intermodule_singleton initialization failed
Config file name: "C:\Users#####\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
[2016-08-03 19:50:55.565519]: SharedMemory::dispose - Failed to free shared memory: tracker_view_0
[2016-08-03 19:50:55.570022]: ClientConnection::stop - Stopping client connection id 0

**Comment by HipsterSloth** [comment]
Looks like this is issue #89 again. Does the work around from that issue fix it for you?

> So as far as I get from internet problem may occur when boost::interprocess failed to get temporary directory on Windows as it's use following registry key by default: 
Code:
SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\Common AppData

>It's may occur when user modify registry with tools like CCleaner, but can be fixed by system reboot. It's should be possible to bypass that problem by setting "BOOST_INTERPROCESS_SHARED_DIR_PATH" so boost store shared memory in some other directory on Windows.'

>I opened regedit and found the "SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\Common AppData" registry key. It pointed at C:\ProgramData. I looked in there and there was the following folder C:\ProgramData\boost_interprocess\1466482908 containing a tracker_view_0 and tracker_view_1 files.

>See if that registry key exists on your machine. If it does, go to the folder it specifies. If you're running win10 it almost certainly is also C:\ProgramData. **Then if you have a C:\ProgramData\boost_interprocess folder, delete the files in there.** My bet is the interprocess state in there is borked and deleting them will create new ones with valid state."

If this does fix the problem for you still leave this issue open, because the underlying problem still exists.

**Comment by NyanBlade** [comment]
Unfortunately this is no longer fixing the issue. I also tried deleted the PSMoveService folder in AppData\Roaming and using SteamVR_UninstallDriverWin64 but it's not working. I get the same output when starting PSMoveService, also only one PSEyeTrackerConfig is now in AppData\Roaming\PSMoveService but I have 3 cameras, it seems to be loading this 3 times.

**Comment by HipsterSloth** [comment]
If you run test_camera.exe (with PSMoveService closed) do you get only one camera stream or 3 camera streams?

**Comment by NyanBlade** [comment]
3, they are all working

**Comment by HipsterSloth** [comment]
Oh. I think you are only getting one PSEyeTrackerConfig file because the service is dying after trying to open the shared_memory for the first camera stream, so it can't save out the config file for the other two cameras. That log message just means that PSMoveConfig::getConfigPath() is getting called 3 times, not necessarily that it's trying to open the same camera 3 times. I see the same set of 3 "config filename" messages show up on my machine. That said, I should check really quick to make sure I'm not actually trying to open each camera 3 times and you just happen to be hitting some IO error I'm not.

**Comment by NyanBlade** [comment]
For anyone else that may have the same problem, this is what I just did to get it working again, I still have to see if it works after setting it up again and rebooting.

Go to C:\Users\#####\AppData\Roaming and delete the PSMoveService folder (backup/rename first)
Go to C:\ProgramData\boost_interprocess and delete everything in there
Run SteamVR_UninstallDriverWin64.bat
Open CCleaner, go to Options, Exclude, Add, and then under Driver or Folder enter C:\ProgramData\boost_interprocess\
Reboot
Open zadig and reinstall the libusb driver for the cameras
Run

**Comment by HipsterSloth** [comment]
Oh did you just find this github issue talking about the CCleaner fix as well?
https://github.com/networkMe/missinghud2/issues/8

I'll add those steps to the troubleshooting wiki. Thanks!

**Comment by NyanBlade** [comment]
Yeah, that's what I just used. Now my controllers are acting strange, they are rotating by themselves, I have tried recalibrating the magnetometer a few times but they are still turning, they were working fine before.

**Comment by HipsterSloth** [comment]
Did you still have the old controller config files (the ones named `xx_xx_xx_xx_xx_xx.json`?) If so you could compare the "magnetometer" calibration settings from the new config with the old ones. They readings should be nearly identical, in particular the "Identity" value that identifies where magnetic north is.

**Comment by HipsterSloth** [comment]
Sorry I haven't replied to this in a while. Been swamped with DS4 stuff. Are you still hitting this issue?

**Comment by NyanBlade** [comment]
Yeah still having the issue where it won't start, also the controller's orientation feel like they lag behind a bit as they move

**Comment by HipsterSloth** [comment]
Wait. If PSMoveService won't start how are you testing the controller orientation lag (can't get controller data if the service isn't running)? Do you mean it starts sometimes and not others? And if it's not starting are you getting the "boost::interprocess::intermodule_singleton initialization failed" error or something else?

**Comment by NyanBlade** [comment]
Sorry didn't explain that at all, yeah I can't remember what I did to get it working yesterday as I have to do different things to get it working each time. But right now it's starting up and I can't get it started, it's the same error also some libusb can't share parent error on the new alpha. When it did work there was some lag in the rotation of the controller's but they moved fine.

**Comment by HipsterSloth** [comment]
Apparently restarting your machines sometimes breaks the camera libusb install. Try using zadig to assign libusbK, to the cameras then reassign libusb-win32. I have no idea why that would fix it, but apparently that helps some people.

From zelmon64 issue #168:
>if you now switch back to libusb-win32 does it work? This trick of having once used libusbK then using libusb-win32 used to be a big issue. It used to be that you'd have to switch back to libusb-win32 after a reboot because libusbK would then not work.

As for the orientation lag, do you see that same lag when you run the "orientation test" for the controller in the "Controller Settings" section of PSMoveConfig tool?

**Comment by NyanBlade** [comment]
I think this may be the issue, I have 3 cameras plugged in but two of them have the same ID:
USB Camera-B4.09.24.1 (Interface 0)
USB Camera-B4.04.27.1 (Interface 0)
USB Camera-B4.09.24.1 (Interface 0)

When I change one of the 09.24.1 drivers, the other 09.24.1 shows the same driver and this must be what the libusb error about cannot share parent is about?

**Comment by HipsterSloth** [comment]
Maybe? I know some USB devices are "composite devices". The have a parent controller and then child devices that route data to the parent. The PS4 camera is like this. I guess the ps3 eye must be like this too since it has the mic and the camera in the same device. Maybe the libusb driver got assigned to the mic device by accident (though I thought this was interface 1)?

Maybe starting from a clean slate is the best approach. Try unplugging all your cameras and running through the camera driver uninstall/reinstall steps here: https://github.com/cboulay/PSMoveService/wiki/Troubleshooting-%28Windows%29#general-weird-camera-behavior-clean-camera-driver-reinstall

**Comment by rovarma** [comment]
The cameras are supposed to have the same "id" (it's not an ID but just the device name). However, one thing that makes me suspicious is the second device you have (USB Camera-B4.04.27.1). The B#.##.##.# string is the version number of the camera. Off the top of my head, 4.09.24.1 is the most recent version, so 4.04.27.1 is something older. 

Maybe your problems stem from that; perhaps the firmware of the versions is different enough that the current driver doesn't work with it, or it's USB structure is different. I would try removing that camera and buying a more recent one, then trying again.

**Comment by duig0** [comment]
Im having the exact same problem - has the problem been sucessfully troubleshooted yet?

I spent a lot of time (and some money) setting this up - it looks wonderful on all the demo videos on youtube - but alas, im having no luck in getring it running 

Ive teied all thw steps mentioned here and over on issue #89 without success.

:-(

**Comment by duig0** [comment]
Thanks for the reply ozzeruk...no luck im afraid....I think its sown to how shared memory is allocated

**Comment by HipsterSloth** [comment]
Closing old support issues. If this is still a problem please post a request to the google group:

https://groups.google.com/forum/#!forum/psmoveservice
