### ISSUE TITLE
Need a textured 3D .obj model for the Navi controller

### ISSUE THREAD

**Issue by HipsterSloth** [cboulay/PSMoveService#151]
This was spawned off of issue #41. 

I need a 3d model (.obj format) with single texture for the playstation navigation controller to display in SteamVR and in the config tool. I'm currently using the psmove controller model as a stand in.

In SteamVR the model units are in meters. Once I have a. OBJ model for SteamVR I can add it into the config tool since there is a special process involved in doing that (need to run a perl script to turn the .obj into a c++ header file).

**Comment by ReallyDiskun** [comment]
My 3D modeling skills are a bit rusty but I'll try my best. Others are welcome to contribute too.

**Comment by andregm3** [comment]
https://www.cgstud.io/3d-model/sony-move-controller-21532

**Comment by HipsterSloth** [comment]
> https://www.cgstud.io/3d-model/sony-move-controller-21532

@andregm3 It's funny, I've actually used those very models internally at this studio. However I can't use paid models in PSMoveService. I don't mind buying them, but then I'm not allowed to distribute them. I need to include the source .obj files and that would be circumventing the artists ability to sell their model on cgstudio, since people could just get the models for free as part of this project.

**Comment by andregm3** [comment]
you could try asking for the guy who made the model if he could give a free model to the project and get the credits in change =]

**Comment by andregm3** [comment]
anyway he is selling a copyrighted product dont know how much legal is that

**Comment by HipsterSloth** [comment]
I think it would just be easier to have someone who has a bit of 3d modeling experience make a navi specifically for this project. As far as 3D models go it's not terribly complicated. I was debating doing it myself, but someone who knows what their doing in Blender could probably do it 10x faster than I could. That way we avoid any headaches trying to negotiate rights over a model.

**Comment by andregm3** [comment]
may you send me the model you have, i could reduce polygons and create a different model based on it

**Comment by andregm3** [comment]
andregm3@hotmail.com

**Comment by HipsterSloth** [comment]
I can just attach the zipped STL model here:
[dualshock_4.zip](https://github.com/cboulay/PSMoveService/files/411951/dualshock_4.zip)

I deleted your last post with your e-mail address so that you don't get spam.

**Comment by andregm3** [comment]
do you have the Nav ?

**Comment by andregm3** [comment]
Just converted to .obj so anyone could open it on Unity

**Comment by HipsterSloth** [comment]
Whoops. I'm sorry, I misunderstood. I thought I was in the DS4 issue not this one and you were asking for the DS4 model. I keep changing jumping between issues answering questions. Let me find the navi model I bought. Would you mind posting your e-mail again (i'll delete it after I copy it down this time).

**Comment by andregm3** [comment]
andregm3@hotmail.com
whats app: +55 48 9982-6602

get in touch

**Comment by andregm3** [comment]
I used this online 3D model conversor:

http://www.greentoken.de/onlineconv/

**Comment by andregm3** [comment]
Done !

![dsdsd](https://cloud.githubusercontent.com/assets/4154732/17570371/81424ed4-5f22-11e6-8a68-8e7c4529b96f.png)


LOL just kidding...

**Comment by andregm3** [comment]
https://sourceforge.net/projects/meshlab/?source=typ_redirect

**Comment by andregm3** [comment]
![reddd](https://cloud.githubusercontent.com/assets/4154732/17571291/04805388-5f26-11e6-81a0-bce622195d1d.png)

**Comment by HipsterSloth** [comment]
Oh that's a nifty tool. The company I work at has sent some models to shapeways for 3d printing before. That's good to know that tool exists for simplifying meshes.

**Comment by HipsterSloth** [comment]
Posting the .obj here.

[PSNavi_OBJ.zip](https://github.com/cboulay/PSMoveService/files/412172/PSNavi_OBJ.zip)

This still needs a texture map. I think a simple planar mapping will work. If no one gets to this in a week or so I'll try my best to texture map this myself in blender.

**Comment by andregm3** [comment]
![38bd1fe480dc21a896eeef2abfba2a43 1](https://cloud.githubusercontent.com/assets/4154732/17572996/dd3b15d0-5f2d-11e6-892a-677a0e813928.jpg)

**Comment by ReallyDiskun** [comment]
It's very far from perfect but I hope it's good enough.

![image](https://cloud.githubusercontent.com/assets/20774380/17604724/53ba3558-6017-11e6-82dc-f9d09fa2b012.png)

[PSnavi.zip](https://github.com/cboulay/PSMoveService/files/414240/PSnavi.zip)

**Comment by HipsterSloth** [comment]
@ReallyDiskun Awesome! Thanks for the texturing work. This will work great. 

I'll go ahead and mark this issue as resolved. I still have work to do on my end to incorporate the model and finish with the navi controller communication layer, but I'm glad to have this model ready. 

Thanks guys!
