### ISSUE TITLE
Connecting Playstation Move and Navigation controllers through bluetooth

### ISSUE THREAD

**Issue by billyisms** [cboulay/PSMoveService#152]
Would it be possible to connect the Move and Navigation Controllers as normal PC game controllers using this software? I have been using Motioninjoy, but would prefer connecting them through this software if it works well through bluetooth.

**Comment by HipsterSloth** [comment]
Not presently. What you're describing is a "filter driver" similar to [ScpToolkit](https://github.com/nefarius/ScpToolkit) for DualShock controllers. I think the ScpToolkit also does this navi as well, but not the PSMove. PSMoveService is a usermode program that provides controller data over a socket to client plugins (currently the only two clients are SteamVR and FreePIE). It's a non-goal of this library to remap the controller as other PC Game controller types.
