### ISSUE TITLE
Re calibrate center Headset button

### ISSUE THREAD

**Issue by HyppoNymous** [cboulay/PSMoveService#160]
The headset is always off and not centered around PS move calibration space.
Using one camera whatever calibration method i use , the headset is never centered to work with PSmove , they don't share the same space.
One button to only recalibrate and recenter the headset to the center of calibrated space would help.

**Comment by Bungpiece** [comment]
Not what your looking for but in the mean time you can manually make edits to a config file to change your orientation as detailed here. #113

**Comment by HyppoNymous** [comment]
I would like to have some option to tell config tool to read the heaset position and consider it as aligned and consider it at the same position as the PSmove controller position.
You hold PSmove and Headset at same position in space , you press a button and the Config tool will consider any headset movement relative to the new origin.

**Comment by cboulay** [comment]
It's not really up to PSMoveService to change the headset's reference frame in the game.

If you want a hotkey mapped to the typical HMD_reset (which zeroes the HMD's position and yaw in the game world) then that's up to the game to implement and map to a button, and we just have to make sure that button is mapped to something on the PSMove.

I think instead what you want is to recenter the PSMove space.

Anyway, your description of the problem (poor calibration with HMD space) is really no different than the dozen or so other posts. I'll close this as there is more than enough of those. We have a few fixes in the works that will improve tracking generally, then we can take a better look at coregistration problems.
