### ISSUE TITLE
idea HTC Vive circular touchpad emulation

### ISSUE THREAD

**Issue by HyppoNymous** [cboulay/PSMoveService#161]
In some games we need the touchpad to switch weapons for example.
Could we get some options in the PS move config tool to tell the mouse will emulate the touchpad or  pressing regular PSmove buttons : circle,triangle, square, cross buttons will act like using the touchpad ? 
This would help a lot.

**Comment by Bungpiece** [comment]
Can't find the post now but I believe there was talk  of implementing a button to act as a touchpad press and until it was released the directional tracking would act as touchpad input as a possibility later down the road. I'd imagine this would also depend on what happens with navigation controller support too as it has an analogue stick which could potentially perform the same function.

**Comment by HyppoNymous** [comment]
This would be graet to emulate touchpad with a button pressed than rotate around with PSmove to simulate Touchpad interaction.

**Comment by YossiMH** [comment]
@Bungpiece I've implemented the feature you've described and submitted a pull request: https://github.com/cboulay/PSMoveService/pull/205

**Comment by Bungpiece** [comment]
@YossiMH great work mate. As you mention in the pull request discussion this should add compatibility with quite a few programs that rely on swipes, make ui's easier to use and develop. I wish I knew where in the issues I saw the original idea but I've never seen the comment again.

**Comment by zelmon64** [comment]
@Bungpiece You probably saw it in [this reddit thread](https://www.reddit.com/r/SteamVR/comments/4imxdt/psmove_oculus/d3f1jfh) where I suggested it to HipsterSloth. I used it in the FreePIE script for the plugin of thp's PSMoveAPI [here](http://www.mtbs3d.com/phpBB/viewtopic.php?f=139&t=18265&p=161407&hilit=touch#p161407) and thought it was a good method.

@YossiMH Great work implementing this!

**Comment by Bungpiece** [comment]
@Zelmon64 Yep your spot on and all credit to you! No wonder I couldn't find it under issues.
