### ISSUE TITLE
idea 3rd PS move controller managed for head tracking

### ISSUE THREAD

**Issue by HyppoNymous** [cboulay/PSMoveService#162]
[https://www.youtube.com/watch?v=CSxavTvJ97Q](url)
This could help to have PS Move service able to track a third PSmove controller that we should configure as headset tracking, and let PSmove service manage to send information to StamVR ?
I use HDK 1.4 , but if i could use a third PS move with 3 cameras i would get a full 360 head tracking system lot more precise and better than one camera system from OSVR HDK.

**Comment by cboulay** [comment]
@HyppoNymous, please read through other issues, even closed ones, before posting new ones.
Closing in favour of #59

**Comment by Bungpiece** [comment]
Support for this was discussed in #59 
However @Hawkinse has developed a client and plugin for called freepieridge that was most likely what was being used in that video that takes psmoveservice data and puts it in freepie which riftcat then uses in steam vr see issue #53 In theory this might be doable without riftcat through osvr if/when support is implemented through the use of OSVR-fusion plugin. I think we would just need to be able to specify which controller we were trying to take the positional data from.
 https://github.com/simlrh/OSVR-fusion
