### ISSUE TITLE
PS move controller is always behind me and pointing the wrong way in steamVR 

### ISSUE THREAD

**Issue by booty156** [cboulay/PSMoveService#163]
I have redone it loads of times and still have the same error. I use VRidge/riftcat

**Comment by zelmon64** [comment]
Make sure your phone is connected and oriented forwards (with ctrl+shift+alt+R) while you run the tracker calibration.

**Comment by booty156** [comment]
I have

**Comment by booty156** [comment]
Should I use the mat or attach the ps move to the headset?

**Comment by zelmon64** [comment]
The mat. After the five poses it takes the direction of the HMD and at that point your phone needs to be pointing forwards.

**Comment by HipsterSloth** [comment]
Also make sure to use the release I just put out yesterday: https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha4.6

**Comment by booty156** [comment]
I try again using the mat and I am using that release

**Comment by booty156** [comment]
Still don't work

**Comment by HipsterSloth** [comment]
It's a more painful alternative, but you can manually edit your TrackerSettings file to force align the steamvr and psmove tracking spaces. See issue #113 about how to do this. We don't officially support the RiftCat yet so the support for this is pretty rough.

**Comment by zelmon64** [comment]
@booty156 I just ran some tests and you must restart SteamVR for the new alignment to take effect. I used this method to successfully rotate the PSMove forward direction to the left then back to the front.
* start and connect VRidge 
* start SteamVR
* start PSMoveService
* start calibration and ensure your HDM is looking forwards
* place the mat with the poses 4 and 5 to the front
* finish and close calibration
* restart SteamVR

Following that should result in the forward directions being aligned.

**Comment by booty156** [comment]
Thank you so much, IT WORKED :D

**Comment by HipsterSloth** [comment]
I updated the [troubleshooting guide](https://github.com/cboulay/PSMoveService/wiki/Troubleshooting-(Windows)) with Zelmon's notes. Thanks for the tech support!

**Comment by mjducharme** [comment]
Hi,

I fixed this by adjusting the global_forward_degrees setting in the tracker configuration json file. The default was 270 and when I changed it to 90, the SteamVR alignment exactly matched the results that I had just gotten inside the config tool.
