### ISSUE TITLE
steamvr file empty!! PLS HELP

### ISSUE THREAD

**Issue by cinema4d** [cboulay/PSMoveService#166]
My empty file - Why is that?
{
   "driver_vridge" : {
      "renderScale" : 100,
      "windowHeight" : 1080,
      "windowWidth" : 1920
   },
   "jsonid" : "vrsettings",
   "perfcheck" : {
      "heuristicActive" : true
   },
   "steamvr" : {
      "allowReprojection" : true,
      "showMirrorView" : false
   },
   "version" : "1"
}
this is all the code that is in the file

**Comment by zelmon64** [comment]
I think you're just missing enable multiple drivers (`"activateMultipleDrivers": true`) and perhaps `"requireHmd": false`. See [here](https://developer.valvesoftware.com/wiki/SteamVR/steamvr.vrsettings) for reference (although it doesn't appear to mention the multiple driver part).

**Comment by cinema4d** [comment]
I do not understand, I have to copy the code into your file?

**Comment by zelmon64** [comment]
I'm saying that it's not that empty. You're probably only missing one or two lines. You probably only need to add the multiple driver line like this:

```
{
"driver_vridge" : {
"renderScale" : 100,
"windowHeight" : 1080,
"windowWidth" : 1920
},
"jsonid" : "vrsettings",
"perfcheck" : {
"heuristicActive" : true
},
"steamvr" : {
"allowReprojection" : true,
"showMirrorView" : false,
"activateMultipleDrivers" : true
},
"version" : "1"
}
```
(note the extra comma needed before `"activateMultipleDrivers" : true`)

**Comment by cinema4d** [comment]
and after editing the file to install the drivers?

**Comment by zelmon64** [comment]
You mean the PSMoveService SteamVR driver? Then yes. It looks like you already have the VRidge driver installed. 

Just so you know, SteamVR drivers don't actually get _installed_ but registered with SteamVR instead.

**Comment by cinema4d** [comment]
Steam sign appeared controller and camera, but PSmoveKonfigTool crashed!

**Comment by cinema4d** [comment]
VRidge delet? since I had Oculus

**Comment by zelmon64** [comment]
The configuration tool won't do anything without the service running. Why did you install VRidge if you have an Oculus HMD? There's no need to delete it as it would just do nothing.

**Comment by cinema4d** [comment]
I put the bridge when there was Oculus

**Comment by cinema4d** [comment]
tell should start with ps3move, oculus home and steam VR?

**Comment by zelmon64** [comment]
@cinema4d I'm sorry but I don't quite understand what you mean (same with your previous comment). Could you please elaborate on what you are asking? PSMoveService does need to be running for SteamVR to be able to see the cameras and controllers but the order they are started in does not matter.

**Comment by cinema4d** [comment]
I am also very sorry that I can not describe all problemmu (Russia) using a translator but I'm not talking about the server and about PSMoveConfigTool, I just tuned it bad I think so

**Comment by cinema4d** [comment]
my progress, but I tuned deleted Steam drivers that they would not start

**Comment by fbepyon** [comment]
The steamvr config file is only going to show what is changed outside of the default config files located in the SteamVR apps folder under settings.  If you need to change the file to apply the "activateMultipleDrivers" : true there.

**Comment by HipsterSloth** [comment]
Closing old support issues. If this is still a problem please post a request to the google group:

https://groups.google.com/forum/#!forum/psmoveservice
