### ISSUE TITLE
Menu button on the PS move controller is not working in Job Simulator.

### ISSUE THREAD

**Issue by booty156** [cboulay/PSMoveService#170]
When I try to run Job Sim one of the first to do is you have to "Hit the Menu Button" Which is mapped to triangle button on my controller but it does nothing.

**Comment by HipsterSloth** [comment]
Unfortunately we don't have terribly great debugging for buttons at the moment. In the mean time there are two things you might investigate. 

The first is remapping the "application_menu" button to a different controller button in the off chance that that button isn't behaving correctly. See the [steam vr setup](https://github.com/cboulay/PSMoveService/wiki/Steam-VR-Setup) page for instructions on button remapping. 

If you have other games that use the application menu button I'd be curious to hear if the triangle button isn't working for those either. I'm curious if this is Job Sim specific or a general issue with the triangle button mapped to "application_menu".

**Comment by booty156** [comment]
I have swap 2 buttons around (Trigger is now application_menu and triangle is trigger) the changes work in steamVR but the controls are not changed in the game.

**Comment by andregm3** [comment]
since new update version i don't get PS home button working anymore for menu

**Comment by HipsterSloth** [comment]
Interesting. I have Job Sim. I'll try and repro the issue in the next day or two and see if I can determine what's going on with the button mapping. I'm trying to get a new release out for the DS4. If there is a fix for this I might roll it into that.

**Comment by booty156** [comment]
OK, thank you

**Comment by zelmon64** [comment]
@andregm3 At one point during my testing I also could not access the Steam menu using the PS button but then restarting PSMoveService and SteamVR fix it. Is this bug persistent for you if you restart?

**Comment by booty156** [comment]
I have restarted it and stills doesn't work :(

**Comment by booty156** [comment]
The only button that seems to work in job simulator is trigger...

**Comment by booty156** [comment]
Can someone send me there save file for Job Sim located here:
C:\Users\USERNAME\AppData\LocalLow\Owlchemy Labs\Job Simulator\
will be most appreciated thank you, Kai.

**Comment by HipsterSloth** [comment]
Closing old support issues. If this is still a problem, please post a request to the google group:

https://groups.google.com/forum/#!forum/psmoveservice
