### ISSUE TITLE
Crash on connecting PS Move Controller "PSMoveController::open - with EMPTY serial_number"

### ISSUE THREAD

**Issue by zephy7** [cboulay/PSMoveService#173]
Hey and thanks for all your awesome work on this :) 

I've had 2 Controllers tracked nicely for a while, but now whenever i connect one of them, i get "PSMoveController::open - with EMPTY serial_number" and it crashes the PSMoveService. The other controller works fine as before. 
I've tried unpairing and repairing them, resetting them and connecting them to my PS3 (which seems to work fine, they light up as usual), and deleting the controller settings from the PSMove folder. Nothing helped so far. 

Any idea what might be causing this or how i can hope to fix it? I'm using the Asus BT 400 and Win10, i've tested this with ver 4.5 and 4.6. 
I've recently upgraded to 2 PSEyes and tried to pair 3 Controllers, could that have anything to do with it?

**Comment by HipsterSloth** [comment]
The "PSMoveController::open - with EMPTY serial_number" is normal if a controller is connected via USB. A controller only has a "serial number" filled in when windows thinks it's connected over Bluetooth (the serial number is actually the MAC address of the controller). If you don't have any controller connected via USB then maybe Windows is in some funky HID state? When you open your bluetooth settings do you see 3 motion controller entries? Here is what mine looks like (I have 2 PSMoves and a DualShock4):

![image](https://cloud.githubusercontent.com/assets/16793853/17631437/efda902a-6078-11e6-9fa5-421f44ba5a59.png)

**Comment by zephy7** [comment]
Thanks a lot for your reply! There's nothing in my Bluetooth device list anymore since i unpaired it all, hoping it would help (it didn't). Before i did that, it showed all 3 of them in the list when it was already crashing.

The crash happens whenever i try to connect the controller with bluetooth OR usb, since it immediately crashes the service, there's no more chance of repairing it that way.
I'll try killing some of the HID entries in the device manager, both visible and hidden next then - ill let you know how it goes! Thanks again.

**Comment by HipsterSloth** [comment]
Would you mind running psmove service from the command line? I'd love to see all of the logs before the crash happens.

Also if killing the hid entries doesn't help, you could try using the old pairing utility in PSMove-Unity5:

Download this:
https://github.com/HipsterSloth/psmove-unity5/blob/master/Assets/Plugins/x86_64/psmove-pair-win.exe

And this:
https://github.com/HipsterSloth/psmove-unity5/blob/master/Assets/Plugins/x86_64/psmovepair.exe

Follow the setup instructions here:
https://github.com/HipsterSloth/psmove-unity5/wiki/PSMove-Setup-%28Windows%29

**Comment by zephy7** [comment]
Sorry for the super slow follow up, i've not had time/energy to mess with the PS Move controllers a lot recently thanks to overtime at work, but i've finally gotten them both to work again!

Unfortunately I couldn't really pinpoint why it stopped working in the first place or what the exact step to fix it was, but here's what i can say:

-I don't think kicking the device entries from the device manager made a difference by itself alone
-Pairing via PSMove-Unity5 didn't change the problem

What seems to have helped is the combination of all of these:
-Connected all the PS Moves to the PS3 again and resetted them a several times while still connected to the PS3 via usb(first step)
-THEN kicked everything suspicous from the bluetooth list and the device manager
-Then deleted the controller profiles from the PS Move Service folder
-Then used different USB Ports directly from the backside of the comp, no usb hubs inbetween and managed to pair them again, finally!

I hope this can help someone if they run into the same problem.

Also, here's the full log from one of the crashes from when they still happened: 

`
Launching psmoveservice:
[2016-08-13 10:01:32.361223]: main - Starting PSMoveService
Config file name: "C:\Users\default.DESKTOP-A8KJFLO\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
[2016-08-13 10:01:32.368189]: bluetooth_get_host_address - Found a bluetooth radio
[2016-08-13 10:01:32.370194]: bluetooth_get_host_address - Retrieved radio info
Config file name: "C:\Users\default.DESKTOP-A8KJFLO\AppData\Roaming\PSMoveService\TrackerManagerConfig.json"
[2016-08-13 10:01:32.388506]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\11\0, camera_index=0)
ps3eye::PS3EYECam::getDevices() found 2 devices.
Config file name: "C:\Users\default.DESKTOP-A8KJFLO\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b2_p3.3.3.4.json"
Config file name: "C:\Users\default.DESKTOP-A8KJFLO\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b2_p3.3.3.4.json"
Config file name: "C:\Users\default.DESKTOP-A8KJFLO\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b2_p3.3.3.4.json"
[2016-08-13 10:01:32.566401]: SharedMemory::initialize() - Allocating shared memory: tracker_view_0
[2016-08-13 10:01:32.572981]: DeviceTypeManager::update_connected_devices - Device device_id 0 (PSEYE) opened
[2016-08-13 10:01:32.576026]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\19\1, camera_index=1)
ps3eye::PS3EYECam::getDevices() found 2 devices.
Config file name: "C:\Users\default.DESKTOP-A8KJFLO\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b2_p3.3.4.json"
Config file name: "C:\Users\default.DESKTOP-A8KJFLO\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b2_p3.3.4.json"
Config file name: "C:\Users\default.DESKTOP-A8KJFLO\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b2_p3.3.4.json"
[2016-08-13 10:01:32.772995]: SharedMemory::initialize() - Allocating shared memory: tracker_view_1
[2016-08-13 10:01:32.779551]: DeviceTypeManager::update_connected_devices - Device device_id 1 (PSEYE) opened

connecting controller:
[2016-08-13 10:01:58.357928]: ClientConnection::start - Starting client connection id 0
[2016-08-13 10:01:58.360936]: ClientConnection::send_connection_info - Sending connection id to client 0
[2016-08-13 10:02:12.844365]: PSMoveController::open - Opening PSMoveController(\\?\hid#vid_054c&pid_03d5&col01#7&15cc102a&3&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})
[2016-08-13 10:02:12.850381]: PSMoveController::open -   with EMPTY serial_number
Config file name: "C:\Users\default.DESKTOP-A8KJFLO\AppData\Roaming\PSMoveService\e0_ae_5e_51_ef_52.json"
Config file name: "C:\Users\default.DESKTOP-A8KJFLO\AppData\Roaming\PSMoveService\e0_ae_5e_51_ef_52.json"
[2016-08-13 10:02:12.861468]: DeviceTypeManager::update_connected_devices - Device device_id 0 (PSMove) opened
[2016-08-13 10:02:12.864575]: PSMoveController::open - Opening PSMoveController(\\?\hid#vid_5543&pid_0047&mi_00&col01#7&1ea6b32c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})
[2016-08-13 10:02:12.870090]: PSMoveController::open -   with EMPTY serial_number
`

Thanks for the cool project :D Hope to see more!

**Comment by HipsterSloth** [comment]
Thanks for the report back. Glad to hear you got things working again. I added your troubleshooting steps to the [wiki](https://github.com/cboulay/PSMoveService/wiki/Troubleshooting-(Windows)#crash-on-connecting-ps-move-controller) with a link back to this issue. Hopefully that will help other who run into the same problem. I'm closing this issue for tracking purposes, but people can still find it off of the wiki and the closed issues page.
