### ISSUE TITLE
PS Move controller ID by serial code + enable/disable ideas

### ISSUE THREAD

**Issue by ozzeruk** [cboulay/PSMoveService#176]
I'm having reasonable success using 3 Move controllers in a SteamVR room setup with the third controller as my HMD positional tracker as I'm using Riftcat. When it works it works nicely.

One massive improvement would be if we could fix which controller ID each controller would be assigned based on the serial code of the Move controller. Currently it appears to be the order in which they are switched on, however, at times I have 2 already connected and I switch on the third, and it becomes controller ID 1 not 2 oddly. This all appears slightly random.

The reason for my idea is that I have Velcro pads attached to the controller that I stick to my HMD, and so I need this to always be the final controller (?) - PSMoveFreepieBridge appeared to need this at one point.

Additionally, I have the Leap Motion device which itself can act as 2 Vive controllers (using hands), this is also nice and I hope to use that combined with 1 Move controller and PSMoveService stuck to my HMD. For that to work my hunch is that I might need the controller on my head to be the 3rd controller in SteamVR. (?)

Finally - continuing on from this idea, it would be incredibly useful to be able to disable/enable controllers from appearing as SteamVR/Vive controllers. In my setup I would disable the third controller from appearing as a controller in SteamVR, and instead just have the data picked up by PSMoveFreepieBridge/FreePie/Riftcat and used for HMD positional data.

I am a C++ programmer and could probably do some of this myself, I hope to take a good look at the source code this month and see where I could help.

**Comment by HipsterSloth** [comment]
We could fix the controller order issue one of two ways:

1) Sort the controllers in the controller enumerator by serial number. The current controller enumerator just uses the [device order we get back from hidapi](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/Enumerator/ControllerDeviceEnumerator.cpp#L33). We could instead make the controller enumerator walk the entire controller list we get back from HIDAPI copying the entries into an array, then sort the array by serial number. This would make the controller order stable

2) Allow the SteamVR plugin to define what serial number is assigned to which controller slot. The steamvr plugin currently just [adds the controllers in the order the server returns them in](https://github.com/cboulay/PSMoveService/blob/master/src/openvr_plugin/driver_psmoveservice.cpp#L427-L450). The protocol currently sends the [serial number down to the client](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveprotocol/PSMoveProtocol.proto#L358), but we don't expose that in the [client api](
https://github.com/cboulay/PSMoveService/blob/master/src/psmoveclient/ClientRequestManager.cpp#L173-L219) that steamvr uses at the moment. Wouldn't be hard to add. Just a bit of plumbing. Once the client controller list has the serial number the steamvr.vrsettings file could take options for a given serial number like controller order or if the controller should be exposed. Similar to how we handle the [button mapping](https://github.com/cboulay/PSMoveService/blob/master/src/openvr_plugin/driver_psmoveservice.cpp#L1017-L1047).

I'm going to be swamped working on controller tracking improvements for the next month so any help I could get making usability improvements like this would be greatly appreciated.

**Comment by HipsterSloth** [comment]
I forgot we added hmd controller filtering a while ago and didn't resolve this issue:
https://github.com/cboulay/PSMoveService/wiki/Steam-VR-Setup#hmd-controller-3rd-controller-filtering
