### ISSUE TITLE
CLEye driver speedup?

### ISSUE THREAD

**Issue by ozzeruk** [cboulay/PSMoveService#177]
As has been noted, to get multiple cameras working with the CLEye drivers you need to buy one of their platform packs, which for 4 cameras costs $35.

Would using their drivers give any performance advantages?

I think they may allow upping the framerate from 60fps to 160fps+, which perhaps isn't even usable in PSMoveService?

Basically would it be a smart thing to purchase from a performance point of view? If it would help PSMoveService a lot then I would buy the platform pack, otherwise I won't bother.

I can update the Wiki with any advice that I get here. It would be useful to tell people whether investing in the CL Eye licences for multiple cameras has any performance advantages at all.

**Comment by zelmon64** [comment]
@ozzeruk from my experience libusb may have some issues but CL-Eye is worse. I believe the higher fps is only attainable with lower resolution so isn't worth it. Libusb can easily handle four cameras for free.

**Comment by ozzeruk** [comment]
Thanks - I'll pass on them then

**Comment by HipsterSloth** [comment]
Yeah the ps3eye camera can only support up to 70fps@640x480 with the bayer filter mode (1 byte per pixel). If you want higher frame rates you have to drop to 320x240 which limits the usable tracking range to about 3ft from the camera. The other problem with the CLEye drivers is that they only have a 32-bit driver (last I checked anyway) which means that if you want to use it with psmove service, you have to  use the 32-bit version of the service.

I'm closing the issue for tracking purposes, but please feel free to continue discussion if you have any other questions.
