### ISSUE TITLE
Pose calibration

### ISSUE THREAD

**Issue by renegade406** [cboulay/PSMoveService#178]
I have followed all steps and everything is tracking but when I do pose calibration with the mat the trackers don't sample.

**Comment by zelmon64** [comment]
@renegade406 That sounds like the colour calibration is not set correctly for magenta (check the masked view) or the controller isn't stable enough (place it upright on a the mat on a table or something if you cannot hold it still enough).

**Comment by renegade406** [comment]
I will try recalibration for magenta in the masked view that is probably why.

**Comment by renegade406** [comment]
Worked like a charm thank you.
