### ISSUE TITLE
PS Move Config Tool not detecting controllers via USB 

### ISSUE THREAD

**Issue by notsimply** [cboulay/PSMoveService#179]
I have recently purchased two PS Move controllers to use for VR. But the PSMove Config Tool is detecting any of my controllers when connected by USB. Please help me with my issue.

**Comment by HipsterSloth** [comment]
Some questions for you
* Are you using the MotionInJoy drivers? 
    + If so you'll need to uninstall those first. 
* What version of Windows are you running? 
    + There have been issues with HIDAPI (the library we use to communicate with the controller) and different versions of windows. 
    + Win10 is officially supported (the other versions of windows are not)
* Can you paste the output of the psmoveservice log window into this issue?

**Comment by cboulay** [comment]
@notsimply As you haven't replied to the questions asked that would enable us to help you with your problem, I'm closing the issue. Please comment here (with the replies to the above questions) if your problem is not solved.
