### ISSUE TITLE
can't  be identified with other HMD

### ISSUE THREAD

**Issue by vrxiaochouyu** [cboulay/PSMoveService#181]
can't  be identified with other HMD ，such as DeepoonVR and PimaxVR（some copycat manufactor）.
it can be identified alone. but after connect HMD it will be identified HMD only or  identified PSMOVE only.

**Comment by zelmon64** [comment]
@vrxiaochouyu Are you sure you have multiple drivers enabled in your vrserver,settings file? I can confirm PSMoveService works in combination with both VRidge and driver_null.

**Comment by Bungpiece** [comment]
I can confirm the service works with a deepoon E2.

**Comment by vrxiaochouyu** [comment]
@zelmon64 VRidge is OK. only use copyca HMD will be wrong

**Comment by vrxiaochouyu** [comment]
@Bungpiece Do you set someting?

**Comment by Bungpiece** [comment]
@vrxiaochouyu no I just followed the instructions from the setup guide. What are you using to render to your headset? When I had it working I was using oculus home with runtime 1.6 I want to say.
Before installing psmoveservice was everything working fine with steamvr? A copy of your steamvr.settings file may help.  Also to clarify is this steam only recognising one or the other or is it your PC?

**Comment by papalasarou** [comment]
@bungpiece have you been able to get this work correctly with the deepoon? If so how? I can get the controllers set up etc.. but they always appear behind and above me no matter how I calibrate (anyone else any suggestions )

**Comment by Bungpiece** [comment]
I can't find the video now but you want to basically  have your head be where the hmd is on the calibration mat ie have it at the same height and where you will be standing. Or you can adjust a settings file I think it's in appdata and manually set the values. There's a closed issue on this with more details I'll try to find when I'm on a desktop not a phone. Hope that helps.

**Comment by papalasarou** [comment]
@bungpiece thanks for the above will have a play about when in home tonight

**Comment by cboulay** [comment]
Moving the conversation [here](https://groups.google.com/forum/#!topic/psmoveservice/QJfIVuTnTkQ).
