### ISSUE TITLE
Adding Bluetooth dongle Harware ID (Feature request) 

### ISSUE THREAD

**Issue by ModiPlayz** [cboulay/PSMoveService#182]
Is it possible to add my bluetooth dongle directly using the hardware id from device manager. This would be very helpful for people using unsupported bluetooth dongles like me, Kinda like the way you had to do it in motioninjoy through mijxinput settings file. BTW im new to github so im sorry if i am posting in the wrong thread. Thanks :)

**Comment by HipsterSloth** [comment]
Don't worry this is this right place to post :). 

As for the bluetooth adapter, there is no white list for adapters in psmoveservice. Even though we recommend people use the Asus BT400, we don't explicitly filter out or add custom driver support for that BT adapter. We're just using the plain old windows bluetooth and HID APIs to communicate with the controllers. In theory, this means we should be able to support any bluetooth adapter windows supports. 

Do you still have motioninjoy installed? If so you'll need to uninstall it before psmove service will work. Motioninjoy takes over the bluetooth adapter exclusively.

**Comment by ModiPlayz** [comment]
Thanks for replying! I have actually uninstalled motioninjoy and reinstalled the bluetooh driver yet it still doesn't work. however using my laptops integrated bluetooth dongle worked fine. This also only started happening recently since this usb adapter was working with psmoveservice when i first found out about it. It might be my windows 10 install if so i might format it and do it again since i had to restore it. I will try uninstalling the adapters drivers and try it again. Thanks :) :+1:

**Comment by ModiPlayz** [comment]
So i tried many times and sadly it didnt work anymore so I might need a new bluetooth adapter to use the service on my pc. I might try other cheap bluetooth dongles to check if they work or not. Thanks though! 100:

**Comment by HipsterSloth** [comment]
Sorry to hear that didn't work out. I'm going to close this issue for tracking purposes, but feel free to add any additional comments.
