### ISSUE TITLE
[IDEA] PSMoveService for Oculus DK1 Position Tracking + VRControllers

### ISSUE THREAD

**Issue by RescueGamer** [cboulay/PSMoveService#184]
Hi all!

I really love the impressionant work all are doing here. I come with an idea, since dk1 is now not officially supported by oculus (but is still usable in steamvr), it would be possible to use PSMoveService to get positional tracking on DK1 with one ps move and use another two as SteamVR controllers?

I know the last part is already possible, but I didn't found any way to use PSMoveService to complete DK1 head tracking with position trackingin SteamVR. Since this is possible with a cardboard and RiftCat (I saw videos of people using cardboard+psmove for full head tracking and another 2 psmoves as controllers) I think there can be a way to achieve this.

This would be something great to revive dk1 units.

Thanks for your time!

**Comment by HipsterSloth** [comment]
I forget who, but there was someone on here who was actually doing this using FreePie and the PSMoveFreePIEBridge (https://bitbucket.org/hawkinse/psmovefreepiebridge). I can't speak to how well that works. After I got through DS4 and PS4 camera support I was hoping to more look into this sort of thing. I had been interested in trying this out for the GearVR. But I also have a DK1 collecting dust.

**Comment by RescueGamer** [comment]
Sound's great!, gear vr would be a major upgrade too. PS4 camera will be also a great improvement

Meanwhile I will be trying this with riftcat or my dk1 without positional tracking.

Thanks four your work!

**Comment by CircuitLord** [comment]
I haven't tried it myself, but for riftcat + vridge, you download the freepiebridge from the link @HipsterSloth provided, and also FreePie itself. Then, you run all 3 programs (PS Move Service, FreePieBridge, and Free Pie) and tell FreePie to output as FreeTrack. Then, mount a PS Move controller to your headset, and tell riftcat to use "Phone orientation and FreeTrack position" under Tracking Options. Then, you should be able to walk around in your area in steamvr games.

I'm pretty sure this is the right way to do, (someone correct me if I'm wrong). However, I'm not sure how to use controllers along with the headset positional tracking. I'm sure someone here could help you with that.

**Comment by Bungpiece** [comment]
I'm not sure you can use riftcat without a phone connected running the app. I might have been doing something wrong when I tried though. There is a osvr plugin for track it that may work for passing positional data to steam vr though. Haven't tried the combo out yet.

**Comment by CircuitLord** [comment]
Yeah, you need a phone with VRidge for Riftcat to work. Hmm, that plugin sounds interesting.

**Comment by Bungpiece** [comment]
Never tried it out but here's a link. I think it's for input and not outputting as track IR data but I'm not 100% so sorry if that's the case. https://github.com/samaust/TrackerV2-OSVR

**Comment by cboulay** [comment]
I'm going to close this issue because it doesn't appear to be an issue with PSMoveService. For general discussion, please move to the google group.
