### ISSUE TITLE
Failed to start PSMoveService: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted

### ISSUE THREAD

**Issue by YossiMH** [cboulay/PSMoveService#186]
When I try to run `PSMoveService.exe` from release 4.6, it immediately shuts down after I authorize it to run at the UAC prompt. No log file is generated.

When I try to do the same thing with release 4.5, it behaves similarly, but does leave a log file behind:

```
[2016-08-26 01:28:59.458789]: main - Starting PSMoveService
[2016-08-26 01:28:59.464793]: main - Failed to start PSMoveService: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted
```

I tried the registry change suggested [here](https://msdn.microsoft.com/en-us/library/aa560610%28v=bts.20%29.aspx), but it didn't appear to have any effect.

Thanks!

**Comment by YossiMH** [comment]
Update: I've got the [Unified Remote](https://www.unifiedremote.com/) Server installed on my computer. Shutting it down fixed the problem.

**Comment by HipsterSloth** [comment]
Sorry about the log file issue. We had to rip out the old logging library for cross platform build reasons and the new temp logger implementation doesn't log to file anymore. It's on my backlog of things to fix.

Even though you were able to work around this issue, i'm going to leave this issue open as a reminder to make the service port number configurable.

**Comment by HipsterSloth** [comment]
I forgot to close this issue after I made the port number configurable. You can now set the port number in '%appdata%/PSMoveService/NetworkManagerConfig.json'
