### ISSUE TITLE
Make a Controller Invisible

### ISSUE THREAD

**Issue by Figuration** [cboulay/PSMoveService#187]
Is it possible to make one of the controllers invisible? I'm using one of them for headtracking and whenever I'm in a game I can't see because the controller is in my face.

**Comment by CircuitLord** [comment]
I'm not sure how to make a controller invisible, but you could try mounting it like behind your head so that it doesn't block your FOV. Also, how did you make this do Positional tracking for the headset and controller tracking? I know how to do one or the other, but not both at the same time. Thanks!

**Comment by Figuration** [comment]
@CircuitLord Good idea, didn't think of that until today because my other two cameras just came in. As for separating the controllers, keep one vanilla in the PSMoveService, and then use the PsMoveFreepieBridge. I'll see if I can get you a link.

**Comment by Figuration** [comment]
@CircuitLord https://bitbucket.org/hawkinse/psmovefreepiebridge

**Comment by CircuitLord** [comment]
Ohhh okay, thanks. Yeah I saw that program but I wasn't sure how to seperate tracking controllers from actual controllers.

**Comment by Bungpiece** [comment]
There has been a similar request before that I'm struggling to find on my phone but I want to say the answer was that you can change a config file for steam vr that dictates what model a controller is rendered as.

**Comment by HipsterSloth** [comment]
I forgot we added support for controller filtering a while ago and didn't close this issue. See here: https://github.com/cboulay/PSMoveService/wiki/Steam-VR-Setup#hmd-controller-3rd-controller-filtering
