### ISSUE TITLE
Button mappings for touchpad swipes?

### ISSUE THREAD

**Issue by YossiMH** [cboulay/PSMoveService#188]
Apologies if this has already been covered elsewhere, but do any of the available SteamVR buttons listed on [this](https://github.com/cboulay/PSMoveService/wiki/Steam-VR-Setup) page correspond with touchpad swipes?

Thanks in advance!

**Comment by Imgonnawork** [comment]
Hi, maybe I misunderstood you but I think these are like pad swipes in every direction:

"dpad_left"
"dpad_up"
"dpad_right"
"dpad_down"

P.s. 
I don't know if there is a special recognition of swipes but as a concept the swipe in buttons should be reproduced with 2 keys subsequently

Ex.
Left-right
Up-down

**Comment by HipsterSloth** [comment]
That's a great question. When you map a psmove button to "dpad_left" for example, it's sending vr::k_EButton_DPad_Left to steamvr. I don't believe this button code (or any of the dpad button codes) is actually ever emitted by the Vive controller. I think they included it in OpenVR for controllers that did have a dpad. I think the swipe is handled differently, but I don't know this for certain. If anyone wanted to experiment with this button mapping and see if this accomplished the same result as a touch-pad swipe that would be rad. 

I would still like to do more complex button chording support, but that's waiting on me finishing up official support for the DualShock4, which is in turn waiting on me to finish up the Kalman filter with cboulay.

**Comment by YossiMH** [comment]
@HipsterSloth I believe that what applications tend to refer to in their in-game text as "swipes" are simply presses on the touchpad on certain extents. So I guess the most straightforward way to get this working would be to add "buttons" like:

* `touchpad_left_pressed` which, when triggered, would tell steamvr that the current value of the axis `vr::k_EButton_SteamVR_Touchpad.x` is -1 and that the button `vr::k_EButton_SteamVR_Touchpad` is being pressed
* `touchpad_left_touched` which, when triggered, would tell steamvr that the current value of the axis `vr::k_EButton_SteamVR_Touchpad.x` is -1 and that the button `vr::k_EButton_SteamVR_Touchpad` is being touched

**Comment by YossiMH** [comment]
I got something like this working locally. It's not close to ideal, since games seem to actually do want real swipes, as in your position on the touchpad changes over time, but it's a start, and it makes Tilt Brush usable. I'm going to try to submit a pull request at some point over the next few days.

**Comment by HipsterSloth** [comment]
Thanks for the pull request! I'm going to try and make a release tonight with this change since others might find this useful. I'll update the wiki too for info about the new mappings. Once that's done i'll mark this issue as resolved.

**Comment by HipsterSloth** [comment]
I just published a [release](https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha5.0) with these changes. I'm marking this issued as resolved. If anything comes up please feel free to start a discussion on the newly opened forum: https://groups.google.com/forum/#!forum/psmoveservice
