### ISSUE TITLE
SteamVR_initial setup issue

### ISSUE THREAD

**Issue by Goose70** [cboulay/PSMoveService#190]
I have everything configured, everything is tracking perfectly fine. The issue came up when I tried to run the .bat file called SteamVR_InitialSetupWin64. It says that powershell is not recognized as an internal or external command, operable program or batch file. I know this is probably an error on my system, but if anyone can help me, i'd greatly appreciate it. Thanks, Tyler

**Comment by HipsterSloth** [comment]
Ah. That's probably this script bit in the batch file that pops up the directory open dialog:

```
::Select the path to steam folder
set "psCommand="(new-object -COM 'Shell.Application')^
.BrowseForFolder(0,'Please select the root folder for steam (ex: c:\Program Files (x86)\steam).',0,0).self.path""
for /f "usebackq delims=" %%I in (`powershell %psCommand%`) do set "STEAM_ROOT_PATH=%%I"
IF NOT DEFINED STEAM_ROOT_PATH (goto failure)
```

I'm a bit surprised it can't find it since it should be installed by default on Win7 and up. At least that's what [wikipedia](https://en.wikipedia.org/wiki/PowerShell#PowerShell_2.0) says. 

So you have two options.
A) Install powershell. Instructions [here](https://msdn.microsoft.com/en-us/powershell/scripting/setup/installing-windows-powershell)
B) Manually do what the SteamVR_InitialSetup.bat file does 

If you decide to go for option B create a 'SteamVR_SetDriverVarsWin64.bat' file next to the other batch files and put the following in it:

```
@echo off 
set INSTALL_DIR=C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove
set STEAMVR_RUNTIME_DIR=C:\Program Files (x86)\Steam\steamapps\common\SteamVR
```

Make sure those paths actually exist on your machine. Most people have Steam installed at `C:\Program Files (x86)\Steam` but if that's not the case for you make sure to alter those paths as needed.

Once you have done either A or B then you can run `SteamVR_ReinstallDriverWin64.bat`, which should show something like this:

```
"(Re)Installing PSMoveService SteamVR Win64 driver..."
        1 file(s) copied.
        1 file(s) copied.
resources\rendermodels\dualshock4_controller\dualshock4_controller.mtl
resources\rendermodels\dualshock4_controller\dualshock4_controller.obj
resources\rendermodels\dualshock4_controller\dualshock4_controller.tga
resources\rendermodels\navi_controller\frame.png
resources\rendermodels\navi_controller\navi_controller.mtl
resources\rendermodels\ps3eye_tracker\body.png
resources\rendermodels\ps3eye_tracker\ps3eye_thumbnail.png
resources\rendermodels\ps3eye_tracker\ps3eye_tracker.json
resources\rendermodels\ps3eye_tracker\ps3eye_tracker.mtl
resources\rendermodels\ps3eye_tracker\ps3eye_tracker.obj
resources\rendermodels\psmove_controller\frame.png
resources\rendermodels\psmove_controller\psmove_controller.mtl
resources\rendermodels\psmove_controller\psmove_controller.obj
13 File(s) copied
"Done"
Press any key to continue . . .
```

**Comment by Goose70** [comment]
I opted for the lader of the two, but no avail. I created the new .bat file and once I place it in the PSmove Service folder, and click on it, I get a quick box that pops up and goes away immediately. then I try to run ReinstallDriverWin64 and a cmd box pops up with:

"(Re)Installing PSMoveService SteamVR Win64 driver..."
        1 file(s) copied.
        1 file(s) copied.
then it says xcopy is not recognized as an internal or external command.  then "Done"

**Comment by HipsterSloth** [comment]
I would be shocked if you didn't have xcopy.exe on your system. It should be in your `c:\windows\system32` folder. I found an article describing your problem [here](http://stackoverflow.com/questions/17273427/xcopy-is-not-recognized-as-an-internal-or-external-command-operable-program-or). It sounds like your environment path variable is too long. That or `c:\windows\system32` is missing from the path. You could always manually do the work that the `SteamVR_ReinstallDriverWin64.bat` batch file is doing, but I think the best thing is to get your path variable sorted out first. That will probably fix the powershell issue you were having too.

**Comment by Goose70** [comment]
I do not have xcopy.exe in my system32. I'll add it real quick and provide
an update. I appreciate the help thus far.

**Comment by Goose70** [comment]
I have gotten it to work! I had to set some parameters in my experimental
variables.

**Comment by HipsterSloth** [comment]
Excellent! Glad to hear you got that working. One day we'll write a proper windows installer like the leap motion steamvr plugin has and you won't have to deal with batch file shenanigans. I'm going to mark this issue as closed for tracking purposes, but feel free to keep commenting in here if you have other questions.

**Comment by Goose70** [comment]
Will do, the controllers did not show up in Steam, but I'm sure that's
something that I did wrong in the setup process.
