### ISSUE TITLE
PSMoveService won't detect Bluetooth dongle.

### ISSUE THREAD

**Issue by orangy57** [cboulay/PSMoveService#191]
I just got PSMoveService today, and for some reason when I try to connect my Playstation Move controllers, I get an error that says "No Bluetooth adapter found" or something like that. I just got this Bluetooth dongle and it supports 4.0 and Playstion 3 controllers. I don't have Motioninjoy drivers installed either. Is there a way I can get this program to detect my Bluetooth adapter without me having to go buy a new one?

**Comment by HexCuber** [comment]
did you install the bluetooth drivers for your dongle

**Comment by orangy57** [comment]
Yes I did, and I finally got it working by uninstalling my drivers and letting Windows do everything. Apparently BlueSoleil messed some stuff up.
