### ISSUE TITLE
Failed To Start Controller Stream

### ISSUE THREAD

**Issue by HexCuber** [cboulay/PSMoveService#192]
when i click color calibration, it tells me that it failed to start controller stream
I looked in the log/console and it said "requesting controller stream start for ControllerID: 0" but my controller id's for my ps moves are ID:1 and ID:2, there is no Controller id: 0 in my situation.
how to i change my ps moves controller id? I need to change it to ID: 0 

here is my log

ERROR [OpenVRContext::startup] Failed to initialize OpenVR: Hmd Not Found Presence Failed (126)!
INFO [App::init] Failed to initialize OpenVR!
INFO [Renderer::init()] Initializing Renderer Context
[INFO] ClientNetworkManager::start_tcp_connect - Connecting to: 127.0.0.1:9512...
[INFO] ClientPSMoveAPI - Successfully initialized ClientPSMoveAPI
[ERROR] ClientNetworkManager::handle_tcp_connect - TCP Connect error: No connection could be made because the target machine actively refused it
[ERROR] handle_server_connection_open_failed - Failed to connect to service: No connection could be made because the target machine actively refused it
[ERROR] handle_server_connection_open_failed - Failed to connect to service: A socket operation was attempted to an unreachable host
[INFO] ClientNetworkManager::start_tcp_connect - Connecting to: 127.0.0.1:9512...
[INFO] ClientPSMoveAPI - Successfully initialized ClientPSMoveAPI
[INFO] ClientNetworkManager::handle_tcp_connect - Connected to 127.0.0.1:9512
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 1
[INFO] ClientNetworkManager::handle_tcp_connection_info_notification - Got connection_id: 0
[INFO] ClientNetworkManager::send_udp_connection_id - Sending connection id to server over UDP: 0
[INFO] ClientNetworkManager::handle_udp_write_connection_id - Successfully sent UDP connection id
[INFO] ClientNetworkManager::handle_udp_read_connection_result - UDP Connect Success!
[INFO] handle_server_connection_opened - Connected to service
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 2
[INFO] start_controller_data_stream - requesting controller stream start for ControllerID: 2
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 3
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 3
[INFO] stop_controller_data_stream - requesting controller stream stop for ControllerID: 2
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 2
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 3
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 2
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 4
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 3
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 2
[INFO] start_controller_data_stream - requesting controller stream start for ControllerID: 2
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] stop_controller_data_stream - requesting controller stream stop for ControllerID: 2
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 2
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 6
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 5
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 3
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 2
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 3
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 2
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received notification type 3
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 2
[INFO] start_controller_data_stream - requesting controller stream start for ControllerID: 1
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] stop_controller_data_stream - requesting controller stream stop for ControllerID: 1
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 2
[INFO] get_tracker_list - requesting tracker list
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 7
[INFO] start_tracker_data_stream - requesting tracker stream start for TrackerID: 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] SharedMemory::initialize() - Opening shared memory: tracker_view_0[INFO] start_controller_data_stream - requesting controller stream start for ControllerID: 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 9
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] stop_tracker_data_stream - requesting tracker stream stop for TrackerID: 0
[INFO] get_tracker_list - requesting tracker list
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 7
[INFO] start_tracker_data_stream - requesting tracker stream start for TrackerID: 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] SharedMemory::initialize() - Opening shared memory: tracker_view_0[INFO] start_controller_data_stream - requesting controller stream start for ControllerID: 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 9
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] stop_tracker_data_stream - requesting tracker stream stop for TrackerID: 0
[INFO] get_tracker_list - requesting tracker list
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 7
[INFO] get_controller_list - requesting controller list
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 2
[INFO] start_controller_data_stream - requesting controller stream start for ControllerID: 1
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] get_tracker_list - requesting tracker list
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 7
[INFO] start_tracker_data_stream - ## requesting tracker stream start for TrackerID: 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] SharedMemory::initialize() - Opening shared memory: tracker_view_0[INFO] stop_controller_data_stream - requesting controller stream stop for ControllerID: 1
[INFO] stop_tracker_data_stream - requesting tracker stream stop for TrackerID: 0
[INFO] get_tracker_list - requesting tracker list
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 0
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 7
[INFO] ClientNetworkManager::handle_tcp_read_response_header - Received Message Header
[INFO] ClientNetworkManager::handle_tcp_read_response_body - Received Response Body
[INFO] ClientNetworkManager::handle_tcp_response_received - Received response type 2

**Comment by orangy57** [comment]
I'm getting this error too. :/

**Comment by zelmon64** [comment]
@HexCuber If a controller is turned off then back on while PSMoveService is running it will be set to a new ID (ie. ID 0 then 1 then 2 and so on). Try either restarting PSMoveService or restarting your Bluetooth device by either unplugging it or by disabling and re-enabling it in the Device Manager (to make sure no "phantom" PSMoves are connected).

**Comment by orangy57** [comment]
@zlemon64 I've been doing this same thing, but whenever I go to use PSMoveService and I disconnect my USB from my controller, I get a Paired controller In Bluetooth that I can't remove before the computer assigns IDs to the controllers, making this fake one always 0.

**Comment by HexCuber** [comment]
@zelmon64  but how do i change the actual controller id, is there a config file that contains the controller id, or is it in my actual controller or dongle, or is it in the registry somewhere...
can you tell me where it is...

**Comment by HexCuber** [comment]
@zelmon64 could there be something wrong with my ASUS BT-400 dongle?

**Comment by zelmon64** [comment]
@orangy57 try restarting your bt adapter so that no "phantom" PSMoves are connected, start PSMoveService then press the PS button to connect one PSMove via bt. Hopefully then you should see the following in the log:
```
DeviceTypeManager::update_connected_devices - Device device_id 0 (PSMove) opened
```
Actually thinking about it, in you log what do you see get registered as Device device_id 0?

@HexCuber I don't believe the IDs are stored anywhere. I think the're just assigned on connection to PSMoveService. If the controllers are turned on while PSMoveService is running the IDs are assigned incrementally as each is connected. On the other hand, if PSMoveService is started with all the controllers already connected I think the IDs are assigned in the order the computer stores them in (alphabetically with their mac addresses probably). I'm inferring this from the behaviour of connecting multiple controllers in these scenarios.

**Comment by HexCuber** [comment]
@zelmon64 so what should i do?

**Comment by HexCuber** [comment]
@zelmon64 I even Did a factory reset a few hours ago on my pc but i still have the same problem.

**Comment by zelmon64** [comment]
@HexCuber I'm not sure what log file you posted earlier but could you please run PSMoveService with your PSMove controllers connected via bt and copy that log and post it? (PSMoveService doesn't currently save the log which is why you have to manually copy and paste it)

**Comment by HexCuber** [comment]
thats kinda weird because no my controller id is 0... strange?

**Comment by HexCuber** [comment]
but thankyou so much for the support

**Comment by HexCuber** [comment]
@zelmon64 i will let you know if i have any more problems...

**Comment by HipsterSloth** [comment]
Sorry I should have chimed in sooner. As always, thanks for the support @zelmon64. 

Some background: There is no controller order PSMoveService defines anywhere. Basically the service just asks the OS (via HIDAPI) to give us a list of controllers that match the PSMove Controller HID/VID identifiers. HIDAPI gives back a list of bluetooth and USB connected controllers in some random order. PSMoveService assigns controllers an ID in the order it they appear in this returned controller list (0 for the first, 1 for the second, ...). There IS config data stored per controller in `%appdata%\PSMoveService\<controller_bluetooth_id>.json`, but nothing in there remembers the assigned controller ID. On a regular interval we repoll this controller list to see if controllers were added or removed. This means if a bad controller entry is stuck in there, this is an issue at the OS/Bluetooth Driver level.

I have sometimes seen windows hold on to previously opened controllers even though they have since been disconnected. Usually in most cases simply removing and reconnecting the bluetooth adapter fixes the issue. In the worst case there is a way to force rip out a controller entry out of the registry, but I prefer only to tell people about that as a last resort.

**Comment by orangy57** [comment]
I figured out a fix, but it might not help you. What was happening to me was that the controller would be detected as ID 0, or there was a dummy controller somewhere that my Bluetooth tack had recognized. It would probably help to let Windows 10 handle your Bluetooth connections and to make sure to uninstall your current Bluetooth driver if you have one. That seemed to work for me and my Bluetooth no longer says I have a controller connected when it isn't.

**Comment by HipsterSloth** [comment]
@orangy57 Ah that's a good point about using the windows default bluetooth driver. I should add a not to the troubleshooting wiki about that.

I'm going to mark this issue as resolved for tracking purposes, but if the issue comes up again please feel free to re-open it.

**Comment by HipsterSloth** [comment]
@HexCuber @zelmon64 @orangy57 FYI CircuitLord suggested we setup a forum for helping people with trouble shooting. After some discussion we settled on a Google Group for PSMoveService: 

https://groups.google.com/forum/#!forum/psmoveservice

When you guys get a chance you should head over there and request an invite. I would send invites, but I don't have your e-mail address.
