### ISSUE TITLE
I can't use the PS Move controllers and VRidge at the same time for some reason.

### ISSUE THREAD

**Issue by orangy57** [cboulay/PSMoveService#195]
Whenever  launch Steamvr with RiftCat open, it won't say that my controllers are connected, but when I close it I can use my controllers but I can't use my headset. I have multipledrivers set to true. What do I do?

**Comment by HipsterSloth** [comment]
Not sure if you figured this out or not. One thing that bit me last night was a malformed steamvr.vr settings file. I misplaced a comma when editing the file. I recommend pasting your steamvr.vr settings file at jsonlint.com to verify the formatting is correct. Steamvr wont give any notification in the UI if the config file is busted.
