### ISSUE TITLE
Weird calibration issues, 5.0 release.

### ISSUE THREAD

**Issue by Gliby** [cboulay/PSMoveService#196]
I am using 3 cameras with wall mounts, they are all aimed at a specific location downwards with varying distances, some are very close, others far.  Appears that my PSMove controllers come out flipped, and on other calibration attempts they are inaccurately tracked and extremely glitchy.  I have gotten a not-so-bad calibration once, one controller was tracking well, although offset from the world space, the other was flying around the place no matter what I did. A common occurrence of a bad calibration seems that the controller is always higher than the CV1 on the calibration mat.
Attempted fixes:
-  Using only 2 cameras, same position.
-  Re-positioning cameras off walls to stomach level. 
-  Using 2 cameras at my own height, aimed downwards to the calibration mat, and Oculus sensor in the between said cameras.
-  Re-calibrating controller tracking.
-  Re-calibrating magnetometer.

I'd also like to mention that I'm using the CV1.

EDIT: Here's my calibration result.
![example](https://cloud.githubusercontent.com/assets/2299543/18185590/0fb7f91c-70a7-11e6-9b8c-b510101cf8c1.png)
CV1 is sitting on the calibration mat, controller as well.

**Comment by emveee** [comment]
Make sure you aren't maxing out your usb host bus. I had this problem with my desktop and need to order a additional usb 3 pci-e card. Make sure your camera's are running at ~60fps using the test camera exe. Also keep in mind the cameras have a max distance if about 6ft before they lose tracking.

**Comment by Gliby** [comment]
@emveee Using the Inateck PCI-E card, stable 60fps, closest camera is about 6ft.

**Comment by emveee** [comment]
Does this issue occur on 4.6? Also just curious what are you using to wall mount? been looking for a way to do that..

**Comment by Gliby** [comment]
@emveee I am using camera mounts I bought from ebay, they came with short cylinders, that have a camera screw hole. Glued those to my PS3 eyes and attached them to the mount. 
![Camera](https://cloud.githubusercontent.com/assets/2299543/18182833/41b409cc-709a-11e6-9529-349f2213cea7.jpg)

**Comment by HipsterSloth** [comment]
Closing old support issues. If this is still a problem, please post a request in the google group:

https://groups.google.com/forum/#!forum/psmoveservice
