### ISSUE TITLE
Using more then 2 cams to extend controller scope (question)

### ISSUE THREAD

**Issue by gb2111** [cboulay/PSMoveService#202]
Hi,
First of all, thanks for your excellent work. 

Question as stated in title based from my experience when playing VR games. Currently controllers are best identified when in front of cameras and you cannot use them when turned around. In case we have 3 or 4 cameras around the controller area, we could have 360' degree of coverage since we always will have at least 2 cameras that see the controller. But in most cases there will be 3 that can additionally improve accuracy.

Please let me know what do you think of that.
GB

**Comment by cboulay** [comment]
Please follow the instructions in the ['Getting Help' section](https://github.com/cboulay/PSMoveService#getting-help) of the README.
