### ISSUE TITLE
How to manually adjust Floor Height (Steamvr Roomscale)?

### ISSUE THREAD

**Issue by emveee** [cboulay/PSMoveService#203]
After multiple attempts of re calibrating tracker pose, tracker colors and steamvr room setup (roomscale) my floor height in steamvr is about 2 chaperone boxes up from the actual floor. My controllers that are on the physical floor reflect this height and appear floating above the floor in steamvr. This makes playing games difficult ie picking up stuff off the floor. I am using 3 controllers with one being tracked with psmovefreepiebridge. I am using riftcat and used the calibration mat method. I have a 4 camera setup in each corner of the room pointing downwards.

I have tried editing the TrackerManagerConfig.json but the y axis only edits my HMD height and not my controllers. So if i get my hmd to the correct floor height all my controllers appear floating above me.

**Comment by cboulay** [comment]
From now on, I'm going to ask that any posts about psmovefreepiebridge or riftcat start off with posts in the google groups. I've been meaning to go back to the other very similar issues and close those with a similar note.

We need to keep the issue list clean so we can focus on issues that we can solve in code. It may very well be that the issue you are speaking can be solved with PSMoveService, but the problem needs to be isolated better before we can do anything about it.

https://groups.google.com/forum/#!forum/psmoveservice
