### ISSUE TITLE
Why SteamVR shows 3 controllers, if one is dedicated to HMD?

### ISSUE THREAD

**Issue by masterchop** [cboulay/PSMoveService#204]
I have see videos of other people and they have a similar setup with 3 controllers but on theirs only 2 show up in SteamVR, there are games where the HMD Controller is the active one, so i have to hold my head to perform actions, if i switch game it will go back to normal and always the same games?

I wonder if this is due to the 3rd controller showing, is that normal?

**Comment by cboulay** [comment]
Please follow the instructions in the ['Getting Help' section](https://github.com/cboulay/PSMoveService#getting-help) of the README.
