### ISSUE TITLE
3 Controllers in SteamVR and some games but there are other like PaintLab and Waltz of Wizard that dont, this is not issue #136

### ISSUE THREAD

**Issue by masterchop** [cboulay/PSMoveService#208]
Hello,
  I have been using the code very succesfully, i have 3 controllers PSMOVE and  2 cameras with the latest version of PSmove Service, i am using FreePIE to do the head tracking with the controller which works just fine but only for some games there are other that take the head controller and 1 of the hand controllers and other other disapears, if press start to go back to steamVR your controller comes back and its available.

If I configure the head tracking with Opentrack and Kinect, and use only 2 controllers all games work just fine. Is there any known issues with FreePIE? I tried with FreePieBridge alpha 4.5 and 5 with same results.

thank you

**Comment by gladiusz** [comment]
I was going to write this at the same time. It would be awesome, if there was an option to hide on of the controller. For example controller which is used by PSMoveFreepieBridge, isn't seen by SteamVR.  It will be a really good option, beacuse many games, like for example Budget Cuts demo use 2 of 3 connected controllers randomly.

**Comment by masterchop** [comment]
Kinect and Opentrack solved the problem but the problem with kinect is that you use your real head and you cant place it in the calibration mat XD so it always in a wrong position. 

If try to develope with SteamVR SDK using this solution, you will notice that the same thing happen when you launch your game to test, even if you remap the controllers. Not sure if it matters or not but in the SDK you can choose which one will be game pad and which one will be HMD, when you hit play that is ignore and you need to remap during game play.

**Comment by cboulay** [comment]
Hello. Please post in the google group first before posting in GitHub, especially for issues related to the SteamVR driver and 3rd party programs.
https://groups.google.com/forum/#!forum/psmoveservice
