### ISSUE TITLE
Calibration method not working.

### ISSUE THREAD

**Issue by HyppoNymous** [cboulay/PSMoveService#209]
I tried the second calibration method moving the headset and keeping a PSmove attached on it's side, but it doesn't work well. After the calibration the PSmove is way farther from the headset and unusable.
What about making a new calibration method keeping the PSmove at side of the headset , but asking only three or four space position calibration ? Instead of doing movements that finally gets bad tracking ? 

Or why not using an easy Steam VR calibration method ? 
You keep the helmet on head and keep controller in front of you and just clikc a button , than put down them on floor side by side and click a button again ?

**Comment by HipsterSloth** [comment]
> Or why not using an easy Steam VR calibration method ? 
You keep the helmet on head and keep controller in front of you and just click a button , than put down them on floor side by side and click a button again ?

Your question has great timing! I'm working with @YossiMH on basically this feature. You can read about the progress here: https://groups.google.com/forum/#!topic/psmoveservice/xOTO4fRgAc8. My long term goal is to remove the HMD alignment from the PSMoveConfig tool entirely. Only the camera pose estimation will be done there. The HMD alignment will be done as you described.

**Comment by HyppoNymous** [comment]
hahhahaa yeah good timing we have.

In fact i hoped for a different calibration like +X+Z  and -X-Z  only.
Because -X +Z and +X-Z can be calculated from both above and center can also be calculated from the first both.
Perhaps adding a third position calibration like Helmet and PSmove vertically on top of it to adjust relative position between PSmove and Helmet.
So two position calibration plus a third HMD + PSmove position should cover all needs and be more simple to do.

Why do we use a calibration material ? We should be able to calibrate without it, capturing -X-Z would define the farther position behind the helmet on the right we could get for the game , and +X+Z would define the farther position we could reach on the left and in front of the helmet when playing the game.
I think this makes lot more sense to capture maximum bounds play area somewhat like SteamVR roomscale zone setup.
