### ISSUE TITLE
Third PS Move for Tracking Helmet option.

### ISSUE THREAD

**Issue by HyppoNymous** [cboulay/PSMoveService#210]
Could a Third PSMove be an option to define it as helmet tracking and work with SteamVR ? 

Actually i use HDK 1.4 , and the helmet tracking is very angle and range limited compared to PSmove tracking.  If we had some option to add and define a third PSmove for head tracking this would be perfect and would work lot better.

**Comment by cboulay** [comment]
This is already much discussed. Please start by reading and posting in the google group.
https://groups.google.com/forum/#!forum/psmoveservice

We'll graduate topics from there to GitHub issues once we have sufficient information to formulate the problem.
