### ISSUE TITLE
opentrackkinect and PSMoveService

### ISSUE THREAD

**Issue by airsoftmart** [cboulay/PSMoveService#211]
Hi 

I have the opentrackkinect tracking the user and I have vridge tracking the HMD 
 I then have PSMoveService tracking move contollers using four PS3 eyes 

When I try and use the opentrackkinect the PSMoveService comes to a stop and the controllers are n longer tracked 

Anyone else getting this issue 

Mark

**Comment by zelmon64** [comment]
It's just the Kineton eating up ask the bandwidth.

**Comment by airsoftmart** [comment]
I have removed one of the PS MOVE EYE cameras seems to be working ok now 
Next problem I have now is orientation of the three PS MOVE EYE cameras and the steam vr environment 
It seems to be twisted about 20 degrees

Mark

**Comment by zelmon64** [comment]
@airsoftmart an orientation misalignment means your HMD wasn't facing forward when you ran the calibration. After repeating calibration restart both SteamVR and PSMoveService to apply the change.

**Comment by airsoftmart** [comment]
My HMD is a Samsung S3 sing vridge so I have to have it active to calibrate it 

Makes sense will give it a try 

Mark

**Comment by airsoftmart** [comment]
Which calibration do you mean 

PSMoveService / Steam VR

**Comment by zelmon64** [comment]
@airsoftmart PSMS calibration. Make sure your HMD  (VRidge) is looking forwards when you perform the calibration poses. It records the data after the fifth PSMove motion controller pose.

**Comment by masterchop** [comment]
Have you test this with latest version? 5.2

**Comment by HipsterSloth** [comment]
Closing old support tickets. If this is still an issue please post a request to the google group:

https://groups.google.com/forum/#!forum/psmoveservice
