### ISSUE TITLE
Third PSMove to head tracking Response

### ISSUE THREAD

**Issue by HyppoNymous** [cboulay/PSMoveService#212]
I re post it here caus i think no one understood the idea.

PSMove Service should be able to calibrate a third controller used to track head position, overriding OSVR positionnal and orientation tracking.
PSMove service would send third PSMove data to SteamVR about head tracking.
I mean the third PSMove is tracked by PSMove Service and not using FreePie or another program (the less programs we use the better).

There is nothing about that idea on Google Groups.

**Comment by Bungpiece** [comment]
This has been discussed in many opened issues and the current answer is that this sort of feature is currently beyond the scope of the psmoveservice project. I doubt opening 3 issues on the topic will change this. If you look in the riftcat reddit they are thinking about adding support for non phone hmd's. I'd like this feature too but this isn't the way to get it. You could always look up some c++ tutorials and start playing withe the openvr API or making an osvr plugin.

**Comment by masterchop** [comment]
I am sorry, kinda deperate but it was not intencional. 
I am not a developer but i have some knowledge, and beliebe me i really want to go for C++ but i am still trying to be a rookie in C# and Java, but it seems C++ can give you access to better stuff.

**Comment by Bungpiece** [comment]
You've got a head start on me then I've just started looking at it as my first programming language after seeing psmoveservice and some other open source projects that have steam vr drivers. The point I guess I was trying to make is this section is meant to be reserved for issues such as bugs not feature requests. And posting duplicate requests for unplanned features is detrimental to the project as the folks developing it have to sift through threads like this that they have asked be discussed elsewhere to find issues they can actually address and find solutions to.

**Comment by HyppoNymous** [comment]
@Bungpiece 
So there won't be such feature with PSMove service, and people are bind to their HMD tracking capability. Hopefully i'll got a complete system like Vive or Psvr headset as the experience is far better from Osvr or Mobile sort of experimentations.

Thanks for saying what it is, i like clear answers.

**Comment by cboulay** [comment]
>There is nothing about that idea on Google Groups.

Well then that's why you should post there first instead of posting here. Google Group first, then here. The only exception is if it's a bug report with screenshots, logs, etc, then you can post here first.

I understand that part of your post is a slightly new suggestion, but that doesn't go here, not yet anyway.
