### ISSUE TITLE
Onward

### ISSUE THREAD

**Issue by TheProliver** [cboulay/PSMoveService#214]
There is a game called onward made for the vive.
I would really love to play this game but am questioning if this is possible.
People are talking about using the left controller thumbstick (touchpad) to walk and the right controller thumbstick to do certain actions.
My question is if this is also possible with the psmove controllers since i saw that you can program the buttons like triangle to thumbstick up for example. But i dont know if you can do it for both the left and the roght side.
If someone would awnser this question i would greatly appriciate it.

Here is what i found about the controls: For reload, you need to unlock the magazine, put out, take from your body a new magazine, insert in the weapon and charge the bullet. Left thumbstick is used for movement, and axis are related to the left hand (so you can walk, watch and aim in three different orientation). Right thumbstick is used just for some actions, like single/multiple shot on the rifle, or unlock the magazine. Menu buttons are used left for exit the match, right for take the tablet.

**Comment by cboulay** [comment]
Please read the README.
