### ISSUE TITLE
Changing controller colors

### ISSUE THREAD

**Issue by MaVe-64** [cboulay/PSMoveService#221]
Is it possible to have an option to change the color. Yellow doesn't work very wel in my room.

Thanks for this fantastic program!

**Comment by HipsterSloth** [comment]
Certainly. The order of controller colors is totally arbitrary. It would be straight forward to add a color override in the controller settings panel.

**Comment by HipsterSloth** [comment]
I just checked in a fix for this into the master branch. You can now select which tracking color is used for a controller in the controller settings dialog in the PSMoveConfigTool. This will be available to use in the next release of PSMoveService (which I'll try and build this Friday).

**Comment by MaVe-64** [comment]
Thanks! You rock!

**Comment by HipsterSloth** [comment]
This feature is now is the latest release (https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha5.3).
