### ISSUE TITLE
Tracking colored bulb, with no actual psmove controller?

### ISSUE THREAD

**Issue by Tux0Topo** [cboulay/PSMoveService#222]
Hi!!
I wish a way to track one bulb attached to the HMD, just for position, and the rest of the movements tracked by the cellphone (using vridge). Is there any chance?

**Comment by ozzeruk** [comment]
Presumably you still mean with a PSMove controller rather than just a light bulb, as getting a $8 second hand PSMove controller is a lot less hassle than messing around with LEDs.

Presuming that's the case (make sense). Use psmovefreepiebridge / freepie, and set your tracking option in Riftcat/Vridge to 'freetrack position + phone orientation'.

The trickiest part is attaching your 'spare' PSMove controller to the HMD, I'd recommend velcrow.

(if you want to track an LED instead, then software such as FreeTrack can do that - but you'd not be using PSMoveService at all)

**Comment by Tux0Topo** [comment]
The PSMoveService allow to use multiple cams. Freetrack/Opentrack, cant.
Sadly for me, we live in different countries. The second hand controller here, cost about 5-8% of the common salary. So, messing around with leds (second hand), is a cheaper option. And the psmovefreepiebridge use psmove controller for position, and the rest of rotations from the cellphone.... meaning the led bulb is the only part really used. So, using just a simple bulb should be capable of doing the trick, cheaper and lighter...
And i know how to play with leds ;) .

**Comment by zelmon64** [comment]
@Tux0Topo [This DIY controller](http://douevenknow.us/post/149626333983/making-controllers-for-vr-from-the-ground-up) might interest you. For what you want PSMoveService would have to be tricked into thinking there are PSMove controllers connected. This would certainly be achievable but I don't know how difficult.

**Comment by cboulay** [comment]
We wouldn't want to "trick" PSMoveService. Instead we'd add support for another controller type, just like we have separate support for DS4, Navi, etc. I don't have time to look at the code right now, but adding new controller types was considered when designing PSMoveService.

**Comment by HipsterSloth** [comment]
Yeah it wouldn't be too hard to add another tracked "controller" type that was just a light. It would need to be a spherical bulb though. We don't support point light style tracking like [freetrack](http://www.free-track.net/english/). Basically I imagine we'd add a menu option to the controller settings page that let's you add an entry for a tracked spherical light. This would register the "controller" with the controller manager. Then you could edit the color filter the same way you do for the other controllers. The steamvr plugin wouldn't need to be updated, but the FreePIE bridge would to support the new controller type.

All that said, I won't have time to work on this until November at the earliest. If someone wanted to add this support I would be happy to provide guidance.

Funny aside: Attaching the PSMove controller bulbs to an HMD is exactly what the Sony Magic Lab team did when they are prototyping PSVR:

![sony_vr_prototype 0](https://cloud.githubusercontent.com/assets/16793853/19018208/ad1add0a-880d-11e6-868f-8ba81b434772.png)

http://www.polygon.com/2016/3/9/11174194/the-making-of-playstation-vr

**Comment by Tux0Topo** [comment]
I love what you are talking about. Simple positional tracking, made of a simple led bulb... 💃 
Kind of silly question.... The ps4 controller light, can be used to also provide some orientation? I'm asking because the drifting with cellphones and psmove controller is a annoying.... and if the simple bulb idea can be made, using a led triangle, can also be made... helping/correcting any drift with orientation tracking....

**Comment by cboulay** [comment]
If you are going to make something custom and make custom tracking code then you're better off using 4 point leds in an asymmetrical configuration. You are also better off using IR. you have to decide where the trade off is between making the best solution and reusing existing code.

**Comment by MaVe-64** [comment]
It does make sense though, using just a light instead of sticking a PSMove to your head, as only the light is used, am I right?

**Comment by Tux0Topo** [comment]
@MaVe-64 That's what i'm talking about. And from all projects for tracking, psmoveService seems to be the only one using multiple cameras... meaning better tracking / 360 tracking...

@cboulay My coding skills are useless... so, if a great software (yours) + simple idea / modding, can work decently, i'm in...

**Comment by HipsterSloth** [comment]
> The ps4 controller light, can be used to also provide some orientation? I'm asking because the drifting with cellphones and psmove controller is a annoying.... and if the simple bulb idea can be made, using a led triangle, can also be made... helping/correcting any drift with orientation tracking....

It's true that the DualShock4 controller does have a triangular shape that you can compute an orientation with, but there is a pretty narrow range of angles it works in. I made two detailed videos detailing all the complexities get getting the DS4 controller working so far (most of the tracking stuff is in video two):

Part1 - (8min) https://youtu.be/ywxjFAQuxkQ
Part2 - (13min) https://youtu.be/MPbegaB7cf0

If you want yaw drift correction I think it might just be easier use the orientation or magnetometer info from a psmove controller attached to the HMD.

**Comment by Tux0Topo** [comment]
The psmove controller don't have any drift problems?

**Comment by cboulay** [comment]
Yes, there is yaw drift. It's pretty slow though, and you can fix yaw drift with a 'recenter' button. I guess you'd have to 'recenter' about once every 3-5 minutes by looking 'forward' (in the world, not in the game) and pressing a button. Pitch and roll aren't susceptible to drift.

So you definitely want position, but you also want orientation, and you don't think the PSMove is good enough for this, and you can't write code. Well, the LED triangle orientation measurement by itself is not good enough either; it'll definitely be worse than dealing with the PSMove + its yaw drift. (For clarity: The DS4 also has an IMU so its orientation measurement is pretty good) There are definitely other LED arrangements that would be better for 6-DOF tracking with multiple cameras, but any of them would require custom code that doesn't already exist in PSMoveService.

**Comment by nalf3in** [comment]
Well how about using a existing orientation solution (such as the Ed tracker) and just add a light bulb to it that could (in the future ) be tracked by Psmoveservice ?

**Comment by HipsterSloth** [comment]
@nalf3in - It looks like EdTracker is just Gyro + Accelerometer. If you added a light bulb to that you'd basically just have a PSMove minus a magnetometer. There might be other head tracker solutions but at the end of the day it's at best going to be an accelerometer, a gyro, a magnetometer and a light of some kind, which is exactly what the PSMove controller is already.

@Tux0Topo Can you link me the videos of drift. I'm curious about the rate of drift. Having a magnetometer allows you to correct for drift because you have an absolute reference for magnetic north. Any drift people are getting in PSMoveService is likely due to the current orientation filter not having the right blending setting (which is currently hardcoded).

**Comment by cboulay** [comment]
@HipsterSloth , for the record, I still get yaw drift. It's pretty slow, and it tends to slow down even further after a few minutes.

I can't directly observe the drift as it's too slow. However, if I calibrate right now, then move the controller around vigorously (but no more vigorous than in an action game), and then point to my yaw=0 point again, the in-game controller will be pointing about 10 degrees to the right or left.

If I calibrate the controller then leave it on the desk, it'll very slowly rotate over the course of ~ 5 minutes until it's about 10-15 degrees off. Then it sort of stops rotating on it own, or it rotates very slowly on timescales of hours.

Maybe the magnetic field in my room isn't consistent, or maybe it's not sufficiently large in magnitude in the horizontal plane to overcome noise, or maybe I need to rely on the magnetometer more and less on the other sensors.

**Comment by Tux0Topo** [comment]
Kind of silly, but related question... Is there any way to help to reinforce the magnetic field to use these controllers? I don't know... maybe putting in a corner a few HDD magnets?? Maybe that way we can reduce drift as cboulay commented. And in a few tutorials and comments in forums i read similar experiences, so seems to be a common/real problem....

**Comment by cboulay** [comment]
@Tux0Topo If you had a radiating magnetic field then it would die off with 1/d^2. If you had a static field, as you suggest, it would die off with 1/r^3. In other words, the magnets would have to be really close to the magnetometer before they could overpower the earth's magnetic field. I think it would be impossible to create a homogenous magnetic field over any useful volume without some major power-sucking hardware.

In (bio)chemistry, they use these [magnetic stirring devices](https://www.amazon.com/Hanna-Instruments-Magnetic-Mini-Stirrer-Speedsafe/dp/B002OSX2Q0/ref=lp_318023011_1_9?s=industrial&ie=UTF8&qid=1475688731&sr=1-9). Basically the base just rotates a magnetic field, causing a dipole magnet in the solution to spin around really rapidly. In my experience, if you take the container off the stirrer by about 5-8 cm, the dipole magnet stops being affected by the stirrer.

**Comment by Tux0Topo** [comment]
Yeah... i guessed it was a terrible idea....
So, the best option, is some optical tracking with the help of an accelerometer, a gyro, and magnetometer.
Another kind-of idea... adding some other lights to the psmove controller? In the same kind of freetrack... but with added accelerometer, gyro and magnetometer, and multiple cameras support...

**Comment by gb2111** [comment]
hi Tux0Topo,
if you find a controller partially broken and very cheap then you just turn it on and calibrate against your source of light. but it should be a ball like for ps3. its not easy to find a ball or something similar that you can put on your source of light and will have homogeneous light. actually any of 2 balls that I tried did not worked well but its definitively possible.
i tried this when in the beginning the controller on the side was too heavy but now I attach it centrally and my problem is gone...
greg

**Comment by Tux0Topo** [comment]
Yeah... the problem to buying a broken psmove controller, is finding it (and that the owner sell it cheap :S).
In any case, that is tricking the PSMoveService to think that the extra bulb is the real bulb....
Better solution, should be the one described by @HipsterSloth, adding an alternative controller device, just the bulb.

**Comment by rebitti** [comment]
@Tux0Topo, look that, no light is need.  Just a reflective material.

https://www.youtube.com/watch?v=sdc2SLkQ808

**Comment by HipsterSloth** [comment]
Yeah that's another option, using a retro reflective material. You need to modify the ps3eye camera to remove the IR filter in front of the lens though.

**Comment by rebitti** [comment]
Defenelly this feature to track only a light or reflective material will be awesome and make psmove-service more popular, as Tux0Topo said, is the only multiple cam to work with assessible hardware ( pseye ) and in realtime ! We need this ! :D

**Comment by HipsterSloth** [comment]
What that sounds like a neat addition, I'm not going to have time to work on something like that for the next few months. I have a few other higher priority tasks that need to be done before adding support for yet another tracking option. If another dev wanted to step up and help with this I would be happy to give advice and support on how to implement it.

**Comment by Tux0Topo** [comment]
@rebitti The reflective sphere idea, don't buy me. It's only one color, and also you need some leds to point at it....

@HipsterSloth The entire crew are doing some awesome work. With just having the intention to look at the idea, is awesome. Thanks!!

**Comment by robsonswiss** [comment]
Hi

Why would it not be possible to track a diffused point rather than the PS bulb? Is it possible to add tracking for a diffused point?

**Comment by HipsterSloth** [comment]
It absolutely would be possible to track a diffuse point, it's just not implemented. The optical position calculation code currently only knows how to track ellipses (psmove controller bulbs) and triangles (ds4 light bar). It's just a (non-trivial) matter of implementing a new tracking algorithm. When this question first came up I wasn't interested in making a new tracking algorithms for point lights. However, with the PSVR headset that just came out, and the lightning speed with which people have decoded it's [USB protocol](https://github.com/nathanleroux/PSVR_api/blob/master/Morpheus/morpheus.h), I decided to start taking a stab at that. I'm currently working on exposing the Morpheus headset as a new tracked device in PSMoveService. If I can get that working, it should be a straight forward process to extending that to other point light based arrangements. No promises though. I have a general idea how I'm going to make this work with triangulation but my plan for determining point correspondence is still half-baked.

**Comment by robsonswiss** [comment]
Hi

Yes it would be for a single point source, with multiple camera's. 
I don't have enough coding knowledge to add anything to the project, however I am willing to contribute financially(donate/bribe lol) if that would help. :)

**Comment by HipsterSloth** [comment]
No need for bribes. I'm working on the Morpheus headset regardless. And even if I fail at getting that headset working, a single point light tracked "faux-hmd" could fall out of that work very easily. Just be aware that it wouldn't have any orientation, just position.

**Comment by robsonswiss** [comment]
I think that would be perfect and exactly what a few of us need.

**Comment by Tux0Topo** [comment]
Reading the last post, gave a 2 questions:
- The Morpheus headset have multiple light sources. Can they used to also track orientation? ir-track style...
- The tracking of the Morpheus headset, will be compatible with ps3 eye cams? or need different camera?

**Comment by HipsterSloth** [comment]
> The Morpheus headset have multiple light sources. Can they used to also track orientation? ir-track style...

Yes, if you have 3 or more points you can compute an orientation. The tricky part is figuring out which tracked blob in the the video frame is associated with a given LED on the headset. My current thinking is:

1. Use Epipolar Geometry to determine which blobs in one camera frame correspond to blobs in another camera frame (See https://en.wikipedia.org/wiki/Epipolar_geometry)
2. Triangulate points that have corresponding blobs between pairs of camera
3. Determine the HMD pose that best aligns the LED locations on a PSVR mesh with the triangulated points
 * Probably use an interative solver to align the pose
 * Use the IMU orientation to provide an initial guess

> The tracking of the Morpheus headset, will be compatible with ps3 eye cams? or need different camera

I want to give it a try with the PS3 eye cameras first, but I suspect the tracking range won't be great. The other issue is that you need pairs of cameras closer together so that you can triangulate (two cameras need to see the same LED to do triangulation).

**Comment by robsonswiss** [comment]
For headset tracking why would you want full orientation? The MPU can provide orientation, you only need to track Yaw orientation for drift correction, only 2 LED's are required to do this.

**Comment by Tux0Topo** [comment]
I think that you are correct. But i'm not sure if OpenCV allow to get that info. And i think that 3 points are not that much hard to do, and get you more info....
Anyways, you still need to track some device, with just a bulb... which is where this thread started...

**Comment by robsonswiss** [comment]
I don't know how much processing power goes towards calculating and matching the 3 point "pyramid" in OpenCV, I suppose you can improve on it further by making the 3 LED's different colours, I was just thinking along the lines of what is the least complex method of getting to the end result (full 6dof tracking without drift).

**Comment by gb2111** [comment]
Dear! 

I've got some news for you, you are  going to be pleasantly  surprised, read it here please <http://two.jccassis.com/jdh/6>

knurgb

**Comment by gb2111** [comment]
Hey, 

I've come  across that wonderful stuff recently and  it seems  to be something really new, please check  it out <http://thing.gagoesgreen.com/ry/10>

Very truly yours, knurgb

**Comment by Tux0Topo** [comment]
Is that spam?? How can report it?

**Comment by cboulay** [comment]
Yeah it's spam. If you were following UnrealEngine a few months ago you would have seen that they got spammed bad.

Anyway, GitHub was pretty good about fixing that problem and it looks like this problem has been fixed already. Let's hope.

**Comment by Tux0Topo** [comment]
Thanks!!

Anyways.... i have a question... how many different bulbs could be tracked by PSMoveService at the same time? I know that the bluetooth bus can connect to 6 or 7 controllers... but i'm still interested just in the bulbs....

**Comment by TheSmg** [comment]
Now that PS move controllers are back up to $30 each, has this goal been more of a priority for the project? (especially the single point tracking)
I can fully appreciate the work that is being done and released however I feel that this would be a great feature to add in the near future.

**Comment by ThomasMcVay** [comment]
I'm also curious about the status of this, I see on the readme that Virtual controllers is listed as a near term goal. I've also seen the [PSVR Positional Tracking setup](https://github.com/cboulay/PSMoveService/wiki/PSVR-Positional-Tracking-setup) guide which I tested successfully with my friend's headset. But it's a really kludgy solution, and I've been holding off on getting a psvr headset for development work until positional tracking is available.

It seems as if all of the other necessary functions for headset tracking have already been implemented in  MorpheusHMD.cpp, but aside from all these indications, I haven't seen very much actual talk on the subject.

**Comment by HipsterSloth** [comment]
I'm sorry this issue hasn't seen much progress in the last few months. I did a bunch of work in Jan but only got part way into implementing psvr positional tracking (still needs a bunch of research). I shelved that work in favor of helping finish a bunch of other outstanding work we had with psmove service (lens distortion calibration, ROI filtering, ps navi support, switching to c-api). The other monkey wrench is that more of my free time is going to be eaten up teaching prep over the next 6 months. My current plan is to wrap up the loose ends of the c-api conversation over the next week, upgrade to openvr 1.0.6, pull the psmoveserice/openvr plugin code out into it's own github repository, and write a bunch of documentation. 

In the meantime I think a few others have expressed interested in helping out with the virtual  hmd support. Now that the c-api work is mostly done I feel better about people making additions to the client interface.

**Comment by Paradise-My-Colors** [comment]
@HipsterSloth I see there is no development been madeon this driver yet, Right ?
I am really running out of options to get positional tracking on my HMD (deepoon e2) and this driver seems to be my only savior.
any update on the topic or ETA would be greatly appreciated.
thank you for your time and effort.

**Comment by HipsterSloth** [comment]
There's actually been lots of work done on this recently. I have this feature integrated into PSMoveService, but haven't released an official build yet. I'm still testing the code changes in PSMoveFreePIEBridge that take advantages of the PSMoveService changes. See thread here: https://github.com/HipsterSloth/PSMoveSteamVRBridge/issues/2

**Comment by maxternal** [comment]
Would it be possible to extend this further to add positional tracking to some device that already has rotational tracking (like a cell phone or a motion+ wiimote) by adding a bulb to it to use it as a VR hand controller?

**Comment by HipsterSloth** [comment]
Both VirtualControllers (attaching a bulb to a controller) and VirtualHMDs (attaching a bulb to an HMD) are available in the latest versions of PSMoveService/PSMoveFreePieBridge/PSMoveSteamVRBridge.

See [here](https://github.com/cboulay/PSMoveService/wiki/Virtual-HMDs) for setting up a virtual HMD

See [here](https://github.com/HipsterSloth/PSMoveSteamVRBridge/wiki/Virtual-Controller-Setup) for virtual controller setup.

@maxternal This should be possible using FreePIE if someone has written a FreePIE adapter for the device that provides the orientation (phone or wiimote). PSMoveService can provide the bulb tracking data and for VirtualControllers can provide button data from an XInput controller. 

@Tux0Topo Since this feature is now implemented I'm going to close this issues as resolved. But feel free to continue discussion here.

**Comment by NickBuryak** [comment]
> 1. Use Epipolar Geometry to determine which blobs in one camera frame correspond to blobs in another camera frame (See https://en.wikipedia.org/wiki/Epipolar_geometry)
> 2. Triangulate points that have corresponding blobs between pairs of camera
> 3. Determine the HMD pose that best aligns the LED locations on a PSVR mesh with the triangulated points
@HipsterSloth Is it possible to implement? Since PSMoveService supports multiple ps3 eye it will open up new possibilities for true motion capture.
