### ISSUE TITLE
Bluetooth loop issue on pairing

### ISSUE THREAD

**Issue by Beren89** [cboulay/PSMoveService#223]
Hi, I have an issue when pairing the Move. The pairing completes, but then instead of showing the newly paired device among the bluetooth connected controllers, the config tool enters in "blinking" state.

In the log of the PSMoveService there is also a code looping:

"PSMoveController::open - Opening PSMoveController(\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&03d5&col01#9&22ac4eaa&4&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})[2016-10-03 12:56:21.906]: 
PSMoveController::open -   with serial_number: 0006f5e4dbf6[2016-10-03 12:56:21.909]: 
PSMoveController::getBTAddress - HID ERROR: The requested resource is in use.[2016-10-03 12:56:21.913]: 
PSMoveController::open - Failed to get bluetooth address of PSMoveController(\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&03d5&col01#9&22ac4eaa&4&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})[2016-10-03 12:56:21.924]: DeviceTypeManager::update_connected_devices - Device device_id 0 (\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&03d5&col01#9&22ac4eaa&4&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}) failed to open![2016-10-03 12:56:21.941]: DeviceTypeManager::update_connected_devices - Closing device 0 (PSMove) since it's no longer in the device list.[2016-10-03 12:56:21.946]: 
PSMoveController::close - Closing PSMoveController(\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&03d5&col01#9&22ac4eaa&4&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})"

**Comment by siliciorock** [comment]
i have the same issue.. try changing the BT module for other.

Cliptec BT 4.0 works fine for me

**Comment by rebitti** [comment]
I have this problem and a brought another dongle ! Now i have a cheap usb 4.0 bluetooth dongle and works fine !

**Comment by HipsterSloth** [comment]
Hmm... I wonder if I need a timeout for recently paired controllers before I attempt to open them. The Windows bluetooth stack is incredibly finicky to work with (lots of timing dependent code). Thanks for posting about the issue.

Now that the controllers are paired and you have restarted psmoveservice are you still seeing the loop issue or can you connect to the controllers?

**Comment by HipsterSloth** [comment]
@Beren89 Are you running a version of windows older than Win10 by chance? I wonder if this is the same issue as #248.

**Comment by HipsterSloth** [comment]
@Beren89 Could you give this custom build a try: 

[PSMoveService-v0.9alpha5_4_1_custom.zip](https://github.com/cboulay/PSMoveService/files/535390/PSMoveService-v0.9alpha5_4_1_custom.zip)

I think this might be the same issue as #248

**Comment by HipsterSloth** [comment]
I'm going through and close all issues that are troubleshooting support related for tracking purposes.
