### ISSUE TITLE
5.2 release broke SteamVR

### ISSUE THREAD

**Issue by toto5100** [cboulay/PSMoveService#231]
Hello,
With the 5.2 release, SteamVR crashes each time i try to launch it. On the screen, it starts correctly, but only the headset is detected (not even the dk2's tracker). But in the headset, everything is frozen, and it seems that it makes vrserver.exe crash (i have to force quit steamvr.exe,vrserver.exe and vrcompositor.exe using control panel to quit steamvr).

Also, using test_console_client.exe, i noticed that i'm getting bad update performances (~30FPS), even with 5.1 release. Is it normal ?
Thanks

**Comment by HipsterSloth** [comment]
I'm actually having problems with vrserver crashing myself. At first I thought it was my plugin, but after uninstalling in the psmove plugin vrserver kept crashing for me. Even a complete re-install of steam hasn't fixed vrserver for me. 

-If you uninstall the psmove plugin, do you still get the same crash?
-if you close psmoveservice.exe and run test_cameras.exe are you getting a solid frame rate on the video feeds?
-can you attach vrserver log from the steam/logs folder?
-are there any recent .dmp files for vrserver in the steam/dumps folder?

**Comment by toto5100** [comment]
- No, it does not crash. It only crashes when psmoveservice 5.2 is running.
- With test_cameras.exe, i have a very smooth framerate, it looks like it is 60fps.
- I attached vrserver log.
- There are some dumps, but they are from yesterday, not today's tests.
[vrserver.txt](https://github.com/cboulay/PSMoveService/files/518516/vrserver.txt)

**Comment by HipsterSloth** [comment]
It sounds like you aren't having any USB issues if test_cameras is running at 60fps. Not sure why the test_console_client would be getting updates at 30fps. It should be trying to read data as fast as possible (only a 1ms sleep in the main loop). What does the contents of your `%appdata%\PSMoveService\ControllerManagerConfig.json` look like (There is a setting in there that controller how fast we poll the controllers.)? 

From the vrserver log it looks like it connecting to PSMoveService just fine:

> psmove: NotifyClientPSMoveResponse - Controller Count = 1 (request id 0).
> Sun Oct 09 2016 21:26:20.529 - psmove: added new psmove controller id: psmove_controller0, serial: 00:13:8A:9B:71:93

Since you aren't seeing any new dump files it sounds like you aren't getting a crash, but rather vrserver is shutting down. It looks like vrmonitor is is requesting a shutdown in the log you sent:

> Sun Oct 09 2016 21:43:38.448 - Process vrmonitor (1212) has initiated a quit all
> Sun Oct 09 2016 21:44:45.092 - IPCPipe(vrmonitor (1212)): Process disconnected.
> Sun Oct 09 2016 21:44:45.093 - Process vrmonitor (1212) disconnected

Would you mind posting your vrmonitor log? Maybe it will say in there why it's sending the quit message?

**Comment by HipsterSloth** [comment]
Finally got Steamvr working again (netgear usb printer drivers were causing a problem for vrserver). 

However the first time I was testing the new 5.3 release, I hit your issue. I shutdown steamvr, psmoveservice, steam and then deleted the contents of the `Program Files (x86)\Steam\logs`. Then everything worked for me upon restarting PSMoveService, Steam, and SteamVR. I'd be curious if this works for you.

**Comment by toto5100** [comment]
I tried to delete logs folder but it still do not work. The steamvr window is not saying that a key component of SteamVr is not working, and nothing (not even the hmd) is detected.

**Comment by HipsterSloth** [comment]
Could you post your latest vrserver.txt and vrmonitor.txt logs from `Program Files (x86)\Steam\logs`

**Comment by HipsterSloth** [comment]
I think this might be the same problem as issue #239.

Try shutting down steamvr and psmoveserver. Then look in process monitor for any remaining instances of vrserver.exe. Kill those. Then restart psmoveservice and steamvr.

I've got three issues tracking what are likely the same problem so I'm going to close this issue for tracking purposes, but please keep posting updates in this thread.

**Comment by toto5100** [comment]
Even when it's the first time I use psmoveservice there is the problem. It's now not a crash of SteamVR, but it says "A key component of SteamVR isn't working properly" : http://imgur.com/a/i08b5
Also, i attached my vrserver and vrmonitor logs.
[vrserver.txt](https://github.com/cboulay/PSMoveService/files/522754/vrserver.txt)
[vrmonitor.txt](https://github.com/cboulay/PSMoveService/files/522755/vrmonitor.txt)
[steamvr system report.txt](https://github.com/cboulay/PSMoveService/files/522756/steamvr.system.report.txt)
And also a steamvr system report.
