### ISSUE TITLE
Calibration issues

### ISSUE THREAD

**Issue by wewen79** [cboulay/PSMoveService#233]
I have two cameras and two controllers. I calibrated via the calibrationmat method and got good results with controller 0. My issue are that controller 2 are tracking really bad. Don't know how to get that one to track reliable since you only calibrate the first controller.

**Comment by HipsterSloth** [comment]
For troubleshooting help please post questions to the google group:
https://groups.google.com/forum/#!forum/psmoveservice

We're trying to make the issue list be just for reporting specific reproducible bugs. I'm going to close this issue for tracking purposes.

As for tracking issue, it sounds like the color calibration isn't correct for the second controller. The calibration mat method is just used to compute where the tracking cameras are relative to the calibration mat. You need to calibrate each tracking color you want to use for each controller for each camera. If you are using two controllers, this means calibrating cyan and magenta on both cameras.
