### ISSUE TITLE
BOOST_APPLICATION_FEATURE_NS_SELECT not a class or namespace name

### ISSUE THREAD

**Issue by liuping001** [cboulay/PSMoveService#234]
Project PSMoveService can't compile

**Comment by HipsterSloth** [comment]
-Which platform are you building on?
-What are you using to compile psmoveservice?
-Did you use the build instructions from here? 
 https://github.com/cboulay/PSMoveService/wiki/Building-from-source
-If so, did build using the initial setup script (assuming you were on windows) or the manual setup steps?

**Comment by liuping001** [comment]
windows 7
platform:vs2015
yes,initial setup script

**Comment by HipsterSloth** [comment]
Sorry it took me so long to reply back. 

I was finally able to do a test build on a Win7 machine. I do all of my development on Win10 normally so I thought there might be an issue building on an older version of Windows. However I was able to successfully run the the [Building-from-source](https://github.com/cboulay/PSMoveService/wiki/Building-from-source) steps and compile Debug and Release builds for both Win32 and x64.

The `BOOST_APPLICATION_FEATURE_NS_SELECT` constants is defined in `thirdparty\Boost.Application\include\boost\application\config.hpp` which is a third party library PSMoveService uses. Does the `thirdparty\Boost.Application` directory exist for you? If not did you use the `--recursive` flag when cloning the repository?

If you do have the `thirdparty\Boost.Application` then perhaps there is some other reason the `BOOST_APPLICATION_FEATURE_NS_SELECT` isn't getting defined. You could try replacing all the instances of `BOOST_APPLICATION_FEATURE_NS_SELECT` with `std` in PSMoveService.cpp and see if that fixes it.

For what it's worth, I would like to remove the dependency on the Boost.Application library. It's way to complicated for what it provides. It's just meant to be a wrapper around making a Windows service/ unix daemon, but the same functionality could be written without using that library and it would avoid this compile issue.

**Comment by HipsterSloth** [comment]
deleting old support tickets. If this still an issue for you, please post an issue in the google group:

https://groups.google.com/forum/#!forum/psmoveservice
