### ISSUE TITLE
non ps move color light tracking option   

### ISSUE THREAD

**Issue by iamapie13** [cboulay/PSMoveService#241]
hello, I am trying to make a DIY VR controller with a wii mote, I found some source code to implement the wiimote as a controller, I found how to use it's roll pitch and yaw (wii motion plus) but for "X Y Z" I am thinking to use the same mechanism of the PS move, even using a PS eye camera, on the top of the controller I have a dollar store flashlight with a color filter that I added, and it has a ping pong ball with the same size as the PS move one, the problem is that now I just need the software to make this all work, but I'm not really a developer, can you please add this feature? I've seen more people also requesting the same

**Comment by cboulay** [comment]
Please read the README or the wiki section on getting help. Posts like this should go in the google group.

Just so I don't have to reply to a post there too: This is pretty far down my list of priorities, as I assume it is for @HipsterSloth , but you might be able to find someone else willing to work on it sooner than 6 months from now.
