### ISSUE TITLE
PSNAVI Wiki

### ISSUE THREAD

**Issue by rebitti** [cboulay/PSMoveService#243]
Hello, the PSNavi ( Navigation Controller ) is not cover on the documentation of Wiki ? (i didnt find easily, i remember i saw one time )

Someone can do a video how-to setup easily this device to work togheter with PSMOVEService ?

i think community will really appreciate that.

best regards for all.

**Comment by Fr0zenfire** [comment]
It hasn't been fully implemented yet.

**Comment by rebitti** [comment]
okay, i found this wiki, got from psmoveservice google group: https://github.com/HipsterSloth/psmove-unity5/wiki/PSNavi-Setup-(Windows)
