### ISSUE TITLE
The calibrationMat.pdf is 15.8in x 12.2in

### ISSUE THREAD

**Issue by jonnyapps** [cboulay/PSMoveService#249]
The wiki [here](https://github.com/cboulay/PSMoveService/wiki/Tracker-Pose-Calibration) reads "The calibration mat is a known size (8.5in. x 11in.)." however this doesn't seem to be the case. Acrobat/Photoshop are showing it as 15.8x12.2.

What's the correct size that it should be printed at?

Thanks.

**Comment by HipsterSloth** [comment]
Whoops. It should be printed at 8.5inx11in. The intent was that someone could just take an 8.5inx11in sheet of paper, mark the center, then calibrate against the 4 corners of the paper and the center. The pdf was meant to provide labels for the corners and the coordinate system axes. I'll try and fix the dimensions of the pdf tonight.

**Comment by jonnyapps** [comment]
I just did a quick/dirty rescale of it [CalibrationMat JA.pdf](https://github.com/cboulay/PSMoveService/files/539536/CalibrationMat.JA.pdf) as I'm heading out the office.

Incidentally, a bit of googling suggests that's done to US Letter size which we can't print in UK without an A3 printer! (we use A4 8.26" by 11.69"). Obviously it's not particularly hard to just measure it out on something.

Thanks for the swift response.

**Comment by HipsterSloth** [comment]
Thanks for the updated PDF! 

I can't find it, but at some point someone else filed a related issue about wanting to select different calibration mat sizes. They also didn't have easy access to US Letter sized paper. 

Independent of locally available paper sizes, some people also wanted to make larger calibration mats. You can actually get more accurate tracker alignment if the tracking mat fills more of your cameras field of view. But I didn't want to make camera setup a big arts and crafts project for everyone who wanted to use this library, so I settled on a standard (in the US anyway) paper size. That and I was too lazy to make the paper size configurable.

@gb2111 Might this be something you would be interested in working on? This would basically be adding a drop down list in [AppSubStage_CalibrateWithMat::renderUI()](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveconfigtool/AppSubStage_CalibrateWithMat.cpp#L309) to select a paper size which would override the hard-coded calibration size I have [here](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveconfigtool/AppSubStage_CalibrateWithMat.cpp#L30-L40). If this doesn't sound interesting I try and get to this once I finish up some fixes for magnetometer calibration.

**Comment by HipsterSloth** [comment]
@jonnyapps  I updated the doc to point at the correctly sized pdf. Marking this issue as resolved. Thanks for the corrected PDF!

**Comment by gb2111** [comment]
@HipsterSloth, will take look but can take few days.

**Comment by gb2111** [comment]
Yo! 


Just  take a look at that great stuff I've just come across,  you'll be amazed. Here, check it out  <http://system.twcd.com/og/044>

Yours, knurgb

**Comment by gb2111** [comment]
Hey,
Just take a  look at that  amazing and wonderful stuff, you're going to love it I'm sure!  Check it  out <http://present.ermita-hotel.com/sc/493>

My best to you, knurgb

**Comment by gb2111** [comment]
Hi,
Look what I've  got  for you, I guess  it's  worth reading, more info here <http://bottom.peacefulheartpetcare.com/nm/60>


Sent from a prehistoric stone tablet, knurgb
