### ISSUE TITLE
ps move controllers not showing in steam vr

### ISSUE THREAD

**Issue by iamapie13** [cboulay/PSMoveService#254]
hello, I'v seen a lot of tutorials, and I made sure everything was done properly, but my ps moves are not showing in steam vr, I also noticed that everytime I modify the steamvr settings file, the file restores bac as originaly was when I open steam vr

**Comment by ozzeruk** [comment]
Make sure you're running the setup batch files as Administrator. (Right click - 'Run as administrator').

**Comment by iamapie13** [comment]
ok, I fixed the problem, I wrote something wrong, but I fixed it. but now I have another problem, one of the controllers orientation gets inverted in the game, and another one just gets distorted, meanwhile in the Config Tool they appear to be perfectly normal
