### ISSUE TITLE
Failed to pair controller!

### ISSUE THREAD

**Issue by Dropper7856** [cboulay/PSMoveService#257]
![capture d ecran 26](https://cloud.githubusercontent.com/assets/23097919/19764896/ca3b3118-9c45-11e6-990d-f1c70577d344.png)
 

Hi guys I have a small problem

Failed to pair controller!

Help me Please

If you do not see the picture 

http://i.imgur.com/4R9Irjj.jpg

**Comment by HipsterSloth** [comment]
For troubleshooting help we are trying to get people to post to the psmove google group first:

https://groups.google.com/forum/#!forum/psmoveservice

Once we have identified the core of the problem then we create an issue for it. There are also more people watching the google group so it's easier to get support that way.

Could you open a new thread in the google group with this image and also paste the output of the PSMoveService windows (not the PSMoveConfigTool windows). That will have detailed logs about what happened when the service was trying to pair with the controller.

You might also give this latest alpha-5.4.4 custom build a try (it has some newer code that will be out in the next release):

[PSMoveService-v0.9alpha5_4_4_custom.zip](https://github.com/cboulay/PSMoveService/files/556555/PSMoveService-v0.9alpha5_4_4_custom.zip)

I'm going to close this issue for tracking purposes. If we determine that there is in fact a bug we can reproduce we'll re-open this issue.
