### ISSUE TITLE
Setting the tracker exposure in Windows can randomly crash the PSMoveService

### ISSUE THREAD

**Issue by HipsterSloth** [cboulay/PSMoveService#26]
Pulling this out from issue #24, since this is still a problem:

There is a nasty multithreading related crash in PSMoveService when running in Windows I found when adjusting the exposure in in the tracker config tool.

It turns out that there is a bug in libusb's windows implementation of the transfer request queue that isn't multithreading safe. Specifically in windows_handle_events. It's getting a pointer to a transfer_priv out of the transfer request queue while the list is locked, but then reading from that pointer after the lock is release. That means if another thread comes along and writes another transfer request it could stomp the memory that that transfer occupies.

And in fact this happens when you set the exposure while the video stream is running. The video transfer thread is issuing bulk transfer requests when the main thread can come along and inject a control transfer request (i.e setting the exposure or some other camera property). We didn't notice this before in psmoveapi because we set the exposure and then start the video transfer.

We can fix this one of a few ways. I think the simplest thing to do though is just get the lastest version of libusb and see if this crash is fixed. It looks like windows_usb.c has been largely refactored in latest version (the filename is now windows_winusb.c). If we don't want to do that we could fork libusb and spot fix the issue too.

**Comment by cboulay** [comment]
Any objection to pointing `thirdparty/PS3EYEDriver` to `inspirit/master` then closing this issue?

**Comment by HipsterSloth** [comment]
Nope, sounds good to me.
