### ISSUE TITLE
I can't use 3 cameras

### ISSUE THREAD

**Issue by iamapie13** [cboulay/PSMoveService#260]
when  I plug my 3th camera, ps move service goes slow

**Comment by CircuitLord** [comment]
Its possible you don't have a good enough cpu for this. Can you check your cpu usage when you have the test_camera.exe running and the cameras plugged in?

**Comment by iamapie13** [comment]
ok, I don't know what happened, but it suddenly began to work, I have no idea how, but now I can use up to 4 cameras with no problems. this makes no sence
