### ISSUE TITLE
any way to delete all configuration and history?

### ISSUE THREAD

**Issue by iamapie13** [cboulay/PSMoveService#262]
hello, I want to delete all existing data of PS move service to begin again from scratch, the reason I want to do this is because PS move service always wants to unpair my move controllers and always says "failed to unpair" and doesn't let me pair them at all, I tried to delete the %appdata% folder of PS move, but same thing keeps happening, is there something I'm missing?

**Comment by POEDaley** [comment]
Controller pairing is saved by Windows.  You can try going into your devices and printers window and right click all of your motion controllers and selecting "Remove Device".  That should allow you to pair the controllers again using the config.

**Comment by iamapie13** [comment]
I tried that, didn't work, BUT I FOUND A SOLUTION! :D (after 3 days) I pluged my bluetooth adater on  U.S.B 3.0 port, and that was the weird issue, once I changed it to a 2.0 port it worked perfectly fine.
