### ISSUE TITLE
Use simpler positional tracking algorithm when bulb is too small to get cone fit AND multiple cameras see bulb.

### ISSUE THREAD

**Issue by gb2111** [cboulay/PSMoveService#265]
Hi,
This is continuation of this thread from google groups:
https://groups.google.com/forum/#!topic/psmoveservice/BlpF-2af5kw

In 2 cam setup, player is in front of them and they can be pretty close (like for PSVR), so BULB is pretty close and distance calculation based on its size can be accurate.
In case of 4 cam setup you are usually far from each camera. The size is very small but still possible to detect it as point or group of pixels but calculating eclipse based on that can be very inaccurate and even one or two pixel change totally changes estimates. However in this case we heave multi camera interpolation what makes whole thing working.
From what I have observed, interpolations to ellipse if distance is far (which is at least 2 cameras always for me) is causing jittering of the controller. When I tested distance with only one camera as I move it far away I can observe identical jittering in Z dimension by about 10 - 20 cm as distance is far.
But we use only X and Y to triangulate 3d position - yes, but X and Y are calculated together with Z in a single model of ellipse and error in Z is also propagated to other coordinates. The intense of jittering with one camera is same as small shaking in multi cam scenario.

My proposal is allow calculation of 3d position only by interpolation of flat 2d points from each camera. Moreover I would like to calculate these points as average of masked pixels in detected region, not the contour.

Since the code is very complex I would appreciate your input here. I have been trying to implement based on modification of existing code but in this case deeper understanding of topic is required. 
Thanks.

**Comment by gb2111** [comment]
ok. i think i got it. will post info.

**Comment by toto5100** [comment]
Another thing that can improve your method i think would be a non binary mask for the blob (i dont know if it's possible). By this way, we can weight each pixel of the detected region, and then have subpixel accuracy (each little move would change the intensity of the edge's pixels) using the "average of masked pixels" method. This would allow the triangulation to be much more precise.

However there are some problems, when the blob is partially masked, this would lead to an error.

**Comment by gb2111** [comment]
Hello @toto5100 ,
Do you mean to apply this to threasholded image? Don't you think its 'almost' binary so no point in weighting?

I implemented pseudo code and it worked but did not solve problem.
The problem of shaking is really not solvable I think unless we have Kahlman filter if I get it correct.
If we are far we can only interpolate up to dimension of camera and I think the minimal step is proportional to distance, like resolution@distance ~ distance * size of camera pixel.

I still did few attempts and have some results which I prefer describe once few of you do me favor and comment on results. Which one is better? I was doing my tests on 2 cameras only about 5 meters from wall where camera is located (so probably 6 m in straight line). This is where end of playing area is.

https://www.youtube.com/watch?v=Q_Y1iJHZ1cA
https://www.youtube.com/watch?v=qNcdKbx5hRg
https://www.youtube.com/watch?v=Dl4kiUExJOE
https://www.youtube.com/watch?v=YGec6RbSNcs

**Comment by toto5100** [comment]
I wanted to say that instead of using a pure thresholded image we could only use it to determine a region of interest, and then we use an image that uses a threshold to 0 (like here http://docs.opencv.org/2.4/doc/tutorials/imgproc/threshold/threshold.html) so we can keep the intensity of pixels in the edge. I don't know if current tracking algorithm is already subpixel accurate or not. If not, we cannot have an accuracy better than a few milimeters in X and Y when distance is increasing (due to resolution limits)

**Comment by toto5100** [comment]
Also, i think the lasy video is the best

**Comment by gb2111** [comment]
Yes, last is best.

I am using simple exponential moving average so I am simply adding some simple physics what especially helps is controllers is moving.

v1 is current model where we estimate Z for each camera from ellipse size. Like expected it is very jittery as ellipse is small and far away.
v2 is much better - we use only 2d center of mass of detected contour.
v3 - we are adding exponential moving average to v2 - we see that we still getting errors from Z.
v4 - exponential moving average applied to 2d center of mass.

I will do tests close to cameras and see results. I am very happy with v4 especially about my experience when I move controller.

**Comment by gb2111** [comment]
@toto5100, yes that is interesting ohwever this means totally new approach for filtering image. lot of work :)

**Comment by cboulay** [comment]
@toto5100 Let's keep the discussion to the issue at hand. There are lots of ways to improve tracking, and this issue and discussion is limited to just one way.

**Comment by gb2111** [comment]
examples when i am close to cameras which is 2m from wall and they are about 4m from each other on this wall near top.
still worse results are with existing method and calculation of ellipsis, then trangulation based on 2d and then smoothed. this is actually distance where controller buld is starting to look like ellipsis so error can be huge due to setup.

https://www.youtube.com/watch?v=55SX6m4hv50
https://www.youtube.com/watch?v=yuW10I_d7qw
https://www.youtube.com/watch?v=-cFf6hCEff0

**Comment by cboulay** [comment]
@gb2111 . Please see issue #50

**Comment by gb2111** [comment]
Tried new release and if controller is still it really remains still - no shaking. Looks just great!

**Comment by gb2111** [comment]
@cboulay , @HipsterSloth 
i have been thinking about best way to avoid controller jump when BULB in one or more camera goes off or is back and have question that might be able to help. based on this calculation i will be able to calculate error in specific location and make adjustment. i have been thinking about many approaches to this problem and this one seems to be the best.

lets say i have 3 cams and 3rd lost BULB. do you know how to calculate potential 2d location of BULB on 3rd camera so the triangulation from 1+3 will  give same result as we have from triangulation of 1+2 ?

so if we have usually
point3d(cam1,cam2) = triangulatePoints(cam1bulb, cam2bulb)
i want
cam3bulb-estimate(cam1,cam3) = reverseTriangulatePoints(point3d(1,2), cam1bulb).

thx

**Comment by gb2111** [comment]
so what I found is that even if I use 2 points from a distance it does not improve accuracy, even though Z might vary. the biggest effect was simply by adding exponential moving average.
