### ISSUE TITLE
 Tracker appears in middle on ps move controller in "compute tracker poses"

### ISSUE THREAD

**Issue by Xorcist137** [cboulay/PSMoveService#266]
I have 4 ps eye cameras in each corner of my room, and even though I have calibrated the tracking colors of every tracker and calibrated the controller, each time I compute tracker poses, the controller jitters all over the place and one of the trackers appears in the middle of the area, sideways.
![capture](https://cloud.githubusercontent.com/assets/22970192/20032997/bc264b3e-a36c-11e6-8a67-8f9f79aeda21.PNG)

**Comment by gb2111** [comment]
hi,
please check if you have any conflict color in room.
during calibration cover bulb with hand so no camera can see it and put stright like for calibration.
if you see that any camera detects color and counting up this means that color calibration picks also other elements in your room.
this is one possible cause which I was facing.

**Comment by Xorcist137** [comment]
Another issue is that each time I calibrate tracking colors, going back into ps move config resets it and I have to redo it even though its the same lighting

**Comment by gb2111** [comment]
this issue exists indeed. but happens occasionally to me.

**Comment by HipsterSloth** [comment]
Closing old support tickets. If this is still a problem, please post a support request in the google group:
https://groups.google.com/forum/#!forum/psmoveservice
