### ISSUE TITLE
Black screen with hourglass

### ISSUE THREAD

**Issue by Zanop** [cboulay/PSMoveService#267]
When playing 'Tabletop Simulator' and 'The Lab' I get black screen with hourglass inside HMD. 
I'm using 2xPSEYE, 2x Move controllers and Rift CV1. In 'The Lab' the problem seems to only appear when using the Bow while in 'Tabletop Simulator' it just happens randomly at some point. Rendering of the game on the monitor is not affected, all is good there, headtracking works, you can see what happens on the monitor but not in the HMD. HMD remains black with only the hourglass showing.
The only reliable solution to this problem seems to be relaunching the game. Steam/Oculus overlay switching does not help.
I have disabled the rumble as suggested in https://github.com/cboulay/PSMoveService/issues/189 and tested with the bow again. I was able to play for a bit longer but ended up with black screen again. 

While playing Tabletop I was once able to recover from the black screen somehow by alt-tabing and randomly spaming whatever buttons I could but I could not replicate it later.

**Comment by cboulay** [comment]
Please post this type of issue in the google group first. Also, please search for other mentions of the black screen and post in those topics before creating a new one.
