### ISSUE TITLE
SteamVR without Vive Software?

### ISSUE THREAD

**Issue by mungewell** [cboulay/PSMoveService#268]
In prep for PSVR... 'SteamVR_InitialSetupWin64' gives error message

    "No steamvr folder found at C:\Program Files (x86)\Steam! Please install steamvr."
    Press any key to continue . . .

If I go to install the Vive software, it gives me no choice not to sign up for there service account...
![vive_account](https://cloud.githubusercontent.com/assets/236907/20033248/0f94d354-a362-11e6-9dca-41e016b366d1.png)
[steam_vr_without_vive.txt](https://github.com/cboulay/PSMoveService/files/573483/steam_vr_without_vive.txt)

Any work around to get SteamVR installed directly, without Vive?
Simon

**Comment by ozzeruk** [comment]
Install Valve's Steam software (free - do a Google Search) - then look for SteamVR on the Steam store (it's free). You'll need to put your email address etc in to create a Steam account, but you don't need to spend any money, and Steam has many 3D demos you can try. No need whatsoever to install any HTC Vive stuff.

**Comment by mungewell** [comment]
I already have Steam installed, see previous 'txt' attachment.

Searching for 'SteamVR' on the store does not find anything that is just drivers (other than Razor drivers). Do you have a URL?

Looking at the free games.
'Realities' is a 10GByte download.
'The Lab' is also 10GByte download.
'Destinations' is a 6GByte download.

It would be preferable not to have to download too much (some in the world are on slow and/or metered connections).
Simon

**Comment by ozzeruk** [comment]
Interesting, they must have changed that. You should be able to access it by going into Steam (the program rather than the website) - then go to Library->Tools, and from a long list of possible downloads should be 'SteamVR'.

I just checked and it says 1.1gb used, which is a bit nuts for what it is.

**Comment by ozzeruk** [comment]
I'm sure it used to be on the store when you did a search. Seems like it isn't now, but I'm presuming it's on everyone's Library/Tools list.

**Comment by cboulay** [comment]
It wouldn't make sense for them to remove SteamVR as an installable tool. There must still be a way to find it. Follow the instructions [here](https://support.steampowered.com/kb_article.php?ref=2001-UXCM-4439#install-steam) or Step 8 [here]. Either have a direct steam:// link to SteamVR which should find it for you if your Steam is catching those links.

**Comment by mungewell** [comment]
Solved! As @ozzeruk suggested, 'SteamVR' is listed under Library/Tools. I was able to install it from there and when launching, it (correctly) tells me I have no headset or controllers.

I can now run 'SteamVR_InitialSetupWin64', which tells me it has installed some files. Over to https://www.youtube.com/watch?v=XiLYa1EZL04 to complete the processing I guess.

Cheers,
Simon.
