### ISSUE TITLE
ability to exclude opposed cameras from trangulation in 4 cam setup

### ISSUE THREAD

**Issue by gb2111** [cboulay/PSMoveService#269]
hi,
this is to document change as described in title also started on group
https://groups.google.com/forum/#!topic/psmoveservice/V5xG1rVt2RM

i think that opposed cameras in 4 cam setup are causing jumping due to poor triangulation when bulb is almost near the line connecting opposed cameras (as there is no triangle). i made test build and the problem is gone. not sure if I am only one (with Raj) who complains about this but it was often disturbing during gameplay.

**Comment by HipsterSloth** [comment]
That's a good idea! Since we know where the cameras are we could throw out camera pairs using a simple dot product test. I've also wanted to modify the position averaging to be weighted based on pixel projection area on that tracker. Basically trust the position result where the bulb is closer to the camera.

**Comment by gb2111** [comment]
similar video. after opposite cams are excluded problem goes away. you see its even bit below where controller tracking was fine.
https://youtu.be/ldkrThBjmt4

**Comment by Leonidas2015** [comment]
Ive noticed some added issues with having the 4th camera. 

Controller jumping around more then it should. 

Seems like controllers Do not fallow the headset as accurate as it should in full room scale.

**Comment by gb2111** [comment]
@Leonidas2015 can you try this build and let me know if helps?
https://drive.google.com/file/d/0B7IfNQ-sEI8uN05iTFpacUhaT0U/view?usp=sharing

**Comment by Leonidas2015** [comment]
I will do that first thing today and report back as soon as possible

**Comment by Leonidas2015** [comment]
Through my testing the most recent build you asked me to try seems a lot more stable with the 4 cams. Seems to track better even when 1 of the 4 cams loses sight of the controller. 

Before this most recent build the controller would jump position/location when one cam would lose sight. 

One thing I do notice is if you stand in one place and rotate in a circle the controller move away from the bodies position slightly. Slight orientation/distance issue with positioning of controllers in respect to body position. 

Overall the latest test build seems to be the best. 

Faster startup and controller recognition. 

Let me know of the next test build and I will do more research and testing. 

Happy to help great work everyone, Great team.

**Comment by gb2111** [comment]
@Leonidas2015 , good to hear it helped. I hope will be available in next official release.

Regarding other issue, I think its something related to accuracy of trangulation. Each camera pair do it a bit differently and we do average. I really don't know if its possible that each camera do it 100% or more close to this. 
Perhaps this will help: each camera (x lens) needs a default camera matrix and (null) distortion coefficients
https://github.com/cboulay/PSMoveService/issues/50

**Comment by gb2111** [comment]
@Leonidas2015 , did you set them up as described on wiki?

**Comment by lokii30c** [comment]
Anyway we can get a youtube tutorial on the key assignments?

**Comment by gb2111** [comment]
Hi,
Its actually described on wiki.
https://github.com/cboulay/PSMoveService/wiki/Steam-VR-Setup#configure-steamvrvrsettings

**Comment by lokii30c** [comment]
I followed the wiki and the key bindings don't register in-game.

**Comment by HipsterSloth** [comment]
> Anyway we can get a youtube tutorial on the key assignments?

@POEDaley Might this be something you would be interested in doing? I'm pretty slow at throwing together youtube tutorial videos.

> I followed the wiki and the key bindings don't register in-game.

@lokii30c Could you start a thread over here about the key assignment issue, since this is unrelated to this tracking issue: https://groups.google.com/forum/#!forum/psmoveservice. Also would you mind pasting your steamvr.vrsettings file in that thread. That way we can see if there is anything wrong with the settings you are using.

**Comment by POEDaley** [comment]
No sweat.  It's really the least I can do to help out.  If there is
anything else you could think of that would be beneficial to do a video
walk through of, just let me know.

I'll try to have that one up by the end of the weekend.

**Comment by Leonidas2015** [comment]
Appreciate you making the YouTube video for key bindings. 

I have had some issues also with key binding. 

Currently x, square, triangle and circle do nothing for me lol. Probably just a binding issue. 

Also I do not think the touch u lotion works for me probably a key binding issue also. 

This video will help a ton.

**Comment by POEDaley** [comment]
No problem.  I have one I'm just finishing up with now, then I'll make that keybinding one.  Busy weekend ahead of me, but I'll do what I can to get it posted.

**Comment by HipsterSloth** [comment]
New release with Greg's triangulation fix is up:
https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha5.5.3

Closing this issue for tracking purposes. Feel free to continue discussion though.

**Comment by gb2111** [comment]
Hi,
I wonder if you know how to tell what is actual triangle of triangulation?
Opposite cameras as often only ones that can capture BULB near edge of game arena :)
I can do simple solution that would work for me very well - check if vertical coordinate is below certain level but perhaps there is better solution. I was looking on triangulateWorlsPosition but bell does not ring...
Thanks.
 
W dniu 2016-11-14 02:42:37 użytkownik Guido Sanchez <notifications@github.com> napisał:
New release with Greg's triangulation fix is up:
https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha5.5.3
Closing this issue for tracking purposes. Feel free to continue discussion though.

**Comment by POEDaley** [comment]
Wasn't able to get the video up on the weekend.  My Sunday was an utter
write off due to multiple reasons.  I have no other videos in the hopper
now and this one is my next task.  If all goes well, later tonight it
should go up.

Thanks,

**Comment by POEDaley** [comment]
Video Posted.  Hope it helps.
https://www.youtube.com/watch?v=eU9Vo-DQenw

**Comment by Leonidas2015** [comment]
Much appreciated. 

Fallowed your instructions and now I have two steamvr settings files, one for dpad one for thumb. Great work. 

Have not tested it yet in vr/steam but I will be soon. 

Great work.

**Comment by HipsterSloth** [comment]
Thanks @POEDaley! The steamvr setup was one of the more opaque parts of the setup process.  Mind if I link to this video in the wiki?

**Comment by POEDaley** [comment]
Please do.  Feel free to use whatever you need :)
