### ISSUE TITLE
save CPU - receive flipped image directly from camera instead via code

### ISSUE THREAD

**Issue by gb2111** [cboulay/PSMoveService#271]
there is ability to get flipped image directly from camera though we can avoid doing it in code.
this gives about 5% less CPU (from 52 to 47) on 4eye+3controllers setup.

**Comment by Leonidas2015** [comment]
Sounds great to me. 

That is my setup currently. 

2 controllers as controllers and one controller for headset tracking with 4 Ps eye trackers. 

I do not own an oculus tracker.

**Comment by HipsterSloth** [comment]
Greg's change has been integrated in. I'll try and make a new release this Sunday with it.

**Comment by Leonidas2015** [comment]
What an amazing team and group of individuals. 

I applaud everyone's work, effort and contribution very much. 

😎

**Comment by Leonidas2015** [comment]
Just so you know Daydream/Google Vr is working now on the Galaxy S7 edge running 7.0 Nougat Android update. 

Might help with some of the drifting issues. 

Just a thought.

**Comment by Leonidas2015** [comment]
Or maybe that is more of a rift at concern lol either way thought it should be know just in case. 

https://youtu.be/IuoIWU2x1I0

**Comment by HipsterSloth** [comment]
Greg's image flip fix went into the 5.5.2 release:
https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha5.5.2

That said there is a newer release I just put out today with that fix + Greg's opposing camer triangulation fix:
https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha5.5.3

Closing this issue for tracking purposes. Feel free to continue discussion though.
