### ISSUE TITLE
get/set LEDs

### ISSUE THREAD

**Issue by cboulay** [cboulay/PSMoveService#28]
Currently it is possible to [set LED colour and PWMF](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/PSMoveController/PSMoveController.h#L149-L150) through `PSMoveController`. There is no way to query a controller's LED and PWMF, though the last set values are stored in [PSMoveController private member variables](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/PSMoveController/PSMoveController.h#L165-L167). Obviously we need to expose these through similar getter functions.

1. What should the RGB return type be? We can pass pointers in as function arguments or return a container. FWIW, we shouldn't pass in pointers because we don't do that for any other function. Here's what it might look like to return a std::tuple

```
const std::tuple<unsigned char, unsigned char, unsigned char> getLED() const
 {
    return std::make_tuple(LedR, LedG, LedB);
}
// Use with...
unsigned char r, g, b;
std::tie(r, g, b) = controller.getLED();
```

I'll update this issue with another question once I think through how the tracker is going to know which colours to get positions for. I'm about to add a comment to #12

**Comment by HipsterSloth** [comment]
I think this is satisfied now that we can set/get both the tracking color and and override color
