### ISSUE TITLE
PSMove + PSNavi joiner clip

### ISSUE THREAD

**Issue by Xierion** [cboulay/PSMoveService#281]
In anticipation of being able to use the PSMove and PSNavi with the PSMoveService I have put together a 3D printable design for a plastic clip to join the two controllers together. (see photos attached)

I don't have the STL file on me at the moment, but let me know if you want it to put on the wiki, etc.

![img_20161119_113327](https://cloud.githubusercontent.com/assets/23009638/20451689/5148b258-ae4c-11e6-8fa7-6b2677850d9c.jpg)
![img_20161119_113403](https://cloud.githubusercontent.com/assets/23009638/20451690/514f2534-ae4c-11e6-948d-210544b47d50.jpg)

**Comment by Xierion** [comment]
I also have a clip to join a controller to a BoboVR Z4 HMD

![img_20161119_121913](https://cloud.githubusercontent.com/assets/23009638/20452120/a85f6aae-ae52-11e6-9024-1d54baf3a58d.jpg)
![img_20161119_121826](https://cloud.githubusercontent.com/assets/23009638/20452121/a860c1ba-ae52-11e6-964f-6d2b698829fd.jpg)

**Comment by HipsterSloth** [comment]
Yeah we should definately put this on the wiki! Thanks for sharing that. I'll have to print that myself.

**Comment by Leonidas2015** [comment]
That headset looks like a nice catch. May be grabbing one for myself unless you recommend another headset similar but better

**Comment by Xierion** [comment]
The reviews for the BoboVR V4 Mini seemed pretty good, and I have no complaints so far. Found mine on eBay for about $30 AUD

**Comment by Xierion** [comment]
STLs for 3D printable joiner and HMD clip attached.
[PSMove STLs.zip](https://github.com/cboulay/PSMoveService/files/602912/PSMove.STLs.zip)

**Comment by HipsterSloth** [comment]
BTW after months of promising to do so and not getting around to it I finally got around to working on PSNavi support again (see PSNavi branch). I just got communication working over USB. Tomorrow I'm going to work on bluetooth pairing. Barring any craziness with the bluetooth support (the usb support was suprisingly complicated), I'm hoping to get this wrapped up by the end of this weekend.

**Comment by MaVe-64** [comment]
Great!  @Xierion,  time to take orders from us for the clip ;-)

**Comment by TheUberMedic** [comment]
How good is it at holding the two controllers together? Cause I have docking stations for my controllers so i'm gonna have to keep taking it off. And is it in mm? (gonna hopefully use a public 3D printer to make one :3)

**Comment by Xierion** [comment]
They are pretty firm grips on the controllers, but I would Velcro strap the move controller not in your had in case of vigorous movement. as for taking on and off, the early prototypes with hollow/honeycomb structure had snapping issues with the arms, but since printing solid, I haven't had one snap yet.

Docking the controllers with the clips, while possible, doesn't work overly well as the bases of the controllers are not the same level, and there are issues with centre of gravity, and the dock falling over.

The STLs are designed in mm

**Comment by fbepyon** [comment]
@Xierion I was looking at your design, and if you made it so the Move controller was a bit more to the front, and the Navi controller had more of tilt to the towards to the Move controller it would allow it to be placed in the docking station. 

I myself am working on a 3d printed clip for the Navi / Move controller, and have a similar design to your, but with more of a grip.  Let me know if there is anything I can help with..

**Comment by HipsterSloth** [comment]
I finally have a test release with PSNavi support in:

https://drive.google.com/open?id=0B5GgUbBXlQ1uTzhQTUJkdmRfeW8

I'll be posting instructions with how to set this up tomorrow. Bluetooth support is a bit involved because you need an extra bluetooth adapter and the ScpFramework installed.

**Comment by HipsterSloth** [comment]
Documentation is live: https://github.com/cboulay/PSMoveService/wiki/PSNavi-Setup

**Comment by HipsterSloth** [comment]
I just printed this clip myself. Turned out great! That's a well designed clip. Nice work.

![20170206_142810](https://cloud.githubusercontent.com/assets/16793853/22672164/0e847d52-ec87-11e6-824b-8c2674699222.jpg)
![20170206_143649](https://cloud.githubusercontent.com/assets/16793853/22672178/274a9be6-ec87-11e6-8e01-910c40544942.jpg)

**Comment by HipsterSloth** [comment]
Also for anyone interested who doesn't have access to a 3d printer, you can order a clip for ~$16USD at https://www.shapeways.com/

**Comment by HipsterSloth** [comment]
PSNavi support is not live! I put a link to the clip STL in the PSNavi Wiki

https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha7.0.7

**Comment by zelmon64** [comment]
@HipsterSloth Just to be pedantic you may want to change your last comment to "is **now** live".

**Comment by ychoucha** [comment]
I have one 

https://twitter.com/pimax4kuhdfr/status/860549828799066112


Now I need a second and I need to found how make it works with psmoveservice 

thanks

**Comment by ElectricFighter** [comment]
I don't want to necropost but... are the STL files in mm? Is it better to print them in ABS or PLA?

**Comment by bosshunter** [comment]
I printed 2 clips from STL file provided (thanks @Xierion ) and I used PLA. I'm very happy with it!

![6044302466034109242](https://user-images.githubusercontent.com/3970315/39663496-4a2cc626-506c-11e8-9549-06101daf53f6.jpg)
