### ISSUE TITLE
Errors building hmd_server branch in MacOS Sierra

### ISSUE THREAD

**Issue by cboulay** [cboulay/PSMoveService#282]
I'm going to remove the openvr_plugin from the Darwin CMakeLists, but I thought I'd post the errors first.

```
/Volumes/STORE/Tools/VR/PSMove/PSMoveService/src/openvr_plugin/driver_psmoveservice.cpp:810:33: error: cannot initialize an array
      element of type 'char *const' with an rvalue of type 'const value_type *' (aka 'const char *')
        char * const argv[] = { monitor_exe_path.c_str(), pchDriverInstallDir, NULL };
                                ^~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/STORE/Tools/VR/PSMove/PSMoveService/src/openvr_plugin/driver_psmoveservice.cpp:810:59: error: cannot initialize an array
      element of type 'char *const' with an lvalue of type 'const char *'
        char * const argv[] = { monitor_exe_path.c_str(), pchDriverInstallDir, NULL };
                                                          ^~~~~~~~~~~~~~~~~~~
/Volumes/STORE/Tools/VR/PSMove/PSMoveService/src/openvr_plugin/driver_psmoveservice.cpp:812:19: error: use of undeclared
      identifier 'app'
        if (execv(app, argv) < 0)
```

**Comment by cboulay** [comment]
OpenCV only installs on MacOS Sierra if using the latest OpenCV from --HEAD. Something new with this config of OpenCV is it defines inlines for `sqr` [here](https://github.com/opencv/opencv/blob/master/modules/stitching/include/opencv2/stitching/detail/util_inl.hpp#L122-L124). The code itself is old, but I guess the defaults didn't build this previously.

These are conflicting with PSMoveService's macro defines [here](https://github.com/cboulay/PSMoveService/blob/master/src/psmovemath/MathUtility.h#L38-L40).

It might be possible to fix this by making ServerTrackerView.cpp opencv includes more specific (just specific submodules). Another option is to undefine sqr before including opencv. Or another option is to refactor the macro to something like `psms_sqr`. Any preference?

**Comment by HipsterSloth** [comment]
> I'm going to remove the openvr_plugin from the Darwin CMakeLists, but I thought I'd post the errors first.

That makes sense. Until SteamVR is officially supported on OS X there isn't much point to the plugin. At some point I'll try and fix those compile errors though since that will affect the Linux build as well.

> These are conflicting with PSMoveService's macro defines here.

I removed the sqr macro and did a quick compile test. It doesn't look like were using the sqr macro anywhere so my vote is just to remove it from MathUtility.h.

**Comment by cboulay** [comment]
OK. It now builds in Mac OS Sierra. The `error: use of undeclared identifier 'app'` still exists but I removed the openvr driver build from everything but Windows via cmake for now. I've updated the Wiki with the latest build instructions.

These changes don't have anything to do with the hmd_server branch, but I put them here because psxdev wanted them and (s)he's working on this branch.
