### ISSUE TITLE
Erratic accelerator movement

### ISSUE THREAD

**Issue by sinn24** [cboulay/PSMoveService#283]
I am having issues with my controllers experiencing erratic accelerator movement. I have calibrated the accelerator multiple times, but even when my controllers are set on a solid surface they appear to be moving around in game and in the config tool test environment as if they are being shaken.

It is possible that both of my controllers are experiencing hardware issues, but they do not exhibit the same behavior in PS move games.

Any help would be appreciated.

**Comment by cboulay** [comment]
Please post this in the psmoveservice google group.
https://groups.google.com/forum/#!forum/psmoveservice
