### ISSUE TITLE
Not working with OSVR

### ISSUE THREAD

**Issue by TheUberMedic** [cboulay/PSMoveService#285]
Currently, I'm using 2 PS Move controllers and 4 PS eye cameras with the latest release of PS Move Service. So whenever I try to load up SteamVR, it only detects my HDK. Yet if I disconnect my HDK and make steam boot without a headset, the controllers are detected. I've tried setting my steamvr.vrsettings to read-only so the HDK doesn't change it (cause I noticed it was doing that) but it still doesn't do anything (file doesn't change though)

**Comment by cronybox** [comment]
what a coincidence! I succeeded a few days ago in conditions similar to yours.
I think you have saturated USB bandwidth. As a result, SteamVR is not aware of HMD and PSMove at the same time. In my case it was.
After you move the PS3eye to a different USB port, make sure it works with Camera Test and run StemaVR.
See link video. PSMoveSevice test starts at 8:00.
Https://youtu.be/caGbTzA2pcs
I think that it would be much better to have an additional PCI-E to USB 3.0 PCI Express Card, so I have placed an order.

**Comment by TheUberMedic** [comment]
Wait, where you the same guy from reddit? xD
Anyway, I'll order a PCI-E to USB 3 card then and try it out then.

**Comment by HipsterSloth** [comment]
For general trouble shooting questions can't you post to the PSMoveService forums first:
https://groups.google.com/forum/#!forum/psmoveservice

You're likely to get more help there from more people.

Closing this issue for tracking purposes. I'll re-open if after troubleshooting on the psmoveservice forums we determine that there is a bug here that needs a tracking issue.
