### ISSUE TITLE
Controllers shaking, getting disoriented

### ISSUE THREAD

**Issue by k3nnny** [cboulay/PSMoveService#289]
Hello fellow vr maniacs!

I made a 3 camera + 3 controller setup with riftcat. Calibrations are done and everything looks good in the "white blank room". Even in the lab for a while but after that the controllers getting lost (shaking, going out of screen) even after pressing select start just getting worst and not synced to the headset. Im using the 3rd controller as a headtrack (freepie stuff)
My question is:
Is it a common bug or Im just stupid or missing something? I do all the callibrations (all 3 controllers) in the same way (callib. mat) also tried different camera positions. Is it matter if 1 of 3 cameras cant detect a controller or all of them should see the same thing?
This is my camera setup:
http://imgur.com/E6a9vdB
SteamVR config:
http://pastebin.com/cihh60ui

Also any recommended camera position?

Using the latest PS move service, latest riftcat

**Comment by cboulay** [comment]
Can you confirm this happens in the config tool too, or is it just in SteamVR? Or just in games? If it doesn't happen in the configtool then I'd like you to close this issue and instead post on the google group/forum. There are more people there to help with this kind of steamvr/game troubleshooting. 
https://groups.google.com/forum/#!forum/psmoveservice

**Comment by k3nnny** [comment]
Okay some correction. I just rearanged the cameras and looks better now but the controllers still going out of sync with the headtrack.
EVEN if I use riftcan phone gyro only , after turning my head the controllers getting further from me.
In the configtool looks goob but I only can see 1 controller in the time.
I think there is something with the sync cuz if I move my head a bit its good (freepie) but the controllers in hand stays and getting far from them.
Is it a ps service related? A video wwould be more useful?

**Comment by HipsterSloth** [comment]
I'm going through and closing all troubleshooting related e-mail for tracking purposes, but feel free discussion here.

Also yet a video would be really helpful for understanding what is going on here.
