### ISSUE TITLE
PSmoveService close 2 sec afterstart up

### ISSUE THREAD

**Issue by joostvbh** [cboulay/PSMoveService#302]
[2016-12-01 19:57:32.822]: main - Starting PSMoveService
Config file name: "C:\Users\joost\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
Config file name: "C:\Users\joost\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
[2016-12-01 19:57:32.827]: bluetooth_get_host_address - Failed to find a bluetooth radio
Config file name: "C:\Users\joost\AppData\Roaming\PSMoveService\TrackerManagerConfig.json"
Config file name: "C:\Users\joost\AppData\Roaming\PSMoveService\TrackerManagerConfig.json"
[2016-12-01 19:57:32.913]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\12\0, camera_index=0)
libusb: error [init_device] device '\\.\USB#VID_046D&PID_C07D&MI_01#6&1F1DF120&0&0001' is no longer connected!
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [winusbx_open] could not open device \\.\USB#VID_1415&PID_2000&MI_01#6&262A50A&0&0001#{91318542-C820-4FBF-B7DD-0FAADFF473CA} (interface 1): [5] Toegang geweigerd.
ps3eye::PS3EYECam::getDevices() found 0 devices.
[2016-12-01 19:57:32.928]: PS3EyeTracker::open - Failed to open PS3EyeTracker(USB\VID_1415&PID_2000\12\0, camera_index=0)
[2016-12-01 19:57:32.930]: DeviceTypeManager::update_connected_devices - Device device_id 0 (USB\VID_1415&PID_2000\12\0) failed to open!
[2016-12-01 19:57:37.32]: ClientConnection::start - Starting client connection id 0
[2016-12-01 19:57:37.34]: ClientConnection::send_connection_info - Sending connection id to client 0

and it shutdown after 2 sec the service can you look how to fix it

**Comment by HipsterSloth** [comment]
It looks like psmove service can't open the ps3eye camera?

libusb: error [winusbx_open] could not open device \.\USB#VID_1415&PID_2000&MI_01#6&262A50A&0&0001#{91318542-C820-4FBF-B7DD-0FAADFF473CA} (interface 1): [5] Toegang geweigerd.

Have you already assigned the libusb driver to it?
https://github.com/cboulay/PSMoveService/wiki/PSEye-Software-Setup-%28Windows%29#installing-the-libusb-drivers

Also for general trouble shooting questions can't you post to the PSMoveService forums first:
https://groups.google.com/forum/#!forum/psmoveservice

You're likely to get more help there from more people.

Closing this issue for tracking purposes. I'll re-open if after troubleshooting on the psmoveservice forums we determine that there is a bug here that needs a tracking issue.

**Comment by joostvbh** [comment]
i did
