### ISSUE TITLE
Positional Tracking for PC HMD without camera (Deepoon and Pimax)

### ISSUE THREAD

**Issue by vrman66** [cboulay/PSMoveService#305]
Please, how use PsMoveService for Postional Tracking with HMD like Deepoon or Pimax (without camera).
I read wiki and see that Ps Move used only for vive controllers, but not as Positional Tracking Camera.
3rd Ps Move used only with PS Move FreePie Bridge but Vridge translate PS Move data to SteamVR, not PS Move Service.
All video and tutorial about 3 PS Move not work!! its only for Cardboard Users.
Please Help!!!

**Comment by DummiesBelow** [comment]
You seem very confused. It is impossible to get positional tracking without a camera. It is also impossible to use a PS Move controller for positional tracking without a camera.

**Comment by cboulay** [comment]
Just to be a pedant... there are magnetic position tracking systems that don't use cameras (e.g., Polhemus, Razer Hydra). But I'm pretty sure that's not the topic of this post.

@vrman66 , this isn't the appropriate forum for this type of message. Please try the google group first: https://groups.google.com/forum/#!forum/psmoveservice
