### ISSUE TITLE
Please!!! Add support 3rd PS Move for emulation Positional Tracking in Steam VR

### ISSUE THREAD

**Issue by vrman66** [cboulay/PSMoveService#306]
Many people used chinese PC HMD: Deepoon E2 and Pimax P1, that have only rotation tracking (like DK1).
Cardbord users use 3rd PS Move with Riftcat Vridge over PSmovefreepiebridge. 
I was confused wiki info  Step 4a: Coregistration with HMD and image "Attaching the PSMove to your HMD". I thought it was something that I needed, but not.
You close these topics, but they will occur again. Maybe you just add emulation positional tracking and many hundread (and maybe tausend) people will be grateful.
PSMoveService don't need for Oculus CV1 users (i have CV1 too and i just buy Oculus Touch). For DK2 users its also give limits (no 360 tracking). And with 4 PS eye and 3 PS move peoples may use cheap RoomScale!
Sorry for my bad English!

**Comment by cboulay** [comment]
I didn't understand what you wanted before, but I sort of do now.
You want a way to use positional tracking for headsets that aren't using Riftcat, and for ones that don't already have their own position estimation system.

We're not going to support every headset that comes on the market. You're going to have to find a 3rd party software solution. If a solution doesn't exist, then you should ask for advice on the google forum.

Please don't post an issue about this again unless you can point to a specific issue with PSMoveService that needs modification so such a 3rd party solution can work.
