### ISSUE TITLE
Controllers attached when tracking in steamvr

### ISSUE THREAD

**Issue by SeeSJay** [cboulay/PSMoveService#307]
Ive got two PSeye cameras tracking two controllers but once I launch SteamVR only one is usable whilst the other is attached by the bulb, I am able to control the orientation of the other controller but obviously not the position since its attached 
![2016-12-06-pm_05_34_18-layer](https://cloud.githubusercontent.com/assets/24415719/20936372/484e7bec-bbda-11e6-8d65-78a9e901ac61.png)

**Comment by cboulay** [comment]
I'm guessing they are both being tracked by the same color filter. Try doing the tracker color calibration again and picking different colors that are more different from each other. (What looks more different to our eyes might not be more different to an HSV filter, so try a couple)

**Comment by SeeSJay** [comment]
yeh thanks it was the exactly that, works really well and a hell of a lot cheaper than the vive
