### ISSUE TITLE
Update wiki to reflect change in HMD coregistration.

### ISSUE THREAD

**Issue by Jako81624** [cboulay/PSMoveService#308]
Not sure if intentional but I do not get the option of using a calibration mat or HMD in the latest release when setting up the tracking.  Single camera and HMD plugged in and registered with both Oculus and SteamVR

**Comment by cboulay** [comment]
That's expected. The docs are out of date.

**Comment by HipsterSloth** [comment]
Yeah, sorry about that. A while ago I ripped out the HMD coregistration in the config tool. Now you align the controller with your HMD on after you launch steamVR. I added this note below the tutorial video in the wiki, but I just need to update the SteamVR doc section. I'll do that when I put out the next release this weekend.

"NOTE The HMD calibration alignment info in this video is out of date. You no longer place the HMD on the calibration mat in the final stage of the camera pose tool. Instead you now are prompted in the SteamVR compositor with this overlay asking you to hold the controller to your face and then press start+select. This will align the HMD and PSMove tracking spaces (hopefully)."

**Comment by cboulay** [comment]
Oh, I guess the docs had been updated. @Jako81624 , were you following some instructions somewhere or were you going from memory? If you were following instructions then please let us know so we can update them or ask for them to be updated.

**Comment by Jako81624** [comment]
@cboulay No worries, I followed the wiki for this repo but I've since found the best way is to emulate the original mat with rough estimates then line it up in Steam VR like @HipsterSloth said.  Adding a secondary camera tomorrow to test the accuracy.  Next thing is to open a feature and maybe see about implementing turning like the latest update to SteamVR allows Oculus Touch users to do since the tracking for older headsets and the remotes is limited to line of site which make rotation a little difficult :P

**Comment by Jako81624** [comment]
Accidental close, wrong button press

**Comment by HipsterSloth** [comment]
I updated the wiki page describing the latest tracker calibration procedure: https://github.com/cboulay/PSMoveService/wiki/Tracker-Pose-Calibration

I also added a link to a new setup tutorial video: 
https://www.youtube.com/watch?v=QEraN1r_5Nw
