### ISSUE TITLE
PS Move button mapping - save a place in Google Earth VR

### ISSUE THREAD

**Issue by Frogburt** [cboulay/PSMoveService#311]
Hi, has anyone worked out how to map PS Move buttons such that a location can be saved in Google Earth VR? This is a comment from a Google dev on how it is supposed to work (I assume the star icon button is also referred to as a menu button, but I am unsure about this):
Are you using the button above the touchpad on the secondary controller (with a star icon). If you are using the star button and a "Place saved" notification comes up, there should now be a new JPEG in the "Google Earth VR" in Pictures. EDIT1: I use this mapping  "triangle" : "application_menu" but when I press triangle (on either controller) I get the SteamVR dashboard. EDIT2, I use this product to allow PSVR to run SteamVR apps (and do recommend it highly) http://www.trinusvirtualreality.com/psvr/

**Comment by wisockijunior** [comment]
how can you run GoogleEarthVR on riftcat vridge? it keep saying it only
works on HTC Vive?

Att
Renato Wisocki Junior
renato@wisockijunior.com.br


2016-12-11 10:04 GMT-02:00 Frogburt <notifications@github.com>:

**Comment by zelmon64** [comment]
@Frogburt First off this sort of question should really be asked on [the google group](https://groups.google.com/forum/#!forum/psmoveservice). That being said, the button you want is the one that says "START" on the physical PSMove controller that is linked to the virtual controller with the globe on it.

@wisockijunior The easiest way I found to get GoogleEarthVR to run is to place the dll supplied by [FakeVive ](https://github.com/Shockfire/FakeVive) in the same folder as the game's exe file.

**Comment by Frogburt** [comment]
Thanks zelmon64, somehow I hadn't come across the wealth of info on the link you provided. I completed the Google Earth VR tutorial and it started working. I don't think I am doing anything different but it's fine now.
