### ISSUE TITLE
Controller orientation issue

### ISSUE THREAD

**Issue by TheUberMedic** [cboulay/PSMoveService#314]
For one of my controllers in Steam, the orientation goes completely weird. It seems to favour thinking it's on its side when it's upright.

**Comment by cboulay** [comment]
Kudos for correctly using its and it's several times in a row, and for using the correct spelling of favour.

Can you confirm that the orientation looks reasonable in the config tool? If not, try redoing the calibration away from any devices that might be affecting the magnetic field.

**Comment by TheUberMedic** [comment]
In the config tool, it tracks the orientation of the controller fine. It knows up from down. The problem only occurs in Steam. It caused me to be handicapped in Space Pirate Trainer! xD

**Comment by wisockijunior** [comment]
I also have this problem, trying to solve it several days with no sucess. I have 5 psMoveControllers and it is really a bug

**Comment by HipsterSloth** [comment]
@TheUberMedic @wisockijunior Would you guys mind seeing if this is still an issue in the latest release: https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha6.0.8

**Comment by TheUberMedic** [comment]
I haven't noticed it as heavily after the latest update so that's pretty :D
Was pretty nice to use in Space Pirate Trainer :3
