### ISSUE TITLE
Cheap BT adapter

### ISSUE THREAD

**Issue by kswiorek** [cboulay/PSMoveService#315]
You can buy BTD-401 on aliexpress it costs 2$ and it works for me

https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20161222232305&SearchText=BTD-401

(github should add comments so request wouldn't be put in issues)

**Comment by cboulay** [comment]
@kswiorek That's why we have the forums: https://groups.google.com/forum/#!forum/psmoveservice
