### ISSUE TITLE
[Windows] Can't connect controllers

### ISSUE THREAD

**Issue by DJVibezzz** [cboulay/PSMoveService#316]
If i connect the controller using the usb cable i can't connect it. The light at the bottom of the controller is flashing and in the config it says.    No bluetooth adapter detected!, no bluetoioth connected controllers and no usb connected controllers. The cams and hmd does work but the controllers not

**Comment by POEDaley** [comment]
What bluetooth adapter are you using?

**Comment by cboulay** [comment]
@POEDaley is right. Until we can determine that this is a code-related problem then you're more likely to get help in the google group.
P.S. You should only PAIR the controller when the USB is plugged in. After that you should disconnect the USB cable. A flashing light, depending on speed, just means that the controller is charging. But the log saying "No bluetooth adapter detected" is a bad sign. If you are using drivers supplied with your bluetooth dongle then try uninstalling those drivers and letting Windows handle your bluetooth adapter.

I'm closing this issue for tracking. If you want further help then you should really post in the google group first.
