### ISSUE TITLE
2 move remotes = steam controller 

### ISSUE THREAD

**Issue by Prestoned** [cboulay/PSMoveService#318]
Is this a new bug or what? I connect and pair a OK with either controller showing up as a MOVE then I connect 2 and controller #0 is jointed to #1. When I launch steamVR it shows that I have a STEAM VR controller o.O. Testing in PS config shows them joined to #1 while #0 can move freely around #1.

**Comment by Prestoned** [comment]
[Solved] Windows decided to revert one of my cameras to WinUsb reinstalled Libusb

**Comment by Prestoned** [comment]
HMD seems to be breaking and using controller #1

**Comment by lfmerrill** [comment]
Please learn English maybe that will help with your problems

**Comment by HipsterSloth** [comment]
https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha6.0.8
