### ISSUE TITLE
PSMoveService Stop Working.

### ISSUE THREAD

**Issue by Alehandoro** [cboulay/PSMoveService#319]
I have a problem with PSMoveService. Every time I'm playing, randomly and without coming to a clear conclusion, PSMoveService stops working. 

I have a configuration with 2 PS3 Eye (or even with 3 also gives me the error) and suddenly, a controller stops functioning by turning off the ball (the connection LED is still active) or directly the two stop working (keeping the LEDs on Connection).

The error that gives me is the following:

http://imgur.com/wD3oOWz

And this is the log of vrserver:

Thu Dec 29 2016 12:11:57.915 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection active. Shutting down...
Thu Dec 29 2016 12:11:57.915 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection stopped.
Thu Dec 29 2016 12:11:57.915 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Dec 29 2016 12:11:57.915 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Dec 29 2016 12:11:58.927 - psmove: CServerDriver_PSMoveService::HandleFailedToConnectToPSMoveService - Called
Thu Dec 29 2016 12:11:58.927 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - called.
Thu Dec 29 2016 12:11:58.927 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection active. Shutting down...
Thu Dec 29 2016 12:11:58.927 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection stopped.
Thu Dec 29 2016 12:11:58.927 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Dec 29 2016 12:11:58.927 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Dec 29 2016 12:11:59.941 - psmove: CServerDriver_PSMoveService::HandleFailedToConnectToPSMoveService - Called
Thu Dec 29 2016 12:11:59.941 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - called.
Thu Dec 29 2016 12:11:59.941 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection active. Shutting down...
Thu Dec 29 2016 12:11:59.941 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection stopped.
Thu Dec 29 2016 12:11:59.941 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Dec 29 2016 12:11:59.941 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Dec 29 2016 12:12:00.956 - psmove: CServerDriver_PSMoveService::HandleFailedToConnectToPSMoveService - Called
Thu Dec 29 2016 12:12:00.956 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - called.
Thu Dec 29 2016 12:12:00.956 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection active. Shutting down...
Thu Dec 29 2016 12:12:00.956 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection stopped.
Thu Dec 29 2016 12:12:00.956 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Dec 29 2016 12:12:00.956 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Dec 29 2016 12:12:01.972 - psmove: CServerDriver_PSMoveService::HandleFailedToConnectToPSMoveService - Called
Thu Dec 29 2016 12:12:01.972 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - called.
Thu Dec 29 2016 12:12:01.972 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection active. Shutting down...
Thu Dec 29 2016 12:12:01.972 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection stopped.
Thu Dec 29 2016 12:12:01.972 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Dec 29 2016 12:12:01.972 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Dec 29 2016 12:12:02.984 - psmove: CServerDriver_PSMoveService::HandleFailedToConnectToPSMoveService - Called
Thu Dec 29 2016 12:12:02.984 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - called.
Thu Dec 29 2016 12:12:02.984 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection active. Shutting down...
Thu Dec 29 2016 12:12:02.984 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection stopped.
Thu Dec 29 2016 12:12:02.984 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Dec 29 2016 12:12:02.985 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Dec 29 2016 12:12:03.998 - psmove: CServerDriver_PSMoveService::HandleFailedToConnectToPSMoveService - Called
Thu Dec 29 2016 12:12:03.998 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - called.
Thu Dec 29 2016 12:12:03.998 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection active. Shutting down...
Thu Dec 29 2016 12:12:03.998 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection stopped.
Thu Dec 29 2016 12:12:03.998 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Dec 29 2016 12:12:03.998 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Dec 29 2016 12:12:05.013 - psmove: CServerDriver_PSMoveService::HandleFailedToConnectToPSMoveService - Called
Thu Dec 29 2016 12:12:05.013 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - called.
Thu Dec 29 2016 12:12:05.013 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection active. Shutting down...
Thu Dec 29 2016 12:12:05.013 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection stopped.
Thu Dec 29 2016 12:12:05.013 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Dec 29 2016 12:12:05.013 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Dec 29 2016 12:12:06.025 - psmove: CServerDriver_PSMoveService::HandleFailedToConnectToPSMoveService - Called
Thu Dec 29 2016 12:12:06.025 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - called.
Thu Dec 29 2016 12:12:06.025 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection active. Shutting down...
Thu Dec 29 2016 12:12:06.025 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection stopped.
Thu Dec 29 2016 12:12:06.025 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Dec 29 2016 12:12:06.025 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Dec 29 2016 12:12:07.013 - Process vrmonitor (5920) has initiated a quit all
Thu Dec 29 2016 12:12:07.023 - Sending Quit event to process monitor_psmove (780)
Thu Dec 29 2016 12:12:07.023 - Sending Quit event to process vrdashboard (4472)
Thu Dec 29 2016 12:12:07.037 - psmove: CServerDriver_PSMoveService::HandleFailedToConnectToPSMoveService - Called
Thu Dec 29 2016 12:12:07.037 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - called.
Thu Dec 29 2016 12:12:07.037 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection active. Shutting down...
Thu Dec 29 2016 12:12:07.037 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection stopped.
Thu Dec 29 2016 12:12:07.037 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Dec 29 2016 12:12:07.038 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Dec 29 2016 12:12:07.053 - IPCPipe(monitor_psmove (780)): Process disconnected.
Thu Dec 29 2016 12:12:07.053 - Process monitor_psmove (780) disconnected
Thu Dec 29 2016 12:12:07.053 - 0 - leaving standby
Thu Dec 29 2016 12:12:08.052 - psmove: CServerDriver_PSMoveService::HandleFailedToConnectToPSMoveService - Called
Thu Dec 29 2016 12:12:08.052 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - called.
Thu Dec 29 2016 12:12:08.052 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection active. Shutting down...
Thu Dec 29 2016 12:12:08.052 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection stopped.
Thu Dec 29 2016 12:12:08.052 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Dec 29 2016 12:12:08.052 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Dec 29 2016 12:12:09.062 - psmove: CServerDriver_PSMoveService::HandleFailedToConnectToPSMoveService - Called
Thu Dec 29 2016 12:12:09.062 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - called.
Thu Dec 29 2016 12:12:09.062 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection active. Shutting down...
Thu Dec 29 2016 12:12:09.062 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection stopped.
Thu Dec 29 2016 12:12:09.062 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Dec 29 2016 12:12:09.063 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Dec 29 2016 12:12:09.230 - IPCPipe(vrdashboard (4472)): Process disconnected.
Thu Dec 29 2016 12:12:09.230 - Process vrdashboard (4472) disconnected
Thu Dec 29 2016 12:12:09.238 - Sending Quit event to process vrcompositor (7948)
Thu Dec 29 2016 12:12:09.238 - Sending Quit event to process vrmonitor (5920)
Thu Dec 29 2016 12:12:09.253 - IPCPipe(vrmonitor (5920)): Process disconnected.
Thu Dec 29 2016 12:12:09.253 - Process vrmonitor (5920) disconnected
Thu Dec 29 2016 12:12:09.399 - IPCPipe(vrcompositor (7948)): Process disconnected.
Thu Dec 29 2016 12:12:09.399 - Process vrcompositor (7948) disconnected
Thu Dec 29 2016 12:12:09.403 - VR server shutting down
Thu Dec 29 2016 12:12:09.403 - psmove: CPSMoveControllerLatest::Deactivate - Controller stream stopped
Thu Dec 29 2016 12:12:09.403 - psmove: CPSMoveControllerLatest::Deactivate - Controller stream stopped
Thu Dec 29 2016 12:12:09.406 - Listener thread ending
Thu Dec 29 2016 12:12:09.406 - psmove: CServerDriver_PSMoveService::Cleanup - Shutting down connection...
Thu Dec 29 2016 12:12:09.408 - psmove: CServerDriver_PSMoveService::Cleanup - Shutdown complete

**Comment by HipsterSloth** [comment]
This sounds like an issue with with USB bandwidth saturation. You probably have the bluetooth adapter on the same usb root hub as your web cameras. Try moving the the bluetooth adapter to a different usb port.

I'm going to close this issue for tracking purposes. If the problem persists, post an issue on the psmoveservice forum: https://groups.google.com/forum/#!forum/psmoveservice. If we can pinpoint this disconnection as an actual code issue that needs to be fixed (as compared to a USB bandwidth issue), then we can open a new issue for it here.
