### ISSUE TITLE
Controllers jittering through room while HMD (also PSMove) tracks smoothly

### ISSUE THREAD

**Issue by Christanoid** [cboulay/PSMoveService#320]
When playing SteamVR games my PSMove Controllers keep jittering around a lot. The thing that confuses me is that my HMD (made of a PSMove Controller lighting green and the PSMoveBridge) tracks just perfectly fine. The hands however (Magenta and Cyan) can't keep still, spin around and jitter around a lot. I can do nothing with the Controllers refusing to track that much :(
My cameras are setup in a 4 camera in the corners setup and I calibrated the tracking colors for all the controllers in the Colors they light up very precisely. The one I had most struggle with was actually the green one which is the only one not jittering.

I don't have a log because the Service shows no bug or anything.

**Comment by POEDaley** [comment]
Are you using ROI?  If you are, there is a bug in 6.0.6.  There is a test version of 6.0.7 available on the google groups that really solved it for me.  You should try it from there.  Also, you will probably end up getting more luck posting any troubleshooting issues on the google groups as well.  Also, lots of discussion there that my be related.

https://groups.google.com/forum/#!forum/psmoveservice

**Comment by Christanoid** [comment]
@POEDaley I looked into my config and ROI is disabled, so that's not the problem. Yet I will look into the preview later today, maybe it does help.

**Comment by Christanoid** [comment]
Closing this issue by saying that for somewhat reason something in the background apparently had the same color as the bulb. Seems like that confused the tracker. Anyways after recalibrating the colors the controllers are now perfectly stable
