### ISSUE TITLE
Connecting three trackers makes stream extremely slow

### ISSUE THREAD

**Issue by KeyTry** [cboulay/PSMoveService#321]
The service and configuration utility works well with two controllers. However, using three controllers (And I assume more), seems to make the stream extremely slow. In some cases, the config tool gets stuck at "Connecting to PSMove Service". I wonder if this is the case of my computer, since I have a rather modest PC.

**Comment by KeyTry** [comment]
**Update:** This seems to happen at random! I managed to get three trackers smoothly connected at some point. However, when I changed the USB position, it went back to working slowly.

**Comment by cboulay** [comment]
This is a well-known issue. It's in the wiki but it might be a bit hard to find. See number 2 [here](https://github.com/cboulay/PSMoveService/wiki/Frequently-Asked-Questions#multicam).

**Comment by KeyTry** [comment]
> This is a well-known issue. It's in the wiki but it might be a bit hard to find. See number 2 here.

Thanks for the reply. I did some shuffling around and managed to get it working.
