### ISSUE TITLE
Oculus DK2 not working with PS move service

### ISSUE THREAD

**Issue by SUMITOVER** [cboulay/PSMoveService#323]
Hi,

I am new to this but somehow i manage to setup my PS Move controllers with STEAMVR.
but when i run psmoveconfig.exe it says HMD not found.
when i start steamvr keeping my dk2 on, it dont detect my ps move controllers and when i turn it off my dk2 then steamvr detects both controllers and pseye camera as well

also i want to know for now i am using only one PS eye camera and one oculus dk2 camera, in spare i have few more dk2 cameras as well can i use them to improve controllers tracking ??

Thanks in advance.

**Comment by cboulay** [comment]
>i have few more dk2 cameras as well can i use them to improve controllers tracking

No. The DK2 cameras have visible light filters on them and only (mostly) pick up infrared. The PSEye cameras have an infrared filter on them and only pick up visible light.

I haven't tried a DK2 with PSMoveService in SteamVR but I'm sure others have. Try the forums, where these kinds of questions should go first:
https://groups.google.com/forum/#!forum/psmoveservice

**Comment by SUMITOVER** [comment]
bro

thanks a ton for your reply, i tried that group but got no luck with it
Also i tried the setup with riftcat as well using my note4 but everything was same with that hmd as well
steamvr is detecting either my hmd or move controllers only  and with psmove service its not recognizing any of my HMD.
i have multiple drivers enable in steamvr settings file
dont understand what am i missing ??


please help...!!

**Comment by cboulay** [comment]
The forums have people that use rifcat, DK2, note4, etc. HipsterSloth and I read every one of those posts and answer them if we can, but the community has been pretty good about it too. If you want help from the community then provide more information and be clear about what you attempted and what failed. The more detail the better. Screenshots are good. Videos are good. Saying "It didn't work" is not good.

But I think you can find an answer in the [Wiki](https://github.com/cboulay/PSMoveService/wiki#initial-setup-video). Note that there's a new video there. 

If you want help from anyone in the GitHub issues then you're going to need to provide log files and preferably point us to the section of code that you determined to be problematic using your debugger. This is a application development bug report system, not a help desk.
