### ISSUE TITLE
Ps Move controller orientation is backwards.

### ISSUE THREAD

**Issue by kapelow** [cboulay/PSMoveService#337]
Similar to #137 but in my case i use TrinusVR and don't have positional tracking for HMD. One of my controllers turn bulb off after minute and other one is backwards and X, Y movement is inverted. What to do?

**Comment by cboulay** [comment]
Is this happening in the PSMoveService config tool or in game only?
Can you copy + paste your logs?
Do you mean X and Y are swapped (horizontal movements of the controller cause vertical movements of the virtual object) or do you mean both are inverted (rightward is represented as leftward, up is represented as down)?

**Comment by kapelow** [comment]
SteamVR only, both are inverted. Log:
[PSMoveService.txt](https://github.com/cboulay/PSMoveService/files/706685/PSMoveService.txt)

**Comment by kapelow** [comment]
PS: movement is inverted after first controllers turn his bulb off

**Comment by kapelow** [comment]
And i have 2 of 4 cameras upside-down (2 upside down, 1 in right position and 1 disconnected)

**Comment by cboulay** [comment]
Sorry I didn't reply right away. If it's happening in SteamVR only then you're better off asking for advice in the forums. There are people there that have all sorts of multi-cam setups.
