### ISSUE TITLE
Center drift from 12:00 o'clock to 10-11 o'clock using steam VR with OSVR HMD 2.0 

### ISSUE THREAD

**Issue by AKA-TiTAN** [cboulay/PSMoveService#342]
Hi,
I am having issues with centre drift with the PS Move service with OSVR HMD 2.0. the steam VR service centring drifts from 12 o'clock to between 10 and 11 o'clock within 5 mins of use.  i am unsure if it is related to the HMD or the PSmove service, as it only occurs when both are in use. also the HMD 2.0 has small magnets on the front of the HMD, so would this not interfere with the move controllers when raising them to the HMD and calibrate/centering them?

**Comment by HipsterSloth** [comment]
Closing this issue since it's so old and is technically a support request. If this is still a problem, please post a troubleshooting request in the google group:

https://groups.google.com/forum/#!forum/psmoveservice
