### ISSUE TITLE
Error with libusb? 

### ISSUE THREAD

**Issue by kapelow** [cboulay/PSMoveService#343]
Error code: libusb: error [windows_transfer_callback] detected I/O error 2: [2] Nie mo┐na odnalečŠ okreťlonego pliku.

**Comment by HipsterSloth** [comment]
Are your cameras able to open ok in the config tool? I have debug logs enabled in libusb so we get a lot of errors back from libusb that are non-issues. Sometimes there are intermittent usb io transfer issues.
