### ISSUE TITLE
Camera upside down

### ISSUE THREAD

**Issue by Lebrero** [cboulay/PSMoveService#345]
Hi, 
i want to place the cameras  upside down because his foot is made of metal and i want to use a neodymium magnet to remove and put it.

Can someone tell me where is, in the code , to do this?

Thanks

**Comment by HipsterSloth** [comment]
You should be able to mount the cameras upside down and it should just work. So long at the camera can see all 5 points of the calibration mat the calibration tool should be able to correctly compute the transform of the camera. I could point you to the code where we could flip the image, but I'm pretty sure you don't actually want to do that.

**Comment by POEDaley** [comment]
I have tried this myself and it worked just fine without modifying anything.

**Comment by Lebrero** [comment]
Thanks!!
