### ISSUE TITLE
Camera long delay when testing PS eye cameras

### ISSUE THREAD

**Issue by XxAirWalker26xX** [cboulay/PSMoveService#346]
I have along delay with the cameras refreshing slowly. Is it just me or anyone else. Using a 3.0 usb hub with multiple extension with 4 cameras. I also have a beefy pc and should be fine about that. Oh btw im also running the newest release.

**Comment by cboulay** [comment]
It doesn't matter if you're using usb 3.0, the cameras are 2.0 only. A single USB root cannot handle 4 cameras. You have to spread them out. There are many many posts about this in the psmoveservice forums, and there's info about this in the wiki.
