### ISSUE TITLE
Third Controller as Head Track with a DK2

### ISSUE THREAD

**Issue by Imgonnawork** [cboulay/PSMoveService#351]
Hi, do you think it is possible to use the FreePIE bridge to use the positional tracking plugin with a DK2 ? I would turn off the DK2 pos. tracking camera and use a third controller attached to the HMD.

I red a bit about the freepie and everything should be the same without riftcat but I should find a way to tell to steamvr to use the positional tracking from the psmove controller because that's done by the riftcat program.

If that's not possible at all or it requires a lot of work, could you suggest me a program that can achieve the same riftcat do but using an iphone ?

EDIT:
By the way I would like to achieve this to be able to enjoy a (more) 360 experience while using the amazing DK2 screen.

Thank you for your help, time and amazing work!

**Comment by cboulay** [comment]
Your best bet for questions like this is to ask in the google group first. If, after discussion there, it is determined that some code needs to change in PSMoveService then you can come back here and open a new more specific issue.

https://groups.google.com/forum/#!forum/psmoveservice
