### ISSUE TITLE
VR Server crash with "activateMultipleDrivers" : true

### ISSUE THREAD

**Issue by hoquillo** [cboulay/PSMoveService#354]
First, I want to thank the team of PSMoveService for all his efforts making such a great application.
That said, I can't get mine to work xD.

I've got 1 tracking camera + 2 PS Moves + Deepoon E2 as HMD

Having the Deepoon properly installed with SteamVR compatible drivers (and of course making sure that it works), it's time for the PS Moves to do so.
Again, everything was perfect, exactly as de Wiki describes. Such a great manual, btw ;P
But when I start SteamVR, it crashes with VRServer.exe has stopped working.
2 entire days making my own researchs finaly drives me to the ''causer'' of this: "activateMultipleDrivers" : true. Every time I add that line to steamvr.vrsettings it gets exactly the same error, but without it the PS Moves doesn't turn on. I already have tested lots of different configurations, but it's always the same.

What can I do? I'll happily provide anything you need to know: logs, screenshots, etc.

Thanks in advice, and of course, sorry for my english.

**Comment by HipsterSloth** [comment]
You need that "activateMultipleDrivers" flag in order for the PSMove driver to get loaded. It sounds like something is crashing inside the PSMove steamvr plugin. Could you do the following:

1) On the steamvr status panel select "Create System Report", save the report to a text file and attach it to this issue
2) Look in your C:\Program Files (x86)\Steam\dumps folder for a vrserver dmp files. Attach the latest dump file here as well.

**Comment by hoquillo** [comment]
What a quick answer! I really appreciate it.
Ok:
I can't create a system report. It just keeps loading with ''Detecting USB''.
Neither attach my last dump here (and I made a .ZIP with it). So, I uploaded it here: http://ge.tt/2iRcedi2
Also, this is what I used at this case:
{
   "steamvr" : {
      "activateMultipleDrivers" : true,
      "mirrorViewGeometry" : "0 0 540 960"
   }
}

**Comment by HipsterSloth** [comment]
It appears that the crash is within driver_deepon.dll

Dump Summary
------------
Dump File:	crash_vrserver.exe_20170202192003_1.dmp : Last Write Time:	2/2/2017 10:20:03 AM
Process Name:	vrserver.exe : D:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64\vrserver.exe
Process Architecture:	x64
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

![image](https://cloud.githubusercontent.com/assets/16793853/22563174/5cb633c2-e934-11e6-94c9-c54c2807c583.png)

You can also get at the vrserver log file in `C:\Program Files (x86)\Steam\logs`. If you could attach vrserver.txt here I can see if there is anything helpful in the log.

**Comment by hoquillo** [comment]
Of course. I always look there, but I don't know how to read it properly.
Here it is:

Thu Feb 02 2017 19:21:48.842 - ================================================================================================
Thu Feb 02 2017 19:21:48.842 - ================================================================================================
Thu Feb 02 2017 19:21:48.844 - VR server (v0) starting up with config=D:\Program Files (x86)\Steam\config
Thu Feb 02 2017 19:21:48.844 - [Settings] Load Default Json Settings from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\settings\default.vrsettings
Thu Feb 02 2017 19:21:48.844 - [Settings] Load Default Json Settings from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\resources\settings\default.vrsettings
Thu Feb 02 2017 19:21:48.844 - [Settings] Load Default Json Settings from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\null\resources\settings\default.vrsettings
Thu Feb 02 2017 19:21:48.844 - [Settings] Load Json Settings from D:\Program Files (x86)\Steam\config\steamvr.vrsettings
Thu Feb 02 2017 19:21:48.844 - [DriverManager] Create new Resource Driver Manager
Thu Feb 02 2017 19:21:48.844 - New Connect message from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win32\vrcompositor.exe (VRApplication_Background) (Args: ) 8412 
Thu Feb 02 2017 19:21:48.844 - Creating builtin app for D:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win32\vrcompositor.exe (VRApplication_Background)
Thu Feb 02 2017 19:21:48.844 - Setting app system.generated.vrcompositor.exe PID to 8412
Thu Feb 02 2017 19:21:48.844 - deepoon: Entered DpnServerDriver::Init().
Thu Feb 02 2017 19:21:48.844 - deepoon: DpnServerDriver::GetTrackedDeviceCount() returns Device Count: 1.
Thu Feb 02 2017 19:21:48.844 - deepoon: DpnTrackedDevice::GetStringTrackedDeviceProperty() query property: #1002.
Thu Feb 02 2017 19:21:48.844 - deepoon: DpnTrackedDevice::GetInt32TrackedDeviceProperty() query property: #1029.
Thu Feb 02 2017 19:21:48.844 - deepoon: DpnServerDriver::GetTrackedDeviceCount() returns Device Count: 1.
Thu Feb 02 2017 19:21:48.844 -   driver deepoon implements interfaces IVRSettings_001 ITrackedDeviceServerDriver_004 IVRDisplayComponent_002 IVRDriverDirectModeComponent_001 IVRControllerComponent_001 IVRCameraComponent_001 IServerTrackedDeviceProvider_003 IClientTrackedDeviceProvider_003 
Thu Feb 02 2017 19:21:48.844 - Loaded server driver deepoon (IServerTrackedDeviceProvider_003) from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\deepoon\bin\win64\driver_deepoon.dll
Thu Feb 02 2017 19:21:48.844 - Unable to create property container for device 0
Thu Feb 02 2017 19:21:48.844 - Could not activate pending device DPN68888888: VRInitError_Init_Internal
Thu Feb 02 2017 19:21:48.844 - Driver deepoon has no suitable devices.
Thu Feb 02 2017 19:21:48.844 - Load Json firmware manifest from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\firmware\manifest.vrfirmware
Thu Feb 02 2017 19:21:48.844 - Add Json firmware manifest from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\htc\resources\firmware\manifest.vrfirmware
Thu Feb 02 2017 19:21:48.860 - lighthouse: Attached HID Devices:
Thu Feb 02 2017 19:21:48.860 - lighthouse:     No devices
Thu Feb 02 2017 19:21:48.860 -   driver lighthouse implements interfaces IVRSettings_002 ITrackedDeviceServerDriver_005 IVRDisplayComponent_002 IVRDriverDirectModeComponent_002 IVRControllerComponent_001 IVRCameraComponent_002 IServerTrackedDeviceProvider_004 IVRWatchdogProvider_001 
Thu Feb 02 2017 19:21:48.860 - Loaded server driver lighthouse (IServerTrackedDeviceProvider_004) from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\bin\win64\driver_lighthouse.dll
Thu Feb 02 2017 19:21:48.860 - Driver lighthouse has no suitable devices.
Thu Feb 02 2017 19:21:49.054 - oculus: [CAPI] LibOVR module is located at C:\Program Files\Oculus\Support\oculus-runtime\LibOVRRT64_1.dll
Thu Feb 02 2017 19:21:49.057 - oculus: Connected to the server running version (prod = 1).1.10.2(build = 321138) feature version = 0. Client runs version (prod = 1).1.10.2(build = 321138) feature version = 0
Thu Feb 02 2017 19:21:49.557 - oculus: ovrHmd_Create failed
Thu Feb 02 2017 19:21:49.557 - error VRInitError_Driver_Failed when initing driver oculus from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\oculus\bin\win64\driver_oculus.dll.
Thu Feb 02 2017 19:21:49.557 - Unable to load driver oculus because of error 200. Skipping.
Thu Feb 02 2017 19:21:49.575 - oculus_legacy: ovrHmd_Create failed
Thu Feb 02 2017 19:21:49.575 - oculus_legacy: Failed to initialized Oculus device
Thu Feb 02 2017 19:21:49.575 -   driver oculus_legacy implements interfaces IVRSettings_002 ITrackedDeviceServerDriver_005 IVRDisplayComponent_002 IVRDriverDirectModeComponent_002 IVRControllerComponent_001 IVRCameraComponent_002 IServerTrackedDeviceProvider_004 IVRWatchdogProvider_001 
Thu Feb 02 2017 19:21:49.575 - Loaded server driver oculus_legacy (IServerTrackedDeviceProvider_004) from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\oculus_legacy\bin\win64\driver_oculus_legacy.dll
Thu Feb 02 2017 19:21:49.575 - Driver oculus_legacy has no suitable devices.
Thu Feb 02 2017 19:21:49.579 - psmove: CServerDriver_PSMoveService::Init - Initializing.
Thu Feb 02 2017 19:21:49.579 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - called.
Thu Feb 02 2017 19:21:49.579 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Existing PSMoveService connection NOT active.
Thu Feb 02 2017 19:21:49.579 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Starting PSMoveService connection...
Thu Feb 02 2017 19:21:52.745 - psmove: CServerDriver_PSMoveService::ReconnectToPSMoveService - Successfully connected
Thu Feb 02 2017 19:21:52.746 -   driver psmove implements interfaces IVRSettings_001 ITrackedDeviceServerDriver_004 IVRDisplayComponent_002 IVRDriverDirectModeComponent_001 IVRControllerComponent_001 IVRCameraComponent_002 IServerTrackedDeviceProvider_003 IClientTrackedDeviceProvider_004 
Thu Feb 02 2017 19:21:52.746 - Loaded server driver psmove (IServerTrackedDeviceProvider_003) from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove\bin\win64\driver_psmove.dll
Thu Feb 02 2017 19:21:52.746 - Driver psmove has no suitable devices.
Thu Feb 02 2017 19:21:52.746 - psmove: CServerDriver_PSMoveService::Init - called.
Thu Feb 02 2017 19:21:52.746 - psmove: CServerDriver_PSMoveService::Init - Already Initialized. Ignoring.
Thu Feb 02 2017 19:21:52.746 -   driver psmove implements interfaces IVRSettings_001 ITrackedDeviceServerDriver_004 IVRDisplayComponent_002 IVRDriverDirectModeComponent_001 IVRControllerComponent_001 IVRCameraComponent_002 IServerTrackedDeviceProvider_003 IClientTrackedDeviceProvider_004 
Thu Feb 02 2017 19:21:52.746 - Loaded server driver psmove (IServerTrackedDeviceProvider_003) from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove\bin\win64\driver_psmove.dll
Thu Feb 02 2017 19:21:52.746 - Driver psmove has no suitable devices.
Thu Feb 02 2017 19:21:52.746 - Not loading driver null because it is disabled in settings

**Comment by HipsterSloth** [comment]
I have no experiance with the Deepoon so I can't say what is definitively bad or not, but there are two lines that are interesting to me: 

> Thu Feb 02 2017 19:21:49.557 - oculus: ovrHmd_Create failed
Thu Feb 02 2017 19:21:49.557 - error VRInitError_Driver_Failed when initing driver oculus from D:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\oculus\bin\win64\driver_oculus.dll.

I've heard that the Deepoon API emulates the oculus SDK so maybe this is part of the problem.

> Thu Feb 02 2017 19:21:48.844 - Could not activate pending device DPN68888888: VRInitError_Init_Internal
Thu Feb 02 2017 19:21:48.844 - Driver deepoon has no suitable devices.

There was a new steamvr version that was just released two days ago and made a lot of major changes. It's possible that this causing older drivers to break. Are you using the steamvr beta?

**Comment by hoquillo** [comment]
Just standard SteamVR
Maybe with DK2 Mode? There, teh problem is that I just get a blue/grey screen because the lack of positional tracking.
Anyway, I never tested it with SteamVR Beta. Do you think that can help?

**Comment by HipsterSloth** [comment]
It couldn't hurt to try switching to the SteamVR beta. That has helped some people in the best. You can alwys switch back if that doesn't work. If that doesn't help you should send a message to Deepoon support and link them to this issue. 

In the mean time I'm going to mark this issue as closed for tracking purposes since it technically isn't a PSMoveService problem. However, feel free to continue discussion in this thread.

**Comment by hoquillo** [comment]
I'll try.
Thank you so much!

**Comment by hoquillo** [comment]
I'VE GOT IT!!!
I really hope this can help others who use the Deepoon E2 too.
Just delete the folder ''oculus'' in ''Steam\steamapps\common\SteamVR\drivers\''. This forces to use the Deepoon driver and also avoid the confusion with the Oculus one.

I couldn't thank you enough, HipsterSloth. You are awesome!
