### ISSUE TITLE
In SteamVR, the controllers look like XBox controllers

### ISSUE THREAD

**Issue by maso27** [cboulay/PSMoveService#355]
I'm using this with an OSVR HDK 1.4.
Last week the controllers looked great, but after a SteamVR uodate over the weekend they now look like XBox controllers.

I'm not sure that this is related to PSMoveService, but was hoping that if anyone knew how to solve it, it would be you folks.

I love the software, by the way! Keep up the great work!

**Comment by POEDaley** [comment]
Are you using v6.0.9?  This release had fixes for that.

"SteamVR driver fixes

Fix issue with the wrong controller model showing up (set controller version type at creation time)
Added protocol version check that verifies the plugin isn't trying to connect to the wrong version of the service."

**Comment by maso27** [comment]
I'm using 6.0.9, and it was working beautifully.

Then there was a SteamVR update a few days ago, which broke the OSVR interface. I had to update _OSVR-SteamVR_ and grab the latest OSVR _Core Snapshot_, and when I brought it back up I had XBox Controllers instead of PS Move controllers.

I've tried re-running the installation .bat files but it hasn't fixed it. Any ideas?

**Comment by POEDaley** [comment]
Interesting.  I ran into that myself, but the update fixed it.  Does the beta of Steam VR do the same thing?  If that doesn't fix it, I'm afraid that about the extent of it for me.  From what I understood, it was about timing on when the controller model was grabbed, and 6.0.9 should have fixed it.  But I've been using the Beta version of Steam VR for quite some time myself, so unsure if going back to the standard SteamVR would replicate the issue.  @HipsterSloth would be able to explain that much better than I could.

**Comment by HipsterSloth** [comment]
Yeah 5.0.9 had a fix that dealt with the controller model issue. However the OpenVR API 1.0.6 just dropped a few days ago and it made substantial changes to how the controller properties work. It's entirely possible plugins that haven't upgraded to the latest API might have issues. I'm going to be working on merging the psnavi branch back up into master over the next few days, after which I'm going to be upgrading to OpenVR 1.0.6. 

In the mean time  you could try hacking around the issue by copying the psmove controller models in `E:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove\resources\rendermodels\psmove_controller` into `dualshock4_controller`, making the dusal shock models the same as the psmove controller models.

**Comment by maso27** [comment]
Fantastic!  Thanks to both of you.

I'll probably just overwrite the `dualshock4_controller` because sometimes the betas do weird stuff to OSVR.

I'll give it a shot this weekend.

**Comment by maso27** [comment]
So I've tried both copying the psmove controller models into the dualshock4_controller directory (and renaming them), and the SteamVR beta.

Neither have worked.

Something else pointing out though--I was incorrect thinking that it was an XBox controller, but it's not dualshock either.  It's a Steam Controller that I see within SteamVR.

Does that provide any further ideas?

**Comment by maso27** [comment]
Update: Got it!

It's in `...steamapps\common\SteamVR\resources\rendermodels\generic_controller`.

I copied the _.obj_, _.mtl_, and _.png_ files there, then renamed the _.obj_ file to _generic_controller.obj_.

The _.png_ and _.mtl_ files need to keep their same names though, as it seems they're referenced that way within the _.obj_ file.

**Comment by HipsterSloth** [comment]
Glad that fixed it for you. It sounds like the the same issue with the controller type not getting set in time when steamVR asks what the controller model should be. It will default to "generic_controller" in this case. I thought I had fixed this. I'll make sure this is fixed in the next release.
