### ISSUE TITLE
Bulbs Stay off, nothing detected in steam vr

### ISSUE THREAD

**Issue by esahcb** [cboulay/PSMoveService#356]
After going through the set up for the tracking, the bulbs turn off unless I start the  tracker test. 
If i go into the steam no base stations or controllers show up

**Comment by adc103** [comment]
A few things too try. Did you make sure to install all the drivers with the included bat files? Also make sure in your steam vr setting you are allowing multiple drivers.

**Comment by HipsterSloth** [comment]
For troubleshooting help please post the the PSMoveService google group first:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/psmoveservice

There are more people there that can help you. If this turns out to be an actual bug then we can file an issue here for this.
