### ISSUE TITLE
Ps moves will stop working and tracking in the middle of steam vr

### ISSUE THREAD

**Issue by marciokpo** [cboulay/PSMoveService#359]
so now after messing with the drivers and doing a bit of mess with psmove service too unpairing and pairing re calibrating pose tracking and that something went corrupted or not sure what it is , but whenever i start getting track of the ps moves it can wait for a whole minute or maybe 15 seconds , and after that i get "failed to connect to ps move service" in the psmoveservice config app , my ps moves shut down their lights , stop making track and the cameras red light go down and in psmoveservice it goes " ps move service id 0 and 1 stream disconnected" , "tracker id 0 1 and 2 disconnected" and stops there , in vrserver log of steamvr it throws this error " Mon Feb 06 2017 18:04:32.639 - psmove: CServerDriver_PSMoveService::HandleDisconnectedFromPSMoveService - Called
Mon Feb 06 2017 18:04:32.639 - psmove: CPSMoveControllerLatest::Deactivate - Controller stream stopped
Mon Feb 06 2017 18:04:32.639 - psmove: CPSMoveControllerLatest::Deactivate - Controller stream stopped" doesnt talk about the cameras , idk whats wrong now  before it worked flawlessly , i tried switching the port of the bluetooth dongle and re doing all the pairing and magnetometer of both ps moves but it wont work . Also tried using a different copy of ps move service to avoid the fact of ps move service corrupt files , its not that either. perhaps there are hidden psmove files i should erase , i also tried uninstalling and re installing all the ps move files

If you have any idea of what s going on plz lemme know

**Comment by Gabriel-try** [comment]
Maybe that helps for trouble shooting:
I had the same problem with the new release 6.10
So I decided to switch to the costom version 7.0
https://drive.google.com/open?id=0B5GgUbBXlQ1uTzhQTUJkdmRfeW8

That solved the problem for me.

**Comment by marciokpo** [comment]
Thanks a lot ! that solved it
