### ISSUE TITLE
PSEYE Multiple Cams free Driver !

### ISSUE THREAD

**Issue by magadan** [cboulay/PSMoveService#363]
Hello everybody. This is not a issue, is just a contribution:

Today i tested a free driver from a company called IPISoft ( motion capture system ) to use with PSEYE multiple cameras. The driver works very good !

This is a good alternative from CLEYE Driver or libusb installation setup ( sometimes difficult for many users ). And for a easy driver, you will not need spent anymore +/- US$ 8,00 with CLEye Driver ( like me ! )

So you can try, the installation is very simple just run and all PSEYE cameras are recognized.

Download links:
Device drivers for PS Eye camera.
64-bit OS: [http://files.ipisoft.com/drivers/PlayStation3_Eye_iPi-x64.msi](http://files.ipisoft.com/drivers/PlayStation3_Eye_iPi-x64.msi)
32-bit OS: [http://files.ipisoft.com/drivers/PlayStation3_Eye_iPi-x86.msi](http://files.ipisoft.com/drivers/PlayStation3_Eye_iPi-x86.msi)

Source: [http://docs.ipisoft.com/User_Guide_for_Multiple_PS_Eye_Cameras_Configuration](http://docs.ipisoft.com/User_Guide_for_Multiple_PS_Eye_Cameras_Configuration)

Result:

[http://i.imgur.com/4Kdyp96.jpg](http://i.imgur.com/4Kdyp96.jpg)

Hope this helps.

**Comment by adc103** [comment]
Are there advantages too using this driver over the libusb?

**Comment by magadan** [comment]
Really dont know more technical info, we need to get more info with applications like USBView. 

But for me the best advantage is the easy installation for all users.

Performance for me is ok.

**Comment by magadan** [comment]
!(http://i.imgur.com/HoSjCpT.jpg)[http://i.imgur.com/HoSjCpT.jpg]

**Comment by HipsterSloth** [comment]
So with this driver does it just make the PS3 Eye camera appear like a regular web cam? PSMoveService doesn't currently support generic web cam based tracking. We used to a long time ago, but turned it off because we were having problems with people up other non ps3eye web cameras. Point being, install this at your own risk.

**Comment by magadan** [comment]
Hi Guido, no the camera not appears for Windows applications, i tried with skype, not sucess. But works with test_camera.exe and psmoveservice .

**Comment by HipsterSloth** [comment]
@magadan Really?! Huh... I would not have expected that to work. I will give that a try now.

**Comment by magadan** [comment]
I updated the Wiki section with this new driver, hope this helps the psmoveservice community.

**Comment by HipsterSloth** [comment]
I just finished testing it in win10 x64 myself. I had to uninstall my old libusb driver first and then install the iPisoft driver, but it looks like it works:

![image](https://cloud.githubusercontent.com/assets/16793853/23056858/3eed05a4-f4a2-11e6-8ac7-a46816e7bb81.png)

It seems to think it's a WinUSB based driver. The libusb client library that PSMoveService uses can open devices using the WinUSB based kernel drivers so that much be why this works?

Thanks for investigating that and updating the wiki!

That's cool that people don't have to use Zadig anymore and nice of iPiSoft to provide the WinUSB based camera driver.

**Comment by magadan** [comment]
For final, the license: ( included in the 'program filex(x86)/IPIsoft'

WinUSB Driver Registration for Sony PlayStation3 Eye Camera.
Copyright (C) iPi Soft LLC. 
Portions Copyright (C) Microsoft Corporation. All Rights Reserved.

WinUSB Driver Registration for Sony PlayStation3 Eye Camera is free for use in any environment, including but not necessarily limited to: personal, academic, commercial, government, business, non-profit, and for-profit. "Free" in the preceding sentence means that there is no cost or charge associated with the installation and use of WinUSB Driver Registration for Sony PlayStation3 Eye Camera.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software (the "Software"), to use the Software without restriction, including the rights to use, copy, publish, and distribute the Software, and to permit persons to whom the Software is furnished to do so.

You may not modify, adapt, rent, lease, loan, sell, or create derivative works based upon the Software or any part thereof. 

The above copyright notice and this permission notice shall be included in all copies of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

**Comment by magadan** [comment]
The license permits to redistribute, so its possible to make a custom installer ( with Advanced Installer  http://www.advancedinstaller.com/ ) and put this drivers to automatic install pseye driver.

If sounds interesting i can do this installer. ( exe and .msi )

**Comment by zelmon64** [comment]
This seemed interesting so I thought I'd have a go. Performance wise it doesn't seem very different (which I suppose should have been obvious).

What concerns me is that the un-installation does not seem to work. Deleting the driver was fine but when I tried to uninstall it from Programs and Features it would only tell me that it is already installed. Luckily for me I created a restore point before installing it. 

I suppose it shouldn't do any harm leaving it installed but I don't like not having the ability to remove it completely. 

Am I just paranoid or is this potential problem (or was I just inept at un-installing it)?

**Comment by magadan** [comment]
My last conversation with  Software Engineer from IPISoft

I asked about use this driver for windows common apps...

Responde:

_"Hello, Cristian,
PS3 Eye cameras is not supposed to be used on PC. So there are no official drivers for Windows.
We used WinUSB technology to allow iPi Recorder to communicate with camera. This is not noraml driver, so other apps cannot use PS3 as they do with usual web camera."_

**Comment by magadan** [comment]
@zelmon64  no problems here to uninstall. (win10 x64)

**Comment by HipsterSloth** [comment]
For tracking purposes I'm going to close this issue (now that all the info is in the wiki). But feel free to continue discussion
