### ISSUE TITLE
Help to build on windows 10 x64

### ISSUE THREAD

**Issue by magadan** [cboulay/PSMoveService#368]
Help to build on windows 10 x64...

C:\PSMOVESERVICE\PSMoveService\thirdparty\protobuf\vsprojects>cmake -G "Visual Studio 14 2015 Win64" -Dprotobuf_DEBUG_POSTFIX="" -Dprotobuf_BUILD_TESTS=OFF ../cmake
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:12 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:12 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!

(already installed correct cmake and boost)

**Comment by magadan** [comment]
by InitialSetupX64.bat

C:\PSMOVESERVICE\PSMoveService>InitialSetup_X64.bat
'"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
"Creating protobuf project files..."
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:12 (project):
  No CMAKE_C_COMPILER could be found.

**Comment by cboulay** [comment]
What version of Visual Studio do you have installed?

**Comment by magadan** [comment]
Community 2015 version 14

**Comment by HipsterSloth** [comment]
@magadan Are you still having trouble building using 2015?

**Comment by magadan** [comment]
Guido, all ok. Thank you.

**Comment by zelmon64** [comment]
I had this (I think I also had it in the past and resolved it but it's come back and couldn't recall how to fix it) so I'm going to make a note for possible fixes.

The root error was `cannot run 'rc.exe'` which can be resolved by either [copying](https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe/14373113#14373113) `rc.exe` and `rcdll.dll` from `C:\Program Files (x86)\Windows Kits\X.X\bin\x86` to `C:\Program Files (x86)\Microsoft Visual Studio XX.0\VC\bin` or adding 
`C:\Program Files (x86)\Windows Kits\X.X\bin\x86` to the [PATH Environment Variable](https://stackoverflow.com/a/43927381/8364786).

In my case the versions were Windows Kits **8.1** and Microsoft Visual Studio **14.0**.
