### ISSUE TITLE
How to use PS move like a mouse ; Set up-help

### ISSUE THREAD

**Issue by Toroborn** [cboulay/PSMoveService#369]
I have ps move, ps3 eye and dongle
I'm lost I've calibrated and paired PS move to my PC.
I'd like to use its motion tracking as a mouse function for a game called For Honor.
I've gone through PSMOVE config tool and partly done what a tutorial video which was for VR, instructed.
I need help getting the game recognizing the mod.

 is there a way to make it work like a gamepad with motion tracking as would a mouse.
I've tried motioninjoy but it didnt work
also tried better ds3 but my drivers are already paired with ps3 eye and ps move

Help would be appreciated! 
♥

**Comment by cboulay** [comment]
This seems like something FreePIE might be able to do. Ask in the message board: https://groups.google.com/forum/#!forum/psmoveservice

As this question isn't really related to an issue with the PSMoveService codebase I'm going to close this issue. The message board should be the first place to ask these kinds of off-topic questions.
