### ISSUE TITLE
Only one Controller Appearing in SteamVR

### ISSUE THREAD

**Issue by RandomGuy9900** [cboulay/PSMoveService#378]
Hello,

I have recently attempted to setup the PS Move controllers for SteamVR.

I was able to get through all of the calibration steps for my cameras as well as both of the controllers and everything looks well when I test the cameras and the orientation on both controllers.

Although, when I start SteamVR up, both controllers' bulbs light up yet Controller0 does not show up in SteamVR, only Controller1.  If I press select and start on either controller, it resets the one controller that is appearing.  I have all 3 eyes showing up in SteamVR, and 2 controllers, all grey. 

Please let me know any more information I can provide or attach that might be helpful in debugging this.

Thank you,
Ryan

**Comment by cboulay** [comment]
For SteamVR and other client-related questions please ask in the [forums](https://groups.google.com/forum/#!forum/psmoveservice) first. You're likely to get an answer from community members who use this regularly.
