### ISSUE TITLE
How do i add positional tracking with third ps move controller Without using a phone?

### ISSUE THREAD

**Issue by marciokpo** [cboulay/PSMoveService#381]
Im having this problema lately , i own a deepoon e2 which is a headset that Works with oculus and steamvr ( but doesnt have extended mode or doesnt work on desktop of pc but the other things mentioned) and i did all the steps for adding positional tracking , Freepie's script , psmovefreepiebridge i added the third controller there and steam vr recognizes it all as a third controller but thats all , i couldnt make riftcat work as in turning on because i dont own a phone capable of running vridge ( and actually i dont need the phone i just need positional tracking ) so i left riftcat at the option that says , use "freetrack direction and position" but it wont work at all. Any ideas of what im missing? I also filtered the controller using the filter line in the steamvr file , and nothing

**Comment by cboulay** [comment]
Hi, questions related to 3rd party software should be directed to the psmoveservice google group. You'll get better answers there.
groups.google.com/forum/#!forum/psmoveservice

**Comment by marciokpo** [comment]
thx
