### ISSUE TITLE
Cant compute tracker poses

### ISSUE THREAD

**Issue by Marmighty** [cboulay/PSMoveService#385]
I'm using 1 ps3 eye camera, which shows up when i run the test_camera.exe, however the issue is that when i go to compute tracker poses with my PSMove controller nothing happens. I have the controller with the magenta light placed on position one, the camera can see it but stays on sample: 0/60 and nothing happens.

I also dont get any controllers showing when i start steamvr, i'm trying to use this with Trinus PSVR, however i have had no success yet.

**Comment by HipsterSloth** [comment]
Please post this issue over on the google group first: 
https://groups.google.com/forum/#!forum/psmoveservice

You'll get better support there for this issue.
