### ISSUE TITLE
Xcode: duplicate symbol _g_supported_controller_infos

### ISSUE THREAD

**Issue by cboulay** [cboulay/PSMoveService#395]
I'm working on fixes for compilation in MacOS. See ac7817dc47db059132c2c41515d538117a343a29

I ran into an error that I don't know how you want to handle.

```
duplicate symbol _g_supported_controller_infos in:
    PSMoveService/build/src/psmoveservice/PSMoveService.build/Debug/PSMoveService.build/Objects-normal/x86_64/ControllerGamepadEnumerator.o
    PSMoveService/build/src/psmoveservice/PSMoveService.build/Debug/PSMoveService.build/Objects-normal/x86_64/ControllerHidDeviceEnumerator.o

ld: 1 duplicate symbol for architecture x86_64
```

**Comment by HipsterSloth** [comment]
I just needed to renamed the duplicate symbols. Those globals are only in the scope of those respective files. Fix is in latest:

https://github.com/cboulay/PSMoveService/commit/3b3f14298c042e710831016366bfc035f40323cf
