### ISSUE TITLE
MacOS XCode: test_camera_parallel.cpp "ppl.h not found"

### ISSUE THREAD

**Issue by cboulay** [cboulay/PSMoveService#396]
@zelmon64 , what is ppl.h?

This is the only fix remaining in Mac. I can exclude test_camera_parallel from Mac build but I wanted to check what it was first.

**Comment by zelmon64** [comment]
@cboulay sorry I forgot to keep in mind cross platform compatibility when I did this. It's the Microsoft parallel patterns Libbey - it's where parallel_for_each comes from. Having a look around I found [this blog post](https://www.google.co.uk/amp/s/xenakios.wordpress.com/2014/09/29/concurrency-in-c-the-cross-platform-way/amp/) which talks about making it cross platform (funnily it says Apple makes these things awkward on purpose). I sort of understand so I can have a go at changing it.

**Comment by zelmon64** [comment]
@cboulay I've made the changes suggested by that blog post in PR #397 but I don't have a way to test it (it still runs fine on Windows). If it does work I'm wondering if concurrent_vector.h. will then cause a similar problem but I haven't found any solution to that yet.

**Comment by HipsterSloth** [comment]
I merged in PR #397 Zelmon. Looking over the code again briefly this morning i'm thinking you don't need to use a concurrent vector since you don't actually have multiple threads trying to modify the same state at the same time (modifying the vector size, modifying the same entries). You can probably just use a std::vector in this instance.

**Comment by zelmon64** [comment]
I was going to change it over to `std::vector` but I see that it's already been done in 
332669eaafc1333d7ffea1054b31fb3d9a592000 thanks. It must have been something else I tried that needed it to be a concurrent vector. Is there anything else that needs to be changed or can this be closed now?
