### ISSUE TITLE
Button mapping issue

### ISSUE THREAD

**Issue by Jtpeterson2011** [cboulay/PSMoveService#408]
Cannot find file to button map. `C:\Program Files (x86)\Steam\config\steamvr.vrsettings` has 3 lines in it and when i add the button mapping lines it just gets overwritten by the 3 lines again. So i tried `C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\settings` but when i put the button mapping lines in here it flips my display and nothing works correctly.

**Comment by cboulay** [comment]
Hi.
The SteamVR plugin is no longer part of the PSMoveService and instead can be found [here](https://github.com/HipsterSloth/PSMoveSteamVRBridge).

But, you're more likely to get an answer to this question by asking in the forum first.
https://groups.google.com/forum/#!forum/psmoveservice
