### ISSUE TITLE
Button Mapping issue

### ISSUE THREAD

**Issue by Jtpeterson2011** [cboulay/PSMoveService#409]
Cannot find file to button map. `C:\Program Files (x86)\Steam\config\steamvr.vrsettings` has 3 lines in it and when i add the button mapping lines it just gets overwritten by the 3 lines again. So i tried `C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\settings` but when i put the button mapping lines in here it flips my display and nothing works correctly.

**Comment by cboulay** [comment]
I already answered you.
