### ISSUE TITLE
Need new 3d models for assets to display in the config tool

### ISSUE THREAD

**Issue by HipsterSloth** [cboulay/PSMoveService#41]
* Replace PS3 EYE camera model with texture
* Replace PSMove controller model with texture
* DualShock 4 model with texture
* Navi controller model with texture

**Comment by InfinateXtremer** [comment]
Hi there, i actually modeled and textured a PSMove model to use it on SteamVR, texture work is not perfect and it probably needs some scaling too but you can check it out [here](https://onedrive.live.com/redir?resid=FC9C40AB2B66A479!53943&authkey=!AARHliXOTWZ4kAs&ithint=folder%2cpng) (tried to upload it on github but it refused to accept .zip file)

**Comment by HipsterSloth** [comment]
Thanks a bunch for this. I'll incorporate this model this weekend.

**Comment by InfinateXtremer** [comment]
Happy to help! I'm also planning modelling EYE Camera this weekend but i can't promise because of my exams.

**Comment by HipsterSloth** [comment]
Oh no rush. Exams come first :)

**Comment by InfinateXtremer** [comment]
Finished EYE, You can see it from [here](https://sketchfab.com/models/d7cd71b9dbe241929d524ef89b2c5c86) and download it from [here](https://onedrive.live.com/redir?resid=FC9C40AB2B66A479!53955&authkey=!AAW5Fd6fedDpM5A&ithint=folder%2cmtl)

UV Maps are fine when you download it but there is bug in sketchfab that messes up UV maps right now.

**Comment by HipsterSloth** [comment]
Thanks a bunch, looks great! Your timing is perfect. I was debugging the steam vr plugin last night and realized one of the things I needed was pseye model for the compositor view. As soon as I get the plugin working (which should be by the end of this weekend) i'll upload a movie of it in action with your new models.

**Comment by InfinateXtremer** [comment]
That's good to hear, also i'm going to model Navi Controller next.

**Comment by HipsterSloth** [comment]
@InfinateXtremer So I've been trying to get the controller and ps3eye models to show up in steamvr and haven't been having any luck. After some investigation I found the problem in a steamvr log file (vrclient_vrcompositor.txt):

```
Mon Jun 06 2016 17:21:37.177 - RendermodelManager: Reading data from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove\resources\rendermodels\ps3eye_tracker\ps3eye_tracker.json
Mon Jun 06 2016 17:21:37.177 - RendermodelManager: name=body inputRouting=0 filename=ps3eye_tracker.obj
Mon Jun 06 2016 17:21:40.525 - Render model C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\psmove\resources\rendermodels\ps3eye_tracker\ps3eye_tracker.obj specifies multiple diffuse texture materials. Only one diffuse texture per model is supported.
```

It turns out each model can only have one texture. You can break the object up into multiple pieces and make a .json file that connects all of the pieces that have different textures, but if you want a single model it has to be a single texture. Would it be two much trouble to get the psmove controller and the ps3eye to have a single texture? They both currently have two.

Thanks a bunch.

**Comment by InfinateXtremer** [comment]
So that's why i never managed to get them on steamvr, fixing it now.

**Comment by HipsterSloth** [comment]
@InfinateXtremer Hey sorry I haven't written back in a while about this. I got bogged down in fixing controller rumble and adding support for the dualshock4 the last few weeks. I finally got these models in tonight. You can see the models in action here: https://www.youtube.com/watch?v=xomIBMLvDEY. The updated steamvr plugin is now checked into latest. I still need to integrate the new models into the  client config tool. I'm going to try and do that this weekend.

**Comment by HipsterSloth** [comment]
Closing this issue to make individual issues for navi and ds4
