### ISSUE TITLE
Tracker video problems:  Trying to use one PS Eye to emulate Rift Sensor

### ISSUE THREAD

**Issue by argold57** [cboulay/PSMoveService#413]
Hello: 
I am trying to use PSMove and one PSEye to emulate the Rift Sensor with my PiMax 4K HMD.  I am trying to play the Rift Game "Chronos" but it fails to launch with the error messege: 
     "Please check your headset and sensor are connected"  
Chronos is a game played with an XBox One controller so no PSMove controllers are needed

I hope PSMove is the solution to having no sensor.  If not, please advise.

My PSEye came today but (no surprise) I am having a hard time getting it working with steamVR (BTW, I am an electrical engineer and know my way around drivers).

The videos on the PSMove Service site are complete with multiple cameras and controllers and the like but I thought this one PSEye setup should be easier.

Here is what I have done and the step-by-step results:

1) Plugged in the camera
2) Used Zadig to install libusb-win32 driver
3) checked it was installed as a libusb-win32 devic3e on device manager
4) Ran PSMoveService\...\test camera.  The camera works and I can see an image, however there were a few error messages as follows: 
	libusb: error [init_device program assertion failed: device address collision with root hub
followed by 9 of the following:
	libusb: error [windows_get_device_list] program assertion failed - existing device should share parent

5) Ran PSMoveSteamVRBridge\SteamVR_InitialSetupWin64.bat and pointed to the steam install directory (no errors)
6) Ran PSMoveSteamVRBridge\SteamVR_ReinstallDriverWin64.bat 
	There was one error, the last file to be copied was missing.  It was openvr_api.dll so I just grabbed the latest one from a recently installed game and copied it to the PSMoveSteamVRBridge folder and re-ran.  I verified the files following were copied to \Steam\SteamApps\common\SteamVR\drivers\psmove\bin\win64:
	driver_psmove.dll
	monitor_psmove.exe	
	openvr_api.dll	(the one that was missing that I copied from a new game)
	PSMoveClient_CAPI.dll
	(note that there were no .pdb files to copy)	
	
5) Ran PSMoveSteamVRBridge\SteamVR_SetDriverVarsWin64.bat (no errors)
6) Started the PSMove service as administrator.  (there is a log at the bottom of this post of it's output (with my user info deleted))
7) Started the PSMoveConfigTool.exe and was able to connect to the PSMove Service.  
	Since I have no controllers or bluetooth adaptor I did no Controller settings.
	There is no HMD in HMD settings (no surprise). 
	The tracker settings show Tracker ID 0, type PS Eye controller type LIBUSB and the rest look good
	HOWEVER: when I tried to run the video feed test, the config tool reported:
[INFO] SharedMemory::initialize() - Opening shared memory: tracker_view_0[ERROR] SharedMemory::initialize() - Failed to allocated shared memory: tracker_view_0, reason: The system cannot find the path specified.
	...and there was no video feed
	Attempting to run Calibrate Tracker Distortion throws the error" "Failed to open tracker stream".  The same error as above about shared memory shows in the /config Tool console.
	ALSO: the tracker settings did not have all the controls shown in the video.  The only controls available in tracker settings were Test Video Feed, Calibrate Tracker Distortion, and return to main menue.  I assume this was because I have no controllers.

8) modified my SteamVR.vrsettings file.  Here it is:
{
	"camera":{
		"enableCameraInDashboard":false
	},
	"steamvr":{
		"activateMultipleDrivers" : true,
		"background":"#FF000000",
		"defaultMirrorView":2,
		"directModeEdidPid":4121,
		"directModeEdidVid":53838,
		"mirrorViewGeometry":"0 0 540 960",
		"startMonitorFromAppLaunch":false
	}
}

9) Ran SteamVR_ReinstallDriverWin64.bat (no errors)
10) Verified that disable_roi is "false" in TrackerManagerConfig.json
11) restarted the PSMoveService as admin.
12) started SteamVR.  Steam VR shows ONLY the HMD and not any additional sensors or trackers.
Started Chronos but still get the error: "Please check your headset and sensor are connected"

(DISPLAY FROM PSMoveService.exe from step 6)
[2017-04-19 21:42:22.620]: main - Starting PSMoveService v0.9-alpha 8.2.0
Config file name: "<deleted>\AppData\Roaming\PSMoveService\USBManagerConfig.json"
Config file name: "<deleted>\AppData\Roaming\PSMoveService\USBManagerConfig.json"
Config file name: "<deleted>\AppData\Roaming\PSMoveService\NetworkManagerConfig.json"
Config file name: "<deleted>\AppData\Roaming\PSMoveService\NetworkManagerConfig.json"
[2017-04-19 21:42:22.628]: USBAsyncRequestManager::startup - Requested LibUSBApi
[2017-04-19 21:42:22.628]: USBAsyncRequestManager::startup - Creating LibUSBApi
[2017-04-19 21:42:22.631]: USBAsyncRequestManager::startup - Initialized USB API
Config file name: "<deleted>\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
Config file name: "<deleted>\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
[2017-04-19 21:42:22.636]: DeviceManager::startup - Platform Hotplug API is ENABLED
[2017-04-19 21:42:22.638]: bluetooth_get_host_address - Failed to find a bluetooth radio
Config file name: "<deleted>\AppData\Roaming\PSMoveService\TrackerManagerConfig.json"
Config file name: "<deleted>\AppData\Roaming\PSMoveService\TrackerManagerConfig.json"
libusb: error [init_device] program assertion failed: device address collision with root hub
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [init_device] program assertion failed: device address collision with root hub
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
[2017-04-19 21:42:22.782]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\b3_p9, camera_index=0)
libusb: error [init_device] program assertion failed: device address collision with root hub
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
ps3eye::PS3EYECam::getDevices() found 1 devices.
Config file name: "<deleted>\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b3_p9.json"
Config file name: "<deleted>\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b3_p9.json"
[2017-04-19 21:42:22.962]: SharedMemory::initialize() - Allocating shared memory: tracker_view_0
[2017-04-19 21:42:23.94]: DeviceTypeManager::update_connected_devices - Device device_id 0 (PSEYE) opened

**Comment by HipsterSloth** [comment]
We're trying to route troubleshooting issues to the google group first. If we determine that there is a code issue, then we make a formal issue. I went ahead a made a new topic here with all the info you posted:

https://groups.google.com/forum/#!topic/psmoveservice/pYYxjzB-n1o

We should continue discussion there. Closing this issue for tracking purposes.

**Comment by argold57** [comment]
Thank you.
