### ISSUE TITLE
Calibrate Magnetomter dont work/Disable

### ISSUE THREAD

**Issue by tEdFAn026** [cboulay/PSMoveService#415]
First of all I used 5.1.0 and when I went into the Calibrate Magnetomter it didn't work, so I downloaded the lastest version(8.2.0) but it show that the Calibrate Magnetomter disabled
How can fix the problem?

5.1.0 setting: https://gyazo.com/5848768b12f4dcd621f6aff19bead588
         Calibrate Magnetomter: https://gyazo.com/637c186ea7fc7ed2c68faae36c80d3f2
8.2.0 setting:  https://gyazo.com/e2a7ac2e2604203020977d971dc5c5fb

**Comment by HipsterSloth** [comment]
For some reason on the newer psmove controllers (the ones that came out around the same time as the PSVR), Sony decided they no longer wanted to use the mangnetometer. My guess is that they were having too many issues with magnetic interference (home speaker systems for example).  Unfortunately, it looks like you have a controller with newer firmware that disables the magnetometer. You can still use this controller, but it will have a bit more yaw drift than ones that have a functional magnetometer. In the case of drift, you can always recenter by holding down the SELECT button on the controller for 1/4 of a second.

**Comment by HipsterSloth** [comment]
Closing this issue for tracking purposes (since PSMoveService is working as expected in this situation). Though please feel free to post any additional questions about the issue here.

**Comment by zelmon64** [comment]
@HipsterSloth on this subject do you know anything about the firmware update 4.50? It's said that it [massively improves](http://www.pushsquare.com/news/2017/03/ps4_firmware_update_4_50_massively_improves_playstation_move) the PSMove which I would think could only be the case if they've re-enabled the magnetometer.

**Comment by HipsterSloth** [comment]
@zelmon64 From what I could tell it was just firmware improvements to the camera tracking code unfortunately. But I've only given a cursory glance. The one way to know for sure would be to download the psmove firmware on a controller that was plugged into a 4.0 console. Then update to 4.5. Plug the controller in. Then download the firmware again and diff the results. I personally have never had luck downloading the controller firmware on windows (the request to put the controller in DFU mode doesn't work for me). But apparently others have had luck in linux with psmoveapi.

**Comment by Zangetsu38** [comment]
i have same oin my PS4 PSMove, buyed for ps4 and PSVR
tested on pc with psmove api and psmoveservice for compare, and my controller with id
USB\VID_054C&PID_03D5&REV_0400 works perfect, is pack PSMove + sport champion + PSEYE, so is old PS3 pack
but, for psmove PS4 is "USB\VID_054C&PID_03D5&REV_0460" and is calibrate works but for calibrate Magnetomter is keep on 0.0 and calibrate with no move psmove works, so no idea what Sony have changed on more recent psmove, maybe disable Magnetomter  ? strange, i more thinked psvr use it on ps4
