### ISSUE TITLE
Use Wii Numbchuck as controller?

### ISSUE THREAD

**Issue by QuillzLouis** [cboulay/PSMoveService#423]
Could you use the Wii Numbchuck  with the ps move service tracking a ball of light on top? This would theoretically give you all the degrees of movement

**Comment by cboulay** [comment]
The Wii Nunchuk has to be plugged in to something. Also, it doesn't have a full IMU. e.g., see [here](http://diydrones.com/forum/topics/why-not-use-the-wii-imu)
