### ISSUE TITLE
Psmove orientation reversed after 180 turn around- for head tracking

### ISSUE THREAD

**Issue by hatingpomg** [cboulay/PSMoveService#427]
I have set up Psmove server with four camera.
And I connect it to riftcat using PSMove freepie bridge.
I use the third controller as the head tracking orientation
But I have found that the orientation reverse when I turn 180 Degree around (see the video )
https://www.youtube.com/watch?v=mg3DvlU1p9w

PS:
I am following Daley Tech setup
https://www.youtube.com/watch?v=QEraN1r_5Nw&list=PLM_NtdgT2QVc1lcmHoo4AwNLp_wo67fmV&index=6&t=12s

with the PS Move FreePie Bridge
https://bitbucket.org/hawkinse/psmovefreepiebridge/downloads/

the PC
i5 2400
8GB RAM
GTX 1060 6GB
128 ssd +500 Hdd

Ps move server Alpha Release #8.4.0
PSMove freepie bridge Release 13

**Comment by cboulay** [comment]
As this is probably not a problem with PSMoveService itself, and is likely a configuration problem relating to a bridge/driver etc., you're better off searching then asking the question in the google group first:
https://groups.google.com/forum/#!forum/psmoveservice

You can continue to comment here but I'm closing the issue for tracking purposes.

**Comment by hatingpomg** [comment]
Thank for your reply, yes psmoveserver work well on orientation and position test.
I think you are right.
I have no idea where can i ask the question so i post it here, 
thank you for giving me the google group link
Thank you~
