### ISSUE TITLE
Google Earth VR dont see my controlers anymore, they dont work in apk.

### ISSUE THREAD

**Issue by VRmaniaQ** [cboulay/PSMoveService#428]
When using Google Earth became possible for owners Riftcat + psmoveservice (Without Fake VIVE) everything worked beautifully.

Some time later, the controllers in the application became invisible (and did not respond to the buttons). I was hoping that some update would fix this, so I did not bother.

It's been a long time, I even tried "Fake Vive". I tried 2x to reinstall the application. And other things.

I'm using the latest version of Psmoveservice and Riftcat.

Please help. Google Earth is a great application. Without it, VR loses a lot.

**Comment by cboulay** [comment]
PSMoveService itself no longer has anything to do with SteamVR. For that you need to ask people in the google group first, and if no one knows then try [PSMoveSteamVRBridge](https://github.com/HipsterSloth/PSMoveSteamVRBridge).

I have never used PSMoveService with SteamVR, any smartphones, or any other HMDs. If you can't point me to a specific problem in PSMoveService then I can't help you.

**Comment by VRmaniaQ** [comment]
Thx for the answer. And for a PSMS. It is great :) ! 

Greetings! :)
VR ManiaQ - ytbe.
