### ISSUE TITLE
thirdparty/PS3EYEDriver does not build on Xcode

### ISSUE THREAD

**Issue by cboulay** [cboulay/PSMoveService#43]
[This](https://github.com/HipsterSloth/PS3EYEDriver/blob/f64afac61dda55c36f004b5f99b855b2028be907/src/ps3eye.cpp#L620-L656) block of code is the culprit. 

`switch (control_transfer_status)` gives the following: "Multiple conversions from switch condition type 'std::atomic_int' to an integral enumeration type."

Then the `assert` statements also fail because an incorrect "assert.h" is on the path. I haven't tracked it down yet. According to build settings, the only path I have in my header search path is `/Volumes/STORE/Tools/VR/PSMove/PSMoveService/build/psmoveprotocol` but I can't imagine that's exhaustive. Anyway, this is fixed by `#include <assert.h>` at the top of the file.

Then [here](https://github.com/HipsterSloth/PS3EYEDriver/blob/f64afac61dda55c36f004b5f99b855b2028be907/src/ps3eye.cpp#L1218) there is use of undeclared identifier strcat_s. This is supposed to be in C11. Maybe we are missing a cmake flag to set C11? Or maybe it's not really in the standard.

**Comment by HipsterSloth** [comment]
Looks like I neglected to build my modified version of PS3EYEDriver on OS X. I think the switch statement can be fixed by just casting to control_transfer_status to an int. As for the strcat_s, we could just skirt the issue by switching it over to a snprintf("%s%s").

**Comment by cboulay** [comment]
Do you mind making this fix? For me to do it adds about 5 steps vs you doing it.

**Comment by HipsterSloth** [comment]
Not at all. I'll can make the code fix at work. I won't be able to test the os x build until I get home tonight though.

**Comment by cboulay** [comment]
Thank you. I'm at the airport right now. I should be home in 4 hours. I'll take a look then.

**Comment by HipsterSloth** [comment]
I just checked in the ps3eye driver fixes:
https://github.com/HipsterSloth/PS3EYEDriver/commit/00a2b6f3cf61acf8ddb754808874050e92650e7a

and updated the PS3EYEDriver submodule: https://github.com/cboulay/PSMoveService/commit/9f35484b995d3b26b32110c1e967a17b151cfcf5

**Comment by cboulay** [comment]
Nicely done, she builds!

**Comment by HipsterSloth** [comment]
Woo! \o/
