### ISSUE TITLE
INSTALL build does not work first time

### ISSUE THREAD

**Issue by gb2111** [cboulay/PSMoveService#437]
tried it already few times. when I clone all source and run INSTALL project first time there is error unable to open opencv header.
then I run it again and it works.

**Comment by gb2111** [comment]
first of all, there is no cloning of opencv

4>  Cloning into 'opencv'...
3>C:\XXKornisz\Documents\GitHub\PSMoveService\build\src\psmoveprotocol\PSMoveProtocol.pb.cc(6126): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data


and later we have:
9>  AppStage_DistortionCalibration.cpp
9>C:\XXX\Documents\GitHub\PSMoveService\src\psmoveconfigtool\AppStage_DistortionCalibration.cpp(23): fatal error C1083: Cannot open include file: 'opencv2/opencv.hpp': No such file or directory
9>  AppStage_GyroscopeCalibration.cpp
9>c:\XXXdocuments\github\psmoveservice\src\psmoveconfigtool\GeometryUtility.h(9): fatal error C1083: Cannot open include file: 'opencv2/opencv.hpp': No such file or directory
9>  AppStage_HMDAccelerometerCalibration.cpp

**Comment by HipsterSloth** [comment]
You have to build the OpenCV sub-project first to get it to download the dependancies, then you can do a build all.

https://github.com/cboulay/PSMoveService/wiki/Building-from-source#build
> Open <path_to_repo>\build\PSMoveService.sln
> Change to "Release" configuration
> Rt-click on the OpenCV External project and build
>  This will download OpenCV 3.1 into the /deps folder and compile it
> Rt-click on the PSMoveService solution and build (or do a "Build All..." from the build menu)

Ideally the INSTALL setp would have the opencv sub project as a dependancy so you wouldn't have to do this extra step. But for the moment it is working as expected, it's just not as streamlined as it could be.
