### ISSUE TITLE
Magnetometer Calibration stop at 62%

### ISSUE THREAD

**Issue by mscavazza** [cboulay/PSMoveService#438]
When I'm doing the calibration it goes up to 62% and then I can not go any further, what can I do? I tested on two different computers

**Comment by HipsterSloth** [comment]
It could be that there is an issue with the magnetometer in your PSMoveController or there could be a magnetic distortion present depending where you are testing (large speakers? Iron beams?) Given that you tested on two different computers I suspect it's an issue with your PSMoveController.  Get as far as you can with the magnetometer calibration and then  hit the "force accept" button. Then look at the config file that game saved out for your controller. It should be in `%appdata%/PSMoveService/xx_xx_xx_xx_xx_xx.json`. Look for the magnetometer extents section:

```
            "Extents": {
                "X": "179.5",
                "Y": "174",
                "Z": "166"
            },
```

The three values listed there should be relatively close to each other (within around 10-15). If they are father apart than that you might want to consider getting a different controller. If they are close to the same then you should be good to go.

**Comment by HipsterSloth** [comment]
Ah I just discovered your post on the google group. Closing this issue here in favor of the discussion there.
