### ISSUE TITLE
There is no good tutorial for computing tracker poses in the new version 

### ISSUE THREAD

**Issue by Thestickman391** [cboulay/PSMoveService#439]
It's very confusing. What does "Please pick up the HMD" mean? Pick up what? Hold it above what? I can get it to work just by randomly moving my rift around but then it tracks too quickly and I get awful tracking because I didn't have time to move the controller. Can someone please write a proper tutorial?

**Comment by zelmon64** [comment]
That's a bit odd. If you use a controller it should say ["Please pick up the controller"](https://github.com/cboulay/PSMoveService/blob/20fde73a5f09bf82c4591e72f264ce5f62dd94a3/src/psmoveconfigtool/AppSubStage_CalibrateWithMat.cpp#L660). The "Please pick up the HMD" is for when you use the HMD to compute the tracker poses.

**Comment by zelmon64** [comment]
@Thestickman391 try this PSMoveConfigTool. I think I fixed it.
[PSMoveConfigTool-PSMoveService_0.9_alpha8.6.0-custom1.zip](https://github.com/cboulay/PSMoveService/files/1094360/PSMoveConfigTool-PSMoveService_0.9_alpha8.6.0-custom1.zip)

**Comment by Thestickman391** [comment]
Thank yo, so much this worked perfectly! (sorry for late response, got a bit distracted in vr)
