### ISSUE TITLE
Controllers do not track in Superhot

### ISSUE THREAD

**Issue by Thestickman391** [cboulay/PSMoveService#443]
Instead, all I get are these floating hands that are supposed to track onto my controllers. These hands do not move at all and I can look right into them. Note that my controllers track in every other game I've tried. Does anyone else have this issue?
![image](https://user-images.githubusercontent.com/4157860/27505053-5d5244d0-58ea-11e7-9885-c9660354a89a.png)

**Comment by cboulay** [comment]
Once again, this is something that should be posted to the google group.
