### ISSUE TITLE
aboud bluetooth detected

### ISSUE THREAD

**Issue by tyu852** [cboulay/PSMoveService#445]
PSMoveConfigTool not detected though bluetooth is inserted in the USB.
and, PSMoveService display [bluetooth_get_host_address - Failed to find a bluetooth radio].
Where is it wrong?

**Comment by HipsterSloth** [comment]
This sounds like a troubleshooting question. Please post it to the Google group instead of the issues page. 

https://groups.google.com/forum/#!forum/psmoveservice

If we determine that it's an actual bug, we'll create an issue for it.
