### ISSUE TITLE
I have all the steam psmoveservice drivers installed my controllers show up on psmove service but not on steamvr

### ISSUE THREAD

**Issue by thatsitlol** [cboulay/PSMoveService#450]
basically that. my controllers show up on psmove service but dont how up in steam vr
also with my cameras my cameras dont show up
ive edited the steam vrr file
{
	"steamvr": {
		"mirrorViewGeometry": "0 0 1920 1080",
		"activateMultipleDrivers": true
	}
}
but it still doesnt work
update- it says 
"Not Ready"
dont know how to fix it. When I open trinus vr and hit start it says open steam vr, when i open steam vr it still says open steam vr, any fix?

**Comment by HipsterSloth** [comment]
Same as the other issue, I'm closing this issue in favor of a google group thread first:

https://groups.google.com/forum/#!forum/psmoveservice
