### ISSUE TITLE
steam is not detecting cameras or ps3 moves 

### ISSUE THREAD

**Issue by lexvex** [cboulay/PSMoveService#455]
steam is not detecting cameras or ps3 moves 
my ps moves are not lighting up and my head tracking is working but in steam vr cameras does not show up

**Comment by kswiorek** [comment]
Do you use PSMoveSteamVRBridge?

**Comment by lexvex** [comment]
yes

**Comment by lexvex** [comment]
head tracking is working i use 3th move for head tracking

**Comment by lexvex** [comment]
3rd

**Comment by lexvex** [comment]
one file was missing in psmoveservice s i reinstaled it now it works
the name of file
SteamVR_SetDriverVarsWin64.bat
