### ISSUE TITLE
Choosing between onboard bluetooth and dongle bluetooth

### ISSUE THREAD

**Issue by RavenKillz** [cboulay/PSMoveService#456]
Is there a way for me to choose from my onboard Bluetooth which if I move more than two feet away from disconnects the PlayStation move controllers to the dongle that I bought?

**Comment by cboulay** [comment]
I don't think there is a mechanism to do that in PSMoveService, nor do I think Windows supports that (or, from a quick google search, not very well). Your best bet is to disable the onboard bluetooth radio via BIOS if that's possible. Otherwise disable the unwanted device in Windows Device Manager.
