### ISSUE TITLE
move controllers and cameras off in steamvr

### ISSUE THREAD

**Issue by cule2008** [cboulay/PSMoveService#467]
I have a set up with 3 playstation eyes. Configering the controllers in the psmoveservice config tool was no problem. When I test the tracking all looks good, the controllers seem to be configered and tracked quite well. But when I open steamvr both move controllers are a bit off to the side when I define their position as steamvr tells me. Also they are loosing their orientation very fast when I move around. And I can see in the grid few that my cameras are not showing up in front of me like the are for real, but also moved to the side.
Got no clue how to solve this.

**Comment by cboulay** [comment]
Any issues related to SteamVR should be asked first in the [google group](https://groups.google.com/forum/#!forum/psmoveservice) then in [PSMoveSteamVRBridge](https://github.com/HipsterSloth/PSMoveSteamVRBridge).
