### ISSUE TITLE
PS Move controllers not detected by steam

### ISSUE THREAD

**Issue by Marsquakes** [cboulay/PSMoveService#470]
I'm using a DK2 on Windows 10 and my controllers are not showing up on steam. I've completed the room setup and have my controller (only have 1 atm as the other arrived damaged) fully set up and it tracks perfectly. **This is my current steamvr.vrsettings file:**
{
   "collisionBounds" : {
      "CollisionBoundsStyle" : 4
   },
   "keyboard" : {
      "TutorialCompletions" : 1
   },
   "psmove" : {
      "circle" : "a",
      "cross" : "button_8",
      "move" : "touchpad",
      "ps" : "system",
      "rumble_suppressed" : false,
      "select" : "button_9",
      "square" : "grip",
      "start" : "button_10",
      "triangle" : "application_menu",
      "trigger" : "trigger",
      "use_spatial_offset_after_touchpad_press_as_touchpad_axis" : true
   },
   "steamvr" : {
      "allowReprojection" : true,
      "directModeEdidPid" : 43521,
	  "forceFadeOnBadTracking" : false,
	  "activateMultipleDrivers" : true,
      "directModeEdidVid" : 53794,
      "mirrorViewGeometry" : "0 0 960 540"
   }
}

**This is my current default file:**
{
	"steamvr" : {
		"requireHmd" : true,
		"forcedDriver" : "",
		"forcedHmd" : "",
		"displayDebug" : false,
		"debugProcessPipe" : "",
		"enableDistortion" : true, 
		"displayDebugX" : 0, 
		"displayDebugY" : 0,
		"sendSystemButtonToAllApps" : false,
		"loglevel" : 3,
		"ipd" : 0.063,
		"ipdOffset" :  0.0,
		"background" : "",
		"backgroundUseDomeProjection" : false,
		"backgroundCameraHeight" : 1.6,
		"backgroundDomeRadius" : 0.0, 
		"environment" : "", 
		"gridColor" : "", 
		"playAreaColor" : "",
		"showStage" : false,
		"activateMultipleDrivers" : true,
		"directMode" : true,
		"usingSpeakers" : false,
		"speakersForwardYawOffsetDegrees" : 0.0,
		"basestationPowerManagement" : false,
		"neverKillProcesses" : false,
        "renderTargetMultiplier" : 1.0,
        "supersampleScale" : 1.0,
        "allowSupersampleFiltering" :  true,
        "allowAsyncReprojection" :  true,
		"allowInterleavedReprojection" : true,
		"forceReprojection" : false,
		"forceFadeOnBadTracking" : true,
		"defaultMirrorView" : 0,
		"showMirrorView" : false,
		"startMonitorFromAppLaunch" : true,
		"startCompositorFromAppLaunch" : true,
		"startDashboardFromAppLaunch" : true,
		"startOverlayAppsFromDashboard" : true,
		"enableHomeApp" : true,
		"setInitialDefaultHomeApp" : false,
		"CycleBackgroundImageTimeSec" : -1,
		"retailDemo" : false,
		"panelMask" : true,
		"panelMaskVignette" : true,
		"panelMaskVignetteWidth" : 2.0
	},
	"userinterface" : {
		"StatusAlwaysOnTop" : true,
		"screenshots" : true,
		"screenshotType" : 2
	},
	"notifications" : {
		"DoNotDisturb" : false
	},
	"keyboard" : {
		"TutorialCompletions" : 0,
		"ScaleX" : 1.1,
		"ScaleY" : 1.1,
		"OffsetLeftX" : 0.0,
		"OffsetRightX" : 0.0,
		"OffsetY" : 0.0,
		"Smoothing" : false
	},
	"perfcheck" : {
		"heuristicActive" : true, 
		"warnInHMD" : false,
		"warnOnlyOnce" : false,
		"allowTimingStore" : false,
		"saveTimingsOnExit" : false,
		"perfTestData" : 0.0
	},
	"collisionBounds" : {
		"CollisionBoundsStyle" : 0,
		"CollisionBoundsGroundPerimeterOn" : false,
		"CollisionBoundsCenterMarkerOn" : false, 
		"CollisionBoundsPlaySpaceOn" : false, 
		"CollisionBoundsFadeDistance" : 0.7,
		"CollisionBoundsColorGammaR" : 0,
		"CollisionBoundsColorGammaG" : 255,
		"CollisionBoundsColorGammaB" : 255,
		"CollisionBoundsColorGammaA" : 153 
	},
	"camera" : {
		"enableCamera" : false,
		"enableCameraInDashboard" : false,
		"enableCameraForCollisionBounds" : false,
		"enableCameraForRoomView" : false,
		"cameraBoundsColorGammaR" : 0,
		"cameraBoundsColorGammaG" : 255,
		"cameraBoundsColorGammaB" : 255,
		"cameraBoundsColorGammaA" : 153,
		"cameraBoundsStrength" : 78
	},
	"audio" : {
		"onPlaybackDevice" : "",
		"onRecordDevice" : "",
		"onPlaybackMirrorDevice" : "",
		"offPlaybackDevice" : "", 
		"offRecordDevice" : "",
		"viveHDMIGain" : true
	},   
	"power" : {
		"powerOffOnExit" : true,
		"turnOffScreensTimeout" : 5.0,
		"turnOffControllersTimeout" : 300.0,
        "returnToWatchdogTimeout": 0.0,
        "pauseCompositorOnStandby" :  true,
		"autoLaunchSteamVROnButtonPress" : true
   },
   "modelskins" : {
   },    
   "dashboard" : {
		"enableDashboard" : true,
		"arcadeMode" : false
   },
   "version" : "1",
   "jsonid" : "vrsettings"
}

**Comment by cboulay** [comment]
I hope you found https://github.com/HipsterSloth/PSMoveSteamVRBridge

**Comment by LinusMOGEL** [comment]
You have to do enable it in defaultsteamVR.vrsettings
