### ISSUE TITLE
Clean out

### ISSUE THREAD

**Issue by Cretkensigh** [cboulay/PSMoveService#471]
Hey I've been trying for many month and I want to know how to wipe all setting, all config for PS move service. I cant get my cameras to show up in steam despite everything working as far as I can tell. I am getting errors in the client window and best I can tell is I've messed something up and wanna start again. but every time I delete all the folder etc when I reinstall it and run the psmove service my old config comes up errors and all, any help would be great thanks
![20171023_102456](https://user-images.githubusercontent.com/33009221/31866522-4ded5adc-b7dd-11e7-8b4f-75ad37caf62c.jpg)

You wouldn't believe the trouble, even my snipping tool seems to be missing, sorry for the photo but I'm out of options at this point. there are the error I'm have, yet the psmove service works,  I can do all the calibration and test cameras etc it all works. but I can get steamvr to detect the cameras or the controllers. using driver4vr for Kinect positional tracking all works with the dk1 hmd. all I need is me hands and I'm good, any ideas?

**Comment by zelmon64** [comment]
The configuration files are stored at `C:\Users\<username>\AppData\Roaming\PSMoveService`.

**Comment by Cretkensigh** [comment]
sorted all that, I can say it working but steamvr still wont show my cameras or controllers in the lttle steamvr window, in remember then turning green and showing them in others videos, anyideas? its gotta be steam right?

**Comment by Cretkensigh** [comment]
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
[2017-10-23 11:50:25.250]: TrackerDeviceEnumerator - Skipping device (USB\VID_1415&PID_2000\b2_p8) - Operation not supported or unimplemented on this platform
[2017-10-23 11:50:25.266]: TrackerDeviceEnumerator - Skipping device (USB\VID_1415&PID_2000\b2_p8) - Operation not supported or unimplemented on this platform
[2017-10-23 11:50:25.282]: TrackerDeviceEnumerator - Skipping device (USB\VID_1415&PID_2000\b2_p7) - Operation not supported or unimplemented on this platform
[2017-10-23 11:50:25.296]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\b2_p7, camera_index=0)
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent


IS this the issue?

**Comment by Cretkensigh** [comment]
I'm all be certain now its steam, the camera or the controller don't seem to be talking with steam.

**Comment by RUNF0RIT** [comment]
Me and you many be having the same problem, I can't get any of my controllers & cameras to show up. getting this error on the psmoveservice
![capture](https://user-images.githubusercontent.com/33049222/31926235-d3938bd2-b8d4-11e7-9350-7c78bc170472.PNG)

**Comment by Cretkensigh** [comment]
I down graded the psmove drivers to 0.9 alpha 8.1.0 and done a reinstall of the move service including calibration etc. seems to have done to the trick as steam now sees all cameras and controllers.

I can only assume the errors are not that bas as the psmove services still worked and tracked etc while in the psmove config tool.

**Comment by Vetoh** [comment]
i have the same problem..
