### ISSUE TITLE
PS Move Controllers not showing in Steam VR

### ISSUE THREAD

**Issue by RUNF0RIT** [cboulay/PSMoveService#472]
Only my Pimax 4k show up on steam vr without any controllers or cameras. I test all my camera there all work fine and all my controllers show up in the config tool. 
steamvr.vrsettings
{
	"psmove": {
		"circle": "a",
		"cross": "button_8",
		"meters_per_touchpad_units": 0.075000002980232239,
		"move": "touchpad",
		"ps": "system",
		"rumble_suppressed": false,
		"select": "button_9",
		"square": "grip",
		"start": "button_10",
		"triangle": "application_menu",
		"trigger": "trigger",
		"use_spatial_offset_after_touchpad_press_as_touchpad_axis": true
	},
	"steamvr": {
		"activateMultipleDrivers": true,
		"mirrorViewGeometry": "0 0 1209 746"
	}
}
is anyone else having this problem and know how to fix it?

also i'm getting this error on PSMoveService log
![capture](https://user-images.githubusercontent.com/33049222/31926252-f9fcf25e-b8d4-11e7-832c-7513729cdc40.PNG)

**Comment by RUNF0RIT** [comment]
Got it to work.

**Comment by Cretkensigh** [comment]
Howd you get it working man, no ones replied to my issue and from what you sent me we are in the same boat. What version of psmove you using? Do you know how to get the steamvr bridge working? Please im so tired and frustrated.
