### ISSUE TITLE
Create an installer for PSMoveService

### ISSUE THREAD

**Issue by HipsterSloth** [cboulay/PSMoveService#477]
Creating an issue to track the working being done on the installer by @gb2111.

I just checked in the following change related to Greg's efforts:
https://github.com/cboulay/PSMoveService/commit/4600f20f2eda3b2d6db3f53b757923d396b7f8e5
* Files are now copied to ${ROOT_DIR}/install/${ARCH_LABEL}/<CONFIGURATION> instead of ${ROOT_DIR}/${PSM_PROJECT_NAME}/${ARCH_LABEL}/<CONFIGURATION> when running the "INSTALL" project
  - This will make it easier for the installer script to find the output build files
* Fixed issue with BuildOfficialDistribution.bat script failing to find OpenCV cmake files

**Comment by gb2111** [comment]
hi,
it can be tested on my fork:
https://github.com/gb2111/PSMoveService

let me know if there is better way to let you test.

you need download Inno Setup to compile setup
https://github.com/gb2111/PSMoveService

the script is here
misc/installer/installer_win64.iss

setup PSMoveService-Setup64.exe will be created in 'installer' folder.

i create few shortcuts, not sure if that is good idea

this is bery basic version so fi you think we need more please let me know.

**Comment by HipsterSloth** [comment]
Closing this issue since we now have an Inno Setup based installer
