### ISSUE TITLE
[OS X] Consistent interruptions to communication between client and server

### ISSUE THREAD

**Issue by cboulay** [cboulay/PSMoveService#48]
The communication is good for 5 seconds then off for 5 seconds, repeat ad infinitum. The config tool is still responsive during the off time, as in the buttons still do things, but I often encounter a window that says, "Waiting for X to stop..."

I first noticed this when testing the tracker video feed, then also noticed it while accumulating points while calibrating the magnetometer.

**Comment by cboulay** [comment]
edit: Same behaviour after restarting the service with camera unplugged, so it's not the camera.

**Comment by cboulay** [comment]
Tested the same hardware on my Windows PC and everything worked fine.

**Comment by HipsterSloth** [comment]
I wonder if it's the polling for new device connections that's killing it. Maybe creating a new udb device iterator every few seconds can get hung up on some blocking query? You could test this by setting the poll timeout on the device managers to something much longer and see if the issue persists.

**Comment by cboulay** [comment]
OK now it's not happening. My OS did an update since last night. Other than that I don't know what else changed. Closing for now because we have other things to work on and shouldn't spend time on a problem that can't be reproduced.
