### ISSUE TITLE
INVERTED,LAGGY AND WRONG POTISION PS MOVE CONTROLLS IN STEAMVR

### ISSUE THREAD

**Issue by bobost2** [cboulay/PSMoveService#483]
When I start the calibration tool and configure everything the tracking pose is working smoothly, but when I move the first controller foward, it moves left and the seccond controller is inverted. In SteamVR its inverted, laggy and at the wrong position.
--------------------------------------------------------------------------
My setup:
deepoon e2 (works perfect) 
2 ps3eye cameras :    First is 163 cm high and the seccond is 160 cm high. The distance of each other is 180 cm. and my free space from the cameras are 220x140 cm
--------------------------------------------------------------------------
I tried:
1. Recalibrating the controllers. (On the magnemeter recalibration I calibrated 1 minute after 100% to fill all sphere with dots)
2. Turning off the lightes in my room and recalibrated color calibration and traking pose with the calibration mat
3. In SteamVR Start+Select with all combinations possible.
----------------------------------------------------------------------------
video (MY HMD DOESN'T WORKING AT THIS VIDEO AND THE CONTROLS ARE started+selected on the head):

https://www.youtube.com/watch?v=qYULxC94c2w&feature=youtu.be
----------------------------------------------------------------------------
[PsMove appdata content.zip] - uploaded before capturing the videos
(https://github.com/cboulay/PSMoveService/files/1485514/PsMove.appdata.content.zip)

**Comment by bobost2** [comment]
please help me fast

**Comment by bobost2** [comment]
Fixed! I buyed another camera and maded the calibration again at correct angle and added 10fps.

**Comment by AlexTheTech** [comment]
wait so all you did was add another camera and it worked fine? Did you add it to the back of the setup?
