### ISSUE TITLE
"No connected usable controllers."

### ISSUE THREAD

**Issue by qwFaTE** [cboulay/PSMoveService#494]
Hey!

I'm on Windows 7, attempting to setup my DK2 with PSmove controllers.
When plugging them in, the config menu should refresh and show an option to pair them with my PC.
But it doesn't.
It doesn't even refresh.
It stays on "No connected usable controllers" just as if I haven't plugged the move in at all.

Help, I'm not sure what to do.

**Comment by shenmohao** [comment]
have u sloved this problem?

**Comment by qwFaTE** [comment]
Yeah, turns out they simply weren't charged enough. Still haven't gotten them working though, due to the drivers saying that powershell doesn't exist.
