### ISSUE TITLE
PSMOVE Controllers won't Connect to Bluetooth or the Psmoveservice  Help?

### ISSUE THREAD

**Issue by purpxog** [cboulay/PSMoveService#502]
Model : CECH-ZCM2N  - how can i connect to pc? any alternatives? thanks.

**Comment by purpxog** [comment]
Any Help? please i just wanna play vr

**Comment by purpxog** [comment]
is there any other type of PROGRAM I CAN USE TO USE VR MOVE ON MY PC :(

**Comment by cboulay** [comment]
#512
