### ISSUE TITLE
PSMoveFreePieBridge Instant Crash

### ISSUE THREAD

**Issue by swedishdragon** [cboulay/PSMoveService#516]
Hey!
I recently built a glowing ping-pong ball for head tracking, when I was ready to test it and had done all configurations in PSMove configuration tool and got it tracking correctly, I couldn't launch PSMoveFreepieBridge, which obviously is necessary to translate the movement into a free track position.

What could cause this? I've tried putting the extracted folder on my primary drive, two different external hard drives, admin rights turned off and on, PSMoveService running/not running, Freepie running/not running, but no luck. As soon as I open the .exe I get the "not responding..." instantly..

Any help would be greatly appreciated!
Also, I'm not sure what kind of logs that would be helpful since in my understanding, FreepieBridge should at least launch without any other programs running.

**Comment by cboulay** [comment]
Please ask here: https://github.com/HipsterSloth/PSMoveSteamVRBridge
