### ISSUE TITLE
"system" button no longer functional after PSNavi setup.

### ISSUE THREAD

**Issue by dude22072** [cboulay/PSMoveService#519]
After setting up a PSNavi controller to use with PSMoveService no matter which button I map as "system" in steamvr.vrsettings none of them will open the menu.

**Comment by dude22072** [comment]
This issue ended up being caused by a SteamVR update. The fact that it happened the same time as I setup my PSNavi was coincidental.

**Comment by Vininess** [comment]
Hey i got the same problem, how do you managed that the button work again?

**Comment by dude22072** [comment]
Go to your tools library and under SteamVR's properties go to the betas tab and choose the one with openvr in its name.
