### ISSUE TITLE
[question] bind two buttons?

### ISSUE THREAD

**Issue by aliez3331** [cboulay/PSMoveService#522]
sorry for bad english

i'm trying to mapping buttons to VRchat,
i want to use two buttons to make a new command( like trigger + circle and make a gesture for example) and change reset camera button(because this mute and block all in game)

my steamvr.cfg

  },
  "psmove": {
    "meters_per_touchpad_units": 0.075000002980232239,
    "move": "touchpad",
    "ps": "system",
    "rumble_suppressed": true,
    "select" : "grip",
    "start" : "application_menu",
    "trigger": "trigger",
    "use_spatial_offset_after_touchpad_press_as_touchpad_axis": true
  },
  "psmove_touchpad_directions": {
    "circle": "touchpad_right",
    "cross": "touchpad_left",
    "triangle": "touchpad_up",
    "square": "touchpad_down"
  },
  "steamvr": {
    "activateMultipleDrivers": true,
    "defaultMirrorView": 1,
  }
}

**Comment by cboulay** [comment]
For SteamVR-related questions, please first post on the google group and if you can't get help there then try [PSMoveSteamVRBridge](https://github.com/HipsterSloth/PSMoveSteamVRBridge).
