### ISSUE TITLE
pseye not working on high speed usb ports

### ISSUE THREAD

**Issue by nightttide** [cboulay/PSMoveService#523]
My pseye camera is detected fine when I plug it into a usb 2.0 it shows up in camera test but when I move it to usb 3.0 or a c type usb it won't get detected by the camera test. Anybody know whats going on?

**Comment by cboulay** [comment]
You probably have to install the drivers AGAIN whenever you plug it into a new USB controller for the first time.

FYI, you're not going to get any better performance by plugging it into a high speed port. It's tempting to think that a high-speed port will have more overhead and therefore work better with a USB 2.0 device, but when you plug a USB 2.0 device into a high speed port you're basically downgrading (temporarily) that port to a 2.0 port.

**Comment by nightttide** [comment]
I just tried replacing the driver with zadig and it didn't work. The reason I have to use usb 3.0 is because all my usb 2.0 ports are used by 4 other pseyes. Only the usb 3.0 one is pluged in right now though

**Comment by cboulay** [comment]
Is there anything else plugged into the ports sharing that USB host controller/root hub, especially something that might be drawing significant bandwidth or power? Also, not all USB hosts are created equal. I don't have any specific information for you other than to say that I have some USB ports (on a common host) that will never work with the PSEye for whatever reason, but adjacent ports (on a different host) work fine.

**Comment by nightttide** [comment]
I tried with nothing plugged in other than the camera and still not working. I guess it just won't work with it
