### ISSUE TITLE
Unable to open Steam overlay.

### ISSUE THREAD

**Issue by dan2wik** [cboulay/PSMoveService#524]
I'm unable to open the steam overlay but I'm able to do everything else just fine. I can load into SteamVR Home and launch and play a game. Everything else is working perfectly and I've been impressed by it so far.

When transitioning between games, the overlay pops up for a split second showing gamepad buttons on the interface, A, B, etc. I do not have a gamepad plugged in or listed in the game controllers list either.

This is my steamvr.vrsettings
```{
{
  "audio": {
    "onRecordDevice": "{0.0.1.00000000}.{0c87bb37-58b6-4254-9bbe-06b5cf709002}"
  },
  "driver_vridge": {
    "fakeSensorEnabled": false,
    "renderScale": 100,
    "windowHeight": 1080,
    "windowWidth": 1920
  },
  "psmove": {
    "circle": "a",
    "cross": "touchpad_touched",
    "meters_per_touchpad_units": 0.075,
    "move": "touchpad",
    "ps": "system",
    "rumble_suppressed": false,
    "select": "button_8",
    "square": "grip",
    "start": "button_8",
    "triangle": "application_menu",
    "trigger": "trigger",
    "use_spatial_offset_after_touchpad_press_as_touchpad_axis": true
  },
  "steamvr": {
    "activateMultipleDrivers": true,
    "defaultMirrorView": 2,
    "mirrorViewGeometry": "1102 101 789 886",
    "showMirrorView": true
  }
}

**Comment by cboulay** [comment]
Please ask any steam related questions here: https://github.com/HipsterSloth/PSMoveSteamVRBridge
