### ISSUE TITLE
Multiple users having the same issues please help or fix, wih pairing move controlers 

### ISSUE THREAD

**Issue by lewilou22** [cboulay/PSMoveService#527]
When pairing move controllers , The service does not recognize the controllers at all, but the PC sees them as move controllers. I am using a CSR 4.0 blue tooth adapter. I have seen others in here with he same issues. please help, I have purchased all his hardware and its frustrating that it wont work!

**Comment by lewilou22** [comment]
Also reading people have issues with the new micro usb ones, is there a fix?

**Comment by Cretkensigh** [comment]
I had some serious trouble find a bluetooth dongle that would work with the playstation hardware, must have gone through 4 or 5 different brand and chipsets before giving up and just buying the bt400. Worked straight away and was smooth sailing after that.

**Comment by aliez3331** [comment]
on my pc only recognize and charge on usb 3.0, using bluetooth 2.0

**Comment by Cretkensigh** [comment]
But does it pair with the psmove service? When i plug the psmove controllers the pc does see them and charges but will not talk to them unless i have the dongle plugged in

**Comment by Cretkensigh** [comment]
It all comes down to the chipset. I believe is have something to do with the atheros/BCM20702 uses. CSR or broadcomm both use it in some of there dongles.

**Comment by dethmasta** [comment]
these new CECH-ZCM2U model move controllers that came with skyrim vr will not show up at all on psmoveservice. even with the bt-400.

**Comment by linuxdotpy** [comment]
Thank you dethmasta for pointing that out with the skyrim bundle, which is what I have and saved me from buying bt-400. Have you found a solution yet?

**Comment by cboulay** [comment]
If it's a new controller, please follow #512 
If it's an old controller, please try different bluetooth adapters. Windows is picky.

If you're one of the 'multiple users' and you're using Mac or Linux, then please open a separate issue with that in the title.
