### ISSUE TITLE
Unable to open SteamVR dashboard with PSmove controllers

### ISSUE THREAD

**Issue by kitch907** [cboulay/PSMoveService#528]
I am unable to open up the SteamVR dashboard in SteamVR. I made sure that the option to enable the dashboard was checked in the settings. When I'm in SteamVR, I press the PS button and nothing happens. In the lobby I can access the Lobby Menu (via the Triangle button on the PSmove), I am able to move around with the Move button, pick up things, etc, but the PS button doesn't do anything. Here are my steamvr.vrsettings:

{
   "driver_vridge" : {
      "fakeSensorEnabled" : true,
      "hmdMode" : 0,
      "renderScale" : 120,
      "windowHeight" : 936,
      "windowWidth" : 1664
   },
   "psmove" : {
      "circle" : "a",
      "cross" : "button_8",
      "meters_per_touchpad_units" : 0.075000002980232239,
      "move" : "touchpad",
      "ps" : "system",
      "rumble_suppressed" : false,
      "select" : "button_9",
      "square" : "grip",
      "start" : "button_10",
      "triangle" : "application_menu",
      "trigger" : "trigger",
      "use_spatial_offset_after_touchpad_press_as_touchpad_axis" : true
   },
   "psmove_settings" : {
      "disable_alignment_gesture" : true,
      "psmove_extend_z" : -0.075000002980232239,
      "use_orientation_in_alignment" : false
   },
   "psmove_touchpad_directions" : {
      "circle" : "touchpad_down",
      "cross" : "touchpad_up"
   },
   "steamvr" : {
      "activateMultipleDrivers" : true,
      "allowInterleavedReprojection" : false,
      "background" : "#0D0D0DFF",
      "defaultMirrorView" : 2,
      "enableHomeApp" : false,
      "mirrorViewGeometry" : "0 0 960 540",
      "showMirrorView" : true
   },
   "userinterface" : {
      "StatusAlwaysOnTop" : false
   }
}

I've tried other peoples steamvr.vrsettings configurations just by copy/pasting, but still no results.

I can plug in my dualshock4 controller and open the SteamVR Dashboard if I do NOT have PSMoveService running. I tried having PSMS running and having my DS4 hooked in at the same time, and I cannot open up the dashboard in SteamVR with either device.

**Comment by dude22072** [comment]
Hover over ""Library" and choose "VR". Right-click SteamVR and choose properties. Go to the BETAS tab and choose "openvr-inputemulator-temporary" and see if this fixes the issue.

**Comment by SuperEvenSteven** [comment]
I'm looking into this over at PSMoveSteamVRBridge since this isn't an issue with PSMoveService but rather a change that OpenVR implemented to their input system.

**Comment by cboulay** [comment]
Please ask at https://github.com/HipsterSloth/PSMoveSteamVRBridge
