### ISSUE TITLE
psmoveservice doesn't recognize my psmove controllers

### ISSUE THREAD

**Issue by BernieGustavo** [cboulay/PSMoveService#531]
The camara works fine, I have a psnavi and it works fine. I open up controller settings and I see psnavi controller 0. Yet I don't have anything connected
![capture](https://user-images.githubusercontent.com/37877197/38042088-61b2e464-3281-11e8-950d-d8e538e0e3fe.PNG)
I think this problem may have to do with the fact that I accidentally installed  the incorrect drivers onto the psmove controllers. I tried to fix it by connecting the psnavi and seeing what drivers that had. Then installing them onto the psmove. This may also have to do with me having scptoolkit, although I doubt it.

**Comment by BernieGustavo** [comment]
![capture 2](https://user-images.githubusercontent.com/37877197/38042317-0cb0163e-3282-11e8-9116-a994b4652084.PNG)

**Comment by craftxbox** [comment]
Issue #512?

**Comment by insutine12** [comment]
@BernieGustavo Hey, I think for the new generation of PSMove(CECH-ZCM2G), the original Driver is HidUsb (v10.0.17134.112) as shown below. If I replace the HidUsb driver to WinUSB driver, do you think I cannot restore to HidUsb, and also I cannot connect the move with PS4PRO again?

![image](https://user-images.githubusercontent.com/40644381/41998915-e781cc9c-7a96-11e8-9996-12158fde53cd.png)

If there is a way to rollback the driver, then I will try :))

**Comment by cboulay** [comment]
For the new generation of psmove controllers, there is no solution yet so please follow #512 

The drivers installed with Zadig are installed to Windows, not the controller. It only affects how Windows will see the controllers. It won't affect how the PS4 sees the controllers. The process of pairing does actually write something onto the controller's memory, but the code for the old controller doesn't work with the new controller and it's unclear if attempting to pair a new controller does anything that will interfere with re-pairing with the PS4, so it's best to hold off on that until this is resolved.
