### ISSUE TITLE
PsMove+Headset=Lag

### ISSUE THREAD

**Issue by TavarguesEN** [cboulay/PSMoveService#543]
Hi! So I have a issue that every time I play without my headset (Xiaomi VR+Phone), the controller are responding great without lag or any kind of issues, but when I connect the Heasdet with the controllers, they have a high latency/lag. To connect the headset I use TrinusVR (more lag/latency), iVRy (lag/latency lower but still).Can't use Vridge (for me doesn't works).

As I said tracking system :Excellent without headset.
With Headset on:Lag/Latency and tracking issues (ps move controllers).

**Comment by cboulay** [comment]
I know this answer is quite late but there might be others who see it in the future.
Sorry unless you can isolate a problem in PSMoveService itself, we can't help you here. I've never used any of those other apps.
Try the google group where there are several helpful people who use a wide array of different apps.
