### ISSUE TITLE
Button mapping PSNavi

### ISSUE THREAD

**Issue by timer23** [cboulay/PSMoveService#546]
Is it possible to emulate stick PSNavi as a touchpad Vive. So when you movement the stick was emulating touch touchpad. And when you click on the stick + movement emulated pressing the touchpad. прошу прощения за гугл переводчик

**Comment by potatoE2** [comment]
@timer23 here is the solution...
Copy my code and open a new window for Notepad and paste it in there, then click **Save As,** and name the file `steamvr.vrsettings` and click save. Right click the file, click on properties and check the box called **Read Only** and click Apply and Ok.
Go to your steam folder directory, it should look like this: 
`C:\Program Files (x86)\Steam\config`
Move the `steamvr.vrsettings` file into there.
Hope this helped  :)
## **Copy this code!**

{
   "driver_vridge" : {
      "fakeSensorEnabled" : false,
      "renderScale" : 100,
      "windowHeight" : 1440,
      "windowWidth" : 2560
   },
   "keyboard" : {
      "TutorialCompletions" : 1
   },
   "psmove" : {
      "circle" : "a",
      "cross" : "button_8",
      "meters_per_touchpad_units" : 0.075000002980232239,
      "move" : "touchpad",
      "ps" : "system",
      "rumble_suppressed" : true,
      "select" : "button_9",
      "square" : "grip",
      "start" : "button_10",
      "triangle" : "application_menu",
      "trigger" : "trigger",
      "use_spatial_offset_after_touchpad_press_as_touchpad_axis" : true
   },
   "psmove_settings" : {
      "psmove_filter_hmd_serial" : "04:76:6e:c0:8b:d6"
   },
   "psnavi_button" : {
      "circle" : "application_menu",
      "cross" : "system",
      "l1" : "grip",
      "l2" : "trigger",
      "l3" : "touchpad",
      "trigger" : "trigger"
   },
   "psnavi_touchpad" : {
      "dpad_down" : "touchpad_down",
      "dpad_left" : "touchpad_left",
      "dpad_right" : "touchpad_right",
      "dpad_up" : "touchpad_up"
   },
   "steamvr" : {
      "activateMultipleDrivers" : true,
      "defaultMirrorView" : 1,
      "mirrorViewGeometry" : "1249 473 1240 1165",
      "renderTargetMultiplier" : 1.7000000476837158
   }
}

**Comment by cboulay** [comment]
If this didn't solve your problem then maybe this is something better asked on the google group or at https://github.com/HipsterSloth/PSMoveSteamVRBridge
