### ISSUE TITLE
How to compile the project

### ISSUE THREAD

**Issue by toto5100** [cboulay/PSMoveService#55]
Hello,
I'd like to try out the new PSMove Service you made, but i'm struggling with compiling the project.
I follow the steps mentionned in readme, but when i launch "InitialSetup.bat" and set the two folders directory, i have either a missing vcvarsall.bat or this : http://i.imgur.com/yIuMriv.jpg
Because some part are in french, here is a translation : 
- first line : Unable to find D:\PSMoveService-master\SetBuildVars.bat
- error MSB1009 : The project file does not exist.
Thanks for your help.

**Comment by cboulay** [comment]
When you cloned the project, did you do --recursive? At least one of your errors in the screenshot is due to not finding something in a submodule.

**Comment by toto5100** [comment]
i don't know, i just clicked on download zip

**Comment by HipsterSloth** [comment]
So it turns out the source download zip doesn't include submodules (i.e. everything in the thirdparty folder). This is actually a known issue with github (we don't generate the zip). So if you want to build yourself you'll want to:

1) Download [github desktop](https://desktop.github.com/)
2) Do a recursive clone of the repo: https://github.com/cboulay/PSMoveService.git

**Comment by toto5100** [comment]
It seemed to work, everything looked good until the end : http://i.imgur.com/hizkz66.jpg
It looks like a problem with version of cmake. What version should i use (i installed the last one, 3.6 ) ?

**Comment by HipsterSloth** [comment]
Have you tried deleting everything in the `/build` folder and then re-running the InitialSetup.bat and GenerateProject.bat? I'm downloading cmake 3.6 now to make sure it didn't break something. I was using cmake 3.3 previously.

**Comment by toto5100** [comment]
Yes i tried, but same error. Also, in the begginning, it's written that "Microsoft Visual Studio 12.0\VC\vcvarsall.bat" is not recognized as an internal or external command, un executable or a command file. I found that Visual Studio 12.0\VC folder is missing this file. But it is present in Visual Studio 11.0's folder...

**Comment by cboulay** [comment]
We can get around the zip file problem if we change all the submodules over to using [subtrees](http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/).

If not that, then we need to make it explicitly clear in the Wiki/FAQ that you either need to download a pre-compiled release or download the source using git --recursive.

**Comment by HipsterSloth** [comment]
Oh do you have visual studio 2013 installed?

**Comment by toto5100** [comment]
Yes (visual studio express 2013 and visual studio 2013 sdk), and i also tried to reinstall them multiple times, but the file is still missing.
I tried to copy vcvarsall.bat from Visual Studio 11 folder to Visual Studio 12, but it seems to work but it shows this in the beggining : http://i.imgur.com/jCuStoM.jpg

**Comment by HipsterSloth** [comment]
@toto5100 Ahh ok. That's weird that file was missing. I just installed the community edition of 2013 and it had that batch file. You can do the same thing the InitialSetup.bat file does and do the manual build steps (build steps 6, 7, and 8 in the README.md). In particular, I'd be curious if step 6 (the protobuf library building) works for you.

**Comment by zelmon64** [comment]
I installed VS community edition 2013 to build this project with as well and had no errors. Looking at [the website](https://www.visualstudio.com/en-us/products/visual-studio-express-vs.aspx):

> Visual Studio Community has all the features of Express and more

so perhaps that's what they added?

**Comment by toto5100** [comment]
I tried manually, and it works. I managed to build the project. Thanks
