### ISSUE TITLE
Is psmoveservice going to update to allow new controllers?

### ISSUE THREAD

**Issue by airfusion81** [cboulay/PSMoveService#550]
Just a quick question for the people with the new PS move controllers.

**Comment by saadminhas** [comment]
I really hope it does, 
Because the old controllers are quite hard to find these days.

**Comment by cboulay** [comment]
It's an open source project. We welcome pull requests with this addition.

I don't have a new controller or the time to develop and test.

**Comment by dude22072** [comment]
Please look through open issue to prevent duplicates.
#512

**Comment by HipsterSloth** [comment]
Closing this dupe issue in favor of #512
