### ISSUE TITLE
How do I snap my HMD to the left or right? (please help)

### ISSUE THREAD

**Issue by potatoE2** [cboulay/PSMoveService#551]
If you are reading the title and misunderstood my question, let me explain.
I have 2 PsEye Cameras that are on my desk facing me. If I turn around with my HMD in VR my Ps Move controllers go out of view they spazz out. I was wondering if I could snap my HMD to the left or right by pressing a button on my Ps Move Controller without having to physically turn around. What I mean by "snapping" is to virtually move the HMD either left or right without physically moving it.
You're probably wondering... "Why don't you get 2 more Ps Eye cameras? " I can't because I don't have space for 2 more Ps Eye Cameras.

Is it possible to snap my HMD to the left or right by pressing a button on my Ps Move controller?

Looking forward to an answer,
-N.B

**Comment by iamapie13** [comment]
get Driver4VR it has that function to virtually rotate, I use it in my set up

**Comment by potatoE2** [comment]
Thank you! I will definitely try Driver4 VR out!
