### ISSUE TITLE
New PS Move Controllers Not Connecting Via USB

### ISSUE THREAD

**Issue by Pestilience** [cboulay/PSMoveService#554]
how high on the priority list is support for the new ps move controllers?  eg CECH-ZCM2G

**Comment by cboulay** [comment]
It's my #1 priority for PSMoveService.
Unfortunately, PSMoveService is priority #73 in my life right now.

That being said, it's an open source project. Anyone can fork, add support, then make a pull request so the whole community benefits.

This question didn't really need a new issue, did it?
