### ISSUE TITLE
unresponsive steamvr home

### ISSUE THREAD

**Issue by arifsolmaz35** [cboulay/PSMoveService#555]
![aa](https://user-images.githubusercontent.com/39708463/41196062-3165f824-6c41-11e8-92a3-cf2f40d05a10.PNG)
![aaa](https://user-images.githubusercontent.com/39708463/41196063-31878106-6c41-11e8-8ee3-2ecd28471ec5.PNG)

**Comment by arifsolmaz35** [comment]
help me please !

**Comment by cboulay** [comment]
I've never used PSMoveService with SteamVR bridge. I have no idea what I'm looking at.

Try the google group first. https://groups.google.com/forum/#!forum/psmoveservice
Then try here: https://github.com/HipsterSloth/PSMoveSteamVRBridge
