### ISSUE TITLE
Friends please help. Move controller does not stop properly, constantly disappears, does not stop constantly

### ISSUE THREAD

**Issue by arifsolmaz35** [cboulay/PSMoveService#556]
Friends please help. Move controller does not stop properly, constantly disappears, does not stop constantly

video down

https://www.youtube.com/watch?v=1rStz36mWnU&t=3s

**Comment by cboulay** [comment]
You're going to have to post a question on the [PSMoveSteamVRBridge](https://github.com/HipsterSloth/PSMoveSteamVRBridge) page or create a video that uses the config tool only and also give lots of logs and other details.
