### ISSUE TITLE
Use different camera other than PS3 Eye

### ISSUE THREAD

**Issue by Ghostpepper123** [cboulay/PSMoveService#563]
Hello everyone, I believe for PSMoveService you have to use the PS3 Eye camera, but the field of view isn't that great because it's only 75 degrees on blue mode.  Is there a way to use phone cameras, a higher FOV webcam, and a built in webcam all together for PSMove tracking?  

I mean, these are cameras.  Some are higher resolution or higher framerate, but they are all some kind of pixel input feeding into the software, so I'd imagine we'd be able to use virtually any camera we want for input, as long as we have the drivers, obviously.  

Also, does anybody know about the weird controller pose coordination system? I got the controller pose messed up because I didn't know what the +x+z location meant, for example. Does anybody know about this? Thanks!
Edit: Just read through the Issues on here. Probably should have done that earlier. I realized there is already a discussion about non ps3 eye cameras

**Comment by craftxbox** [comment]
#534
