### ISSUE TITLE
PS Move + Navigation Controller joiner solution 

### ISSUE THREAD

**Issue by The-Math-God** [cboulay/PSMoveService#568]
hi i found the most awesome PS move + navi controller joiner on Thingiverse.
It is based on the dualplay a canceled ps move accessory by playhouse entertainment.
i was able to get the one from Thingiverse + the parts for a 2nd minus the sharpshooter from its creator on Etsy. But i found something else. So I am selling it on eBay here's links to everything I mentioned.

My eBay listing
https://www.ebay.com/itm/302828605984

OG dualplay
https://www.youtube.com/watch?v=YudY652Wdpc

DIY dualplay
https://www.thingiverse.com/thing:2790654

Creators Etsy & twitter pages
http://petropixel.etsy.com & https://twitter.com/petropixel

**Comment by craftxbox** [comment]
this isnt an issue.

**Comment by dude22072** [comment]
Literally a spam advertisement
