### ISSUE TITLE
PS move can not connect to a PS move service with a cable

### ISSUE THREAD

**Issue by Gonyczz** [cboulay/PSMoveService#572]
Hello,
Yesterday I bought a new PS move, but after watching all the tutorials, I am unable to pair the driver with a cable in the PS move service. In the PC, I see a PS move connected as a "Motion Controller," but PS move service does not work.

TYPE: Cech-ZCM2E (Micro USB)
Bluetooth: BT-400

Thank you for your help

**Comment by HipsterSloth** [comment]
The ZCM2 is the newer model PSMove controller that isn't supported yet. We are working on it though and have the following issue tracking the problem:

https://github.com/cboulay/PSMoveService/issues/512

**Comment by Gonyczz** [comment]
Thank you. Do not you know when will it be launched? I'm thinking of returning goods and buying old drivers. Or do I prefer to wait? Thank you

**Comment by HipsterSloth** [comment]
It's difficult to say because this is something I work on in my free time after work. We are most of the way along. At this point I just need to finish the gyro calibration and smoothing out the bluetooth pairing process. Somewhere between a week and a month? If you wanted to get up an running right away I would just get an earlier model controller.

**Comment by Gonyczz** [comment]
I understand, you are doing a great job for a game audience. I do not want to buy an old PS move and have a new one but I would like to play :) Is there any way to get around it? Do you need pairing with bluetooth? Thank you

**Comment by Rain343** [comment]
This is a temporary solution. PSMoveService is connected to controllers, but gyro calibration does not work yet. Still Steam does not see them. Maybe there also need new drivers for it.
[PSMoveService-ZCM2U [custom].zip](https://github.com/cboulay/PSMoveService/files/2333399/PSMoveService-ZCM2U.custom.zip)

**Comment by Gonyczz** [comment]
I have tried a new PS move service. Finally, after the USB connection, the PS move appeared in the pairing program. Sorry, I still can not finish pairing. What type of PS move is now good and functional? Thank you
