### ISSUE TITLE
PS move button problem and tracking in Steam VR

### ISSUE THREAD

**Issue by Gonyczz** [cboulay/PSMoveService#574]
Hello.,
I'm already desperate. I'm trying to run PS move on Steam Vr for 3 days :( I have the drivers set up, paired and calibrated, but I still have problems with SteamVR.

Freepie does not work as it should. It follows pinpong ball but also one PS move. How can I solve this problem?
Driver orientation is still out of body. I think it's a pinpong ball and PS move problem that track head tracking.
I'm still updating and overwriting steamvr.vrsettings and I can not add buttons here. Now the buttons do not work.
I use:
Vridge (latest version)
Steam VR (Latest Version)
PS move PS3 with mini usb
Last - PSMoveSteamVRBridge
Last- Freepie
Last - PSMoveFreepieBridge-Release15

I've calibrated everything (by videos on youtube)
My steamvr.vrsettings:
{
   "GpuSpeed": {
      "gpuSpeed0": 336,
      "gpuSpeedCount": 1,
      "gpuSpeedDriver": "24.21.13.9907",
      "gpuSpeedHorsepower": 336,
      "gpuSpeedRenderTargetScale": 1.5199999809265137,
      "gpuSpeedVendor": "NVIDIA GeForce GTX 1060 6GB"
      "gpuSpeedVersion": 2
   },
   "driver_vridge": {
      "fakeSensorEnabled": true,
      "fovValues": "37.78 41.33 44.89 44.89",
      "hmdMode": 0,
      "renderScale": 100,
      "useDefaultFov": true,
      "windowHeight": 1440,
      "windowWidth": 2560
   },
   "steamvr": {
      "installID": "14353893826071132617",
      "mirrorViewGeometry": "0 0 1280 720",
      "supersampleScale": 1.5199999809265137
   }
}

Thank you very much

**Comment by cboulay** [comment]
I've never used PSMoveService with SteamVR. Please ask in the google group then ask in PSMoveServiceStreamVRBridge.
