### ISSUE TITLE
Can't use 2 PSMove controllers while one of them is charging

### ISSUE THREAD

**Issue by 10c8** [cboulay/PSMoveService#575]
One of my PSMoves has a dead battery, so I did the following to pair it to my computer:
1. Connect it to the PC via USB.
2. Start the pairing process.
3. Unplug it from the PC and plug it to my Xbox One (only thing that charges it other than the PC).
4. Finish pairing.

After that it connects normally to the PSMoveService while charging. If I have that controller connected alone, it works fine. The problem starts once I turn on the second PSMove.
It works for 3-5 minutes, then I get this error:
![image](https://user-images.githubusercontent.com/2660859/45246966-a4111e00-b2da-11e8-86b3-8ca45902a025.png)
(It says `HID ERROR: The device is not connected.`)

I've noticed that when I connect the controller that was paired while charging (on the Xbox One, not the PC), this shows up in the log:
![image](https://user-images.githubusercontent.com/2660859/45246987-d753ad00-b2da-11e8-9eb5-ac67ce134efa.png)

While the other one shows no errors:
![image](https://user-images.githubusercontent.com/2660859/45247022-15e96780-b2db-11e8-8c63-fafacc7597af.png)

So it seems that the controller that was unplugged from the PC, but was still plugged to something during pairing, doesn't send its state.

**Comment by 10c8** [comment]
I've tried changing the order and if I connect the one that's charging first, then the other one, the second controller shows the `Failed to open read initial controller state after 10 attempts` error.

**Comment by 10c8** [comment]
After a lot of experimenting I know that the controllers are set up correctly, at least through **PSMoveConfigTool**.

### My tests:
_I'll call the "normal" controller **A**, and the one that only turns on when powered via USB with data (PC/Xbox One), **B**._

- **Just A connected**: Works fine.
- **Just B connected**: Works fine.
- **A connected, then B**: Works fine for ~30 seconds then both controllers turn off.
- **B connected, then A**: Same as above.

**Comment by HipsterSloth** [comment]
I posted a response in the google group. Closing this issue and continuing the discussion there.
