### ISSUE TITLE
Trouble even getting the settings to come up regardless of whats plugged in!

### ISSUE THREAD

**Issue by joshua1029384756** [cboulay/PSMoveService#579]
So I got the full deal, move cameras, old PSmove controllers, the whole thing as well as the headpiece working. However when I follow the instructions to the letter but it came up with the 'Connect: Localhost Server Address" stuff. I heard it's supposed to take you to the menu regardless of whats connected so I removed everything one at a time and it still came up with that! So I uninstalled and installed a different version of the service and it's still coming up with that! Please help!

**Comment by HipsterSloth** [comment]
Did you start running PSMoveService.exe before running the config tool? If you are unable to connect to PSMoveService in the config tool, then PSMoveService might not be able to bind to its default network port of 9512. You can try changing that port here: 

C:\Users\<username>\AppData\Roaming\PSMoveService

Also, for support questions please post those in the Google group:
https://groups.google.com/forum/#!forum/psmoveservice

If we determine that there is in fact a bug then we like to file issues on the github project.

**Comment by joshua1029384756** [comment]
Sorry I figured out what was wrong. See all the tutorial videos I have watched show the program going right into the menu at start up, then did not tell me you had to press connect to go to the menu once everything was set up. Sorry for that.
