### ISSUE TITLE
need help PS move rmotes wont charge

### ISSUE THREAD

**Issue by hani910** [cboulay/PSMoveService#58]
I know this isn't related but I bought a ps move remote to try this but it wont charge.
 it will charge for two seconds and disconnect from my pc or wall outlet.
Do I need a ps 3 or is there a way it will stay connected to my pc

**Comment by cboulay** [comment]
If the light stops flashing after a couple seconds, it's possible the batteries are fully charged.
But I also heard of someone that couldn't get his PS Move controllers to charge so he opened them up, bypassed the internal USB logic, and applied 5V directly to the battery (or its interface). After they charged once then they were able to charge normally again.
This seems like more trouble than it's worth seeing as PSMove controllers can be purchased so cheaply (at least they could a couple years ago).

**Comment by toto5100** [comment]
If you want to charge with your pc, when you connect it, you have to go to device manager (in control panel) and deactivate the psmove. Then unplug it and replug it and it should be ok.

**Comment by orangy57** [comment]
My controller only charges when using PSMoveService but without the controllers hooked up to bluetooth.
