### ISSUE TITLE
How to Use A Normal webcam instead of a pseye?

### ISSUE THREAD

**Issue by ICURSEDANGEL** [cboulay/PSMoveService#584]
i tried zadig to change the driver to libusb but when i launch camera test i type the resolution and fps and enter nothing shows up.

 can i please have a tutorial on how to do it?

**Comment by HipsterSloth** [comment]
Only the PS3Eye is supported at the moment. You definitely do not want to assign libusb driver to non-PS3Eye cameras.  I do have some work in my other PSVR testbed adding support for generic webcams, but it is not quite at a state where I'm ready to incorporate it into PSMoveService yet.
