### ISSUE TITLE
Failed to connect.

### ISSUE THREAD

**Issue by airfusion81** [cboulay/PSMoveService#586]
So i was really excited to connect my move controllers finally, when i saw failed to connect to psmove service. I dont know if i did anything wrong. please help?
![psmove](https://user-images.githubusercontent.com/39842549/46382985-fba56e00-c67b-11e8-8283-d46893917096.PNG)

**Comment by cboulay** [comment]
The PSMoveService needs to be running in the background for this client to have anything to connect to.

**Comment by cboulay** [comment]
This issue isn't really an issue. There might be some other problem that you're facing but if that's the case then you'll have to investigate more and provide more information.
