### ISSUE TITLE
PSMove SteamVR Controller Mapping doesn't work

### ISSUE THREAD

**Issue by MilesMapes** [cboulay/PSMoveService#595]
I used the example steamvr controller mapping and the only buttons that work are the trigger, move for trackpad click, and select for grip. although, the default has square set to grip, so i'm confused.

**Comment by oldmanbluntz** [comment]
They are working on this issue presently. Hopefully it will be fixed soon. This issue has been persistent since back in march when the OpenVR api's were changed and psmove service hasn't been updated for that change yet.

**Comment by oldmanbluntz** [comment]
The fix is coming down the testing pipeline now.

**Comment by oldmanbluntz** [comment]
Version 1.6.0 of psmovesteamvrbridge has been released which fixes this issue. Check it out.

**Comment by HipsterSloth** [comment]
Closing this issue now that Version 1.6.0 is out.
