### ISSUE TITLE
CLEyeMulticam.dll is missing even with the cl cam software installed on my computer

### ISSUE THREAD

**Issue by nalf3in** [cboulay/PSMoveService#61]
Hi, I'm currently trying to get the psmoveservice.exe (of the release) to run on my computer but whenever I do, it show me this error even with the cl cam software installed on my computer :  CLEyeMulticam.dll is missing on your computer..

edit: fixed by manually downloading the dll and paste it into the psmoveservice folder.

**Comment by cboulay** [comment]
@HipsterSloth I guess this needs to be added to the release. Do you have a script for making releases or was it done manually? I made a Python script for creating releases for a different project. See [here](https://github.com/sccn/xdf/blob/master/make_release.py). Do you think the structure of our release has settled down enough that it's worth making a script to automate it?

**Comment by StagZealot** [comment]
@nalf3in I am having the same issue with missing the CLEyeMulticam.dll, could you please link to where you where able to download it?

**Comment by nalf3in** [comment]
Here's the official link (from this github)  : https://github.com/cboulay/PSMoveService/raw/master/thirdparty/CLEYE/x86/bin/CLEyeMulticam.dll
 
I got the advice from reddit : here's the link if you are interested: https://www.reddit.com/r/virtualreality/comments/4no4mz/update_on_using_the_ps_move_on_pc_for_virtual/

**Comment by cboulay** [comment]
Are you SirJoe? Please create another issue in GitHub for your camera problem. It's almost definitely a driver issue, but I'll say more in the new issue.

**Comment by HipsterSloth** [comment]
@cboulay I updated the cmake install action to copy the CLEyeDriver to the `/win32/bin` folder. For the moment by process for building a release is to build from source, build the INSTALL project, and zip up all the binaries, scripts and data in the `/win32/bin` folder. I think it's a good time to make a proper release script. That python script you have looks it'd be perfect to adapt. In the mean time I'm going to post a release later to day that includes the CLEyeMulticam.dll.

**Comment by cboulay** [comment]
Please close this issue as soon as you make a new release.

**Comment by HipsterSloth** [comment]
Fixed in Alpha release 2
