### ISSUE TITLE
Error while running psmoveservice : libusb: error [winusbx_claim_interface] could not access interface 0

### ISSUE THREAD

**Issue by nalf3in** [cboulay/PSMoveService#62]
Hi, after I followed the installation guide in the wiki I'm now getting an error while running psmoveservice.exe : libusb: error [winusbx_claim_interface] could not access interface 0: [87] The parameter is incorrect.

screenshots of the psmove service log here : http://pastebin.com/tpe8P4B4 and usbDeview shows to me http://imgur.com/7C5sveQ and zadig http://imgur.com/313Bgu8

edit : I just downloaded the cl driver from this http://www.emuline.org/files/file/37-ps-eye-pc-driver-cl-eye-plateform/ website and now I do not longer have an error with psmoveservice.exe. However, if I want to start the Calibrate tracking colors part it just crash ..

**Comment by cboulay** [comment]
Part of your post is missing. Please add in the rest of the info.

I don't know if that CL Eye Driver you installed is legit or not. That certainly isn't the official source. I don't really want to advertise for them, but the CL stands for "CodeLaboratories" and they charge $2.99 USD for the driver. I just added a [table to the wiki](https://github.com/cboulay/PSMoveService/wiki/PSEye-Software-Setup-(Windows)#overview) that gives a quick summary of the different ways of getting the PS Eye to work on a Windows PC.

Before you install the CL Eye driver, you should first uninstall the libusb drivers. In *Device Manager*, uninstall all the PS Eye related entries. Make sure to check the box that says "uninstall driver too" (or something like that).

If you choose to use the PS3EYEDriver, then I think it might still work for you but there's something wrong with the way you installed it. Try uninstalling everything (as above) then installing using libusbK. This is still sort of magic and we don't know why libusbK sometimes works, or at least installing libusbK first then libusb-win32 sometimes works.

**Comment by nalf3in** [comment]
Finally, after getting the official cl eye driver and cleaning my device manager like you recommended, It do no longer crash ! However I have a bug really similar that the one you have on osx: the first time I get in the camera preview or calibrate tracking menu, I don't see the video and I need to back to the main menu and return to camera preview/calibrate tracking to make it work. I'm gonna test to see if this new bug is resolved with the alpha 2 version but I think the first issue is resolved.
