### ISSUE TITLE
Steam VR not loading controllers

### ISSUE THREAD

**Issue by dignifiedweb** [cboulay/PSMoveService#65]
Hi,

SteamVR doesn't seem to pick up the move controllers as devices. I tried running "vrcmd.exe" and it lists 2 entires for "psmove" but doesn't list any devices for them (0 counts for both).

I ran through the whole process from your wiki for installation. I'm using the "CL-Eye" $3 USD driver for the playstation eye and was able to run through the configurations in PSMoveConfigTool.exe as described in the wiki using the "attach to HMD" method.

A couple of notes:
 - I'm using the Oculus CV1 and the PSMove w/ normal playstation eye camera (3 devices total)
 - When running PSMoveConfigTool --> HMD settings --> Test HMD tracking, I couldn't see my HMD in that screen on initial load until I reset the default position in steam vr to standing only in the steam VR Room setup. After re-running room setup, it seemed fine.
 - When co-registering the ps move controller and HMD, it seemed like they were quite far away from each other after the whole config was done, is this normal? I am thinking once it's done that if I move the PS move controller close to the HMD, they should be close to the same space on the little display of the DK2 model.
- I previously had the razer hydra drivers installed for steam vr, could that be messing things up?
- Before re-configuring as standing only, I had a room scale setup using my razer hydra controllers

Any ideas of something else I can try?

**Comment by toto5100** [comment]
I had this problem too, then i tried to uninstall SteamVR and reinstall it (not the beta version) and it worked. It seems a little random, as i already had this issue before.
Also, for co registration, i prefer to use calibration mat method, it worked better for me (even with 1 camera).

Be sure to launch psmove service before launching SteamVR.

**Comment by dignifiedweb** [comment]
Thank you! That actually did the trick! The co-registration was off, so I'll have to explore the mat technique like you said. This is pretty not bad! Any tips doing the mat thing? I am really confused by it. For what it's worth, I also uninstalled the hydra drivers, as I thought: why not. The issue is pretty much resolved though, good tip! I was using the beta before too, maybe that was it.

**Comment by toto5100** [comment]
Great ! I'd like to know how does it compare with hydra in terms of tracking.

**Comment by dignifiedweb** [comment]
It's not as good as the hydra for tracking. However, it being wireless is a big win for me. Also, the Hydra is EXTREMELY sensitive to EMF fields. For instance, it's summer now, and my A/C unit is outside my office (central air). If the A/C unit kicks in, the tracking degrades to unusable state, it might as well have gone completely off. So, when hydra is working well, it works fantastic. Also, the tracking mat worked flawlessly! I'm currently re-calibrating with camera positioned higher so I can try setting up roomscale. 

With Hydra, you can setup roomscale with CV1 & get a reasonable 2.5 meter by 2.5 meter usually fairly well. I saw someone run a hydra from a ceiling which is cool. It has 360 tracking, but the drawback is that the EMF field is so sensitive, even your body can sometimes occlude the tracking. The PS Move would be good with a second camera, I'm definitely going to have to go pick one up or something. So far, this is working pretty half decent honestly. Good job guys on this! It's better tracking with the move than it is with Hydra and the EMF field being disturbed.

**Comment by HipsterSloth** [comment]
Sorry I just noticed this issue. Thanks for the debugging help @toto5100! I'll update the troubleshooting steps with the SteamVR tips. 

@dignifiedweb Yeah the second tracking camera definately helps stabilize the z depth. There is still a bunch of work @cboulay and I have to do to improve the tracking quality too. We're currently no undistorting the camera image (need to port over the camera calibration tool). This causes the tracking to become more inaccurate as you get near the edge of the video frame. We also are only using a simple low-pass filter on the position data which is still pretty noisy at times. Hopefully we can get the tracking quality improved over the next month. Thanks for bearing with the alpha-ness.

**Comment by dignifiedweb** [comment]
@HipsterSloth great work! I appreciate the effort!

Any tips on getting a second camera to work? My brother had an extra one kicking around, wanted to try it. I can't seem to get it to recognize in the PSMoveConfigTool.exe. I re-installed the drivers and it all seems to be setup correct. The CL-Eye drivers came with a test app and I get a picture from both cameras if I unplug one, but I think that software may have a limitation of one camera at a time.

Thoughts? Thanks so much for doing this, it's so cool.

**Comment by cboulay** [comment]
Yes, CL Eye driver is limited to one at a time. You have to use their platform SDK (CLEyeMulticam) if you want multiple cameras... or use the PS3EYEDriver for free, warts and all.

**Comment by HipsterSloth** [comment]
With the cl eye driver for multiple cameras I think you you have to buy the multicam driver and additional credits per camera you want to use. It's been a while since I tried that configuration though. Do the libusb drivers not work for you with the alpha release?

**Comment by dignifiedweb** [comment]
Thanks guys, wasn't sure about that. Maybe I'll buy the multicam driver. libusb just wouldn't work for me this time around. I had it working on windows 8 a while back with your unity version of all this. I just couldn't get libusb working this time around and CL Eye was $4 bucks, worked right away. Maybe I can try libusb again and see if I can get it going.

**Comment by dignifiedweb** [comment]
I still couldn't get the libusb method to work. I went ahead and bought the $4.99 USD SDK version and I copied over my own CLEyeMulticam.dll and replaced the one in the release binaries provided. Do I have to build the whole project myself again rather than use your release binaries? 

The SDK came with SDK examples and their own precompiled binaries. I checked both and I can build their WPF multi-camera example and run their binaries just fine. I copied the DLL from %WINDIR%\syswow64 is that the correct DLL to copy? When i startup PSMoveService.exe, it says "failed to open" on one of my PS Eye cameras. When I open the tool, it only displays one in the camera. Then, as an added bonus, one of the PS Eyes stays red like you guys said might happen in your wiki.

Excellent wiki by the way, I should have seen that part about the CL EYe driver only working w/one camera, since it's listed there on the top table.

**Comment by dignifiedweb** [comment]
Hey guys, came back to report that I accidentally didn't actually copy the DLL. The DLL was in use and for some reason windows didn't say it had a problem copying. That's a dumb mistake to make, looks like it works now! Cheers!

**Comment by cboulay** [comment]
With the Multicam DLL you can install the developer version or the redistributable version. The redistributable version, i.e. the one that we supply, allows you to link just fine but when running it only opens cameras that are properly registered. The developer version works with unregistered cameras but cannot be distributed by us. Somewhere in the platform SDK tools it's possible to switch which version is installed. Maybe you did that between copy attempts. Actually, all you have to do is delete the supplied DLL and then it'll pickup whichever one is installed because it's on the path.

**Comment by dignifiedweb** [comment]
Yesterday I tried using multiple cameras and I was getting weird behavior. Using a USB 2 powered hub, I was able to get an image from both, but it was slow bandwidth. Thinking the hub was causing slow bandwidth, switched back to using 2 USB ports and re-installed driver. After this, 1 camera wouldn't get an image and the other had weird artefacts. When it was delayed using the hub, I tried using calibration mat, but had weird ghosting issues when viewing the orb.

In both cases, I used the included binary executable with the CL EYE SDK and could get a perfect responsive image from it. In the PS Move config tool, though, not able to get a good image for 2 cameras. It says Libusb still as type, could that be the problem? I double-checked and it's "WinUSB" type using that usb configure tool. I think I'm hitting a wall here, sorry guys really wanted to test this.

**Comment by HipsterSloth** [comment]
Sorry for the camera woes! 

I think the "libusb" displayed in the psmoveconfig tool is a bug (I recall noticing it always said that regardless of driver). The usb configure tool is definitely the authority. 

Hubs can sometimes be problematic, though usually because it's easier to overload the usb root hub they are plugged in to.

I haven't used the cleye camera tools in a while, but is it possible to get the video streams for both up at the same time using them or just one at a time? I suspect you have both cameras connected to the same usb root hub. When psmove service opens up both cameras at once you are saturating the available bandwidth. You can tell which root hub you are connected to in the windows device manager.

For what it's worth, i'm going to revisit the libusb camera support next week when i'm working on adding support  for the ps4 camera.

**Comment by dignifiedweb** [comment]
No worries. I wasn't very clear, also. The binary that I was talking about from the SDK is the one that shows two cameras at once. It shows both camera pictures at once and there's no noticeable lag at all from that. They are both plugged into my front usb, I could try one in the hub (back USB) and one in the front USB, maybe that'll get it going lol. I may be pre-occupied though, possibly getting Oculus Touch controllers soon for a project I'm working on. That might sway me to not try the PS move... sorry lol.

**Comment by dignifiedweb** [comment]
The weird part though, was with the SDK example binary, it showed both cameras at once, but one camera was tilted (diamond shape in a square frame). I attribute that to a bug in the software, but maybe that camera is just wacky and done. The original camera I tried was good! This has good picture, just on an angle. If I use it by itself, it's straight though, which I found odd.

**Comment by zelmon64** [comment]
@dignifiedweb  The SDK has an arbitrary tilt to all PSEyes so that you can rotate them and piece them together (it's not a bug). 

If you want to have another go at libusb-win32 first install libusbK then replace it with libusb-win32.
