### ISSUE TITLE
Coregistration with HMD doesn't work with vridge.

### ISSUE THREAD

**Issue by nalf3in** [cboulay/PSMoveService#66]
Hi, I'm currently trying to do the HMD Coregistration withg vridge (vridge is basically a software that emulate the rift with your phone so we can play steamvr games with it and here's the official website link :https://riftcat.com/vridge ). The problem is that whenever I want to do the HMD Coregistration it just skip the recording samples part thus putting the psmove at the origin (where my hmd is) in steamvr . The calibration Mat process work as it should be still put my psmove at the origin in steamvr so I'm not able to see the controller and it is kinda hard to control. Also I noticed that the hmd tracking in the main menu doesn't work till I do the coregistration with HMD everytime I open psmoveservice. Steamvr is open when I try to do the coregistration and I'm using the 3 $ cl eye drivers.

Finally, as my headset is kinda unofficial, I understand if you don't want to support it.

Thanks alot anyway :)

**Comment by hawkinse** [comment]
Vridge only handles rotation, not position. As such, you can't use HMD Coregistration to calibrate the controllers. Only the calibration mat will work.

I've had success by setting the HMD height to 72 inches off the ground in the Steam VR setup, and then using the calibration map at head height. When in SteamVR, you'll have to stand in the exact spot you calibrated at to be able to see the controllers.

**Comment by nalf3in** [comment]
Thanks for the help ! But It didn't worked for me ( the controller was just a little above my head which is still a improvement). I ended up modifying the json at C:\Users\\AppData\Roaming\PSMoveService\TrackerManagerConfig.json to set the correct position (for me it is x:0 y:100 and z:-55) and it's now working fine.
