### ISSUE TITLE
Psmove controllers shakes in steam and in test tracking

### ISSUE THREAD

**Issue by nalf3in** [cboulay/PSMoveService#67]
I'm having a strange bug with the psmove controller : they shake in virtual reality even if they are on a flat surface and are not moving at all in the reality. I did the magnetometer calibration (followed the wiki) but that changed nothing.. Here is my psmoveservice.exe [log](http://pastebin.com/uUSEP423) and here's a video showing the problem (While the video only show the controlleron a flat surface shaking in a steamvr game it shake anywhere even in the test tracking program of psmoveconfigtool) [link](https://drive.google.com/file/d/0B0k0vTaYUh55MDQ1SGpaSURZSUE/view?usp=sharing)

**Comment by HipsterSloth** [comment]
Probably a tracking issue? How does the color filter calibration look?

**Comment by nalf3in** [comment]
I think I've done it right, here's a screenshot : http://imgur.com/2xDHqLY. Also I don't know if that's related but  I need to acess the camera a first time to see a image like @cboulay issue on [mac  ](https://github.com/cboulay/PSMoveService/issues/49)

**Comment by HipsterSloth** [comment]
The color filter settings look right. From the logs it looks like you are just using one camera. We have to determine the z-position using the size of the tracking sphere on screen which is intrinsicly noisy. You can improve tracking with a second camera. Also were still working on adding smoothing.

**Comment by netbeard** [comment]
@nalf3in Holy crap your gain is high!  Maybe try turning down your gain and increasing the exposure?
That won't fix the inherent issues with single camera tracking, but it may help.

**Comment by cboulay** [comment]
That gain can't be correct. It's probably just a type conversion & rounding issue, which is a bug that should be fixed. Exposure of 8 seems reasonable, but you can turn it up a bit.

Try repositioning the PSEye so it is closer to your workspace. The closer you are to the camera, the more pixels that the sphere covers, the more accurate the tracker algorithm is. The PSEye usable tracking volume is much smaller than those of the Vive or Rift.

**Comment by nalf3in** [comment]
First, thanks for the help!
I turned my exposure a bit and reduced the distance between the camera and the controller like you suggested and it helped a bit (still shaky though) I guess I will simply buy an other psmove camera as it is fairly cheap and should do the job. Finally does I have to set the psmove camera at a specific place ? Because I just realized that my camera is at my left while in the wiki you suggest to place it  front of the calibration mat..

**Comment by HipsterSloth** [comment]
Any location is fine so long as your controller will be within the sweet spot of 2-6 feet of the camera. I have my two cameras to the left and right of my desk and I place the calibration mat in between the two.

**Comment by nalf3in** [comment]
Perfect thanks ! Do I close the issue or I wait that you implement smoothing?

**Comment by HipsterSloth** [comment]
I'll close this issue and make a new one (Issue #69) specific to the smoothing implementation.
