### ISSUE TITLE
Trigger button unresponsive in certain games

### ISSUE THREAD

**Issue by netbeard** [cboulay/PSMoveService#68]
The trigger button is unresponsive in both "The Lab" and "Job Simulator".
Edit:  Running win10 x64, latest commit.  Did not work with the previous binary releases either.

**Comment by nalf3in** [comment]
I also have the same issue on the same os.

**Comment by HipsterSloth** [comment]
I'll give this a test tonight in "the lab". It could be that I don't have the trigger button event mapped correctly.

**Comment by hawkinse** [comment]
Are you using alpha release 3 or a version built from source? Triggers work for me in The Lab.

**Comment by netbeard** [comment]
@hawkinse I am using the latest(as of OP) build from source.

**Comment by nalf3in** [comment]
I'm also using the lastest version alpha 3 and I noticed that skeet vr
shooting also don't work.

**Comment by zelmon64** [comment]
I'm on Win10ProNx64 using alpha3 and the triggers now work fine for me. I tested in Skeet, The Lab and Cosmic. I can tell that they're working fine because of the virtual vive controller's trigger animation now works.

Did you completely uninstall any previous versions? I used to have that problem.

**Comment by netbeard** [comment]
I've run the uninstaller batch file, and yeah, the trigger animation in steamVR doesn't work either....Hmmm...guess I'll try reinstalling Steam.

**Comment by HipsterSloth** [comment]
I really need to add a button test screen in the config tool as well as button remapping options in the SteamVR plugin. I'll see if I can work that at the end of my dualshock4 work at the end of the week.

**Comment by picklefart9** [comment]
Just to make sure for all of you who find the trigger button unresponsive in The Lab:
Did you by chance update from Alpha 2 to Alpha 3? If you did, make sure to uninstall and reinstall the steam driver using the batch file.

**Comment by netbeard** [comment]
Welp, that's embarrassing.  I couldn't get it working with the build of the latest commit, I tried uninstalling and reinstalling the steamVR driver too.

For the heck of it I tried the latest binary release, alpha 3.  Works like a charm.

**Comment by HipsterSloth** [comment]
Glad you were able to get it working. For what it's worth I just tested latest on my home machine with some new changes to fix rumble. It looks like trigger still works in latest. I'll do a fresh sync of master at work tomorrow to double check. If it looks good there I'll resolve this issue.

**Comment by HipsterSloth** [comment]
There were issues with the trigger in a few other games (Brookhaven Experiement). 
https://groups.google.com/forum/#!topic/psmoveservice/0ek06j6Qal4

I believe this was a different issue. I fixed the trigger touch/press thresholds to match the ones in the Hydra steamvr driver.

Here's a custom build for testing in case anyone wants to try it.
[PSMoveService-v0.9alpha5_4_2_custom.zip](https://github.com/cboulay/PSMoveService/files/535543/PSMoveService-v0.9alpha5_4_2_custom.zip)

**Comment by HipsterSloth** [comment]
Turns out there was one more issue. I wasn't setting which axis was labels at the trigger axis correctly. I just verified the trigger works in "Brookhaven Experiment" and "Serious Sam"

[PSMoveService-v0.9alpha5_4_3_custom.zip](https://github.com/cboulay/PSMoveService/files/537958/PSMoveService-v0.9alpha5_4_3_custom.zip)
