### ISSUE TITLE
Camera not detected but settings seems ok

### ISSUE THREAD

**Issue by demonixis** [cboulay/PSMoveService#70]
Hi,

I followed the instructions of the wiki to configure the PS3Eye, but it's not detected in `PSMoveConfigTool`. This is a screenshot of logs

![2016-06-20 2](https://cloud.githubusercontent.com/assets/1017126/16191631/88bc5818-36e5-11e6-89d4-ede5db70183f.png)

As you can see, the camera seems to be well configured and it uses the `libusb-win32` driver. I have downloaded psmove-unity5 and tried `ps3eye_sdl` and everything seems ok, I can see the camera output at 60 fps.

Any idea?

Thanks.

**Comment by zelmon64** [comment]
Did you install libusbK then replace it with libusb-win32? Sometimes that helps.

**Comment by demonixis** [comment]
Nop, I'll try this after work. Thanks! I wasn't able to configure this camera, I tried libusb and CLEye but nothing seems to work.

**Comment by xMindweaverx** [comment]
Yea, this was the only way I could get it to work as well. Just uninstall the drivers above, then Install the libusbk driver and then install the libusb-win32 driver over top of the libusbk driver. It may hang (Mine did) just restart and then reinstall the libusb-win32 driver. Once I did that it worked perfectly.

**Comment by demonixis** [comment]
I confirme it's working!
