### ISSUE TITLE
HMD tracking doesn't work

### ISSUE THREAD

**Issue by Karon1** [cboulay/PSMoveService#71]
Hi,

the HMD tracking of the PS Move Config Tool doesn't work. It shows a generic blue cage but other than that nothing. It doesn't pick up on my Oculus Rift CV1.

SteamVR is up and running. Since steamVR doesn't support room scale VR with the Rift I can't set up a chaperone room in it.

What do I need to do to fix this?

(I'm new to github, how can I apply a label?)

**Comment by HipsterSloth** [comment]
Sorry I still need to better describe this process in the docs. You can pan around the view with the mouse and zoom with the scroll wheel. Often the HMD is outside of the initial camera view. I still need to implement auto centering.

That blue cage is actually the chaperone bounds I get from SteamVR. When running with the Rift you get some default chaperone bounds.

Let me know if you still can see your HMD after adjusting your camera view.

**Comment by Karon1** [comment]
thanks for the info, yeah it works fine now. Sadly my camera tracking doesn't work well anymore =/ It flashes green pictures between the captured frames =/

**Comment by HipsterSloth** [comment]
Glad to hear that was the HMD issue. I'm going to close this issue.

As for the camera green flash issue, you might try the steps outlined here:
https://github.com/cboulay/PSMoveService/wiki/Troubleshooting-%28Windows%29#psmoveservices-hangs-shortly-after-starting

There is an issue tracking the green flash problem here:
https://github.com/cboulay/PSMoveService/issues/64

And a related one here:
https://github.com/cboulay/PSMoveService/issues/70

In that second issue some have reported the following helps with your situation:
"Yea, this was the only way I could get it to work as well. Just uninstall the drivers above, then Install the libusbk driver and then install the libusb-win32 driver over top of the libusbk driver. It may hang (Mine did) just restart and then reinstall the libusb-win32 driver. Once I did that it worked perfectly."
