### ISSUE TITLE
Can't compute tracker position (DK2 or OSVR)

### ISSUE THREAD

**Issue by demonixis** [cboulay/PSMoveService#73]
Hi,

I try to compute the tracker position but I don't know what I have to do, I move my HMD with my Move, I see the HMD on the screen (not the move) but it does nothing else. I just have to button, reset or cancel.

![image](https://cloud.githubusercontent.com/assets/1017126/16332881/b4a3c5fe-39f8-11e6-8110-c048fc499d1f.png)

![image](https://cloud.githubusercontent.com/assets/1017126/16332960/1e764da8-39f9-11e6-9aab-63f02f0d2044.png)

The PS Move's magnetometer is already calibrated.

I tried to do compute the tracker position with my OSVR HDK but it's the same result. 

Thanks for you help.

**Comment by zelmon64** [comment]
I'm not quite sure about that method. Have you tried using the calibration mat? You can do it without printing it by just estimating the positions (works for me).

**Comment by demonixis** [comment]
Yes but I only have one camera and it's designed for more than one camera right? I tried but I can't calibrate anything.

**Comment by zelmon64** [comment]
No, it should work with just one PSEye. Have you check if the mask is working correctly? It's in Tracker Settings -> Calibrate Tracking Colors -> Color Calibration -> Video Filter Mode and scroll through to Masked. If you can't see the orb then switch to HSV and right-click where the orb is to set it then click Save Default Profile.

**Comment by demonixis** [comment]
OK that was the problem, now it works. I've used the calibration mat method ;) Thanks again for your help !
