### ISSUE TITLE
Trying to connect two PSEyes with the CLEye driver but not working.

### ISSUE THREAD

**Issue by Bigfloopingcake** [cboulay/PSMoveService#74]
I am trying to add two cameras to psmoveservice and it is not working. I have followed the steps to set up the cameras but its still not working. when I launch psmoveservice it says it detected both of them but only opens one.

**Comment by Bigfloopingcake** [comment]
I have also bought every thing that was needed to use cleye.

**Comment by cboulay** [comment]
On the [wiki](https://github.com/cboulay/PSMoveService/wiki/PSEye-Software-Setup-%28Windows%29) you'll see that the CL Eye Driver only supports one camera.

**Comment by Bigfloopingcake** [comment]
even with the cleye platform sdk?

**Comment by HipsterSloth** [comment]
I believe multiple cameras should work if you have the cleye platform sdk, but you have to copy the cleye dll in the psmoveservice directory with the one in the SDK I think. Someone mentioned it in another issue thread but I can't find it.

**Comment by Bigfloopingcake** [comment]
couldn't find the .dll file in the sdk.

**Comment by cboulay** [comment]
It's called CLEyeMulticam.dll. It should be enough to delete the one that comes with PSMoveService because the one installed by CL Eye Platform SDK will be put on the path (I believe in C:\Windows\sys or C:\Windows\sysWoW64). Be sure to use the CL Eye Platform SDK install tool to choose the "developer libraries" instead of the "redistributable libraries". I am not on my Windows machine regularly so I would appreciate it if you can take some screenshots of that process and update the Wiki.

**Comment by Bigfloopingcake** [comment]
It is still only opening one of the the cameras in psmoveservice even when i put the new .dll in to it.
![capture](https://cloud.githubusercontent.com/assets/20143061/16358451/a1a7e634-3ad8-11e6-8cf3-83d3291d50ea.PNG)

**Comment by Bigfloopingcake** [comment]
sorry bad picture.
![capture](https://cloud.githubusercontent.com/assets/20143061/16358463/ccd09e3c-3ad8-11e6-99ad-5ffced513488.PNG)

**Comment by HipsterSloth** [comment]
That last log you posted sure looks like it's opening both (though the indexing is goofy). It found both cameras and opened camera index 0 and camera index 1. You can test that they are both open if you launch the config tool > tracker settings. There should be two trackers listed.

**Comment by greggon** [comment]
If you have Alpha4, then run test_camera.exe to confirm both are working and providing a feed. Then launch PSMoveService.exe and PSMoveConfigTool.exe. In the tool go to Tracker Settings > Test Tracker Video Feed and then return and click the [ >] at the top of the floating box which should change Tracker : 0 to be Tracker: 1. Testing the video feed should show you the perspective from the second camera.

**Comment by xMindweaverx** [comment]
Yea, I'm having issues as well. Both trackers are only showing green in Test_camera. I bought the CL-eye sdk for multicamera.

**Comment by greggon** [comment]
If its green then i've found that to be bandwidth-related. Try plugging them into different ports, or restarting your computer. I sometimes have mine showing up perfectly at first but then intermittent green screens when Steam VR is running as well. Try to make sure you're not using USB hubs and connect directly to your mobo USB slots or case ones. I ended up shuffling around my ports and connections and after connecting to 2 separate USB3.0 ports, both cameras seem to be working well-enough.

**Comment by xMindweaverx** [comment]
Thanks for the reply Greg. One camera was working fine on usb2, but after installing the CL-Eye SDK non of the cameras seem to do anything but green screen. I'm trying to get one camera working with the sdk now and I've used every usb3 port on my motherboard and also on my usb3 pci-e card. The on on my pci-e card I'm seeing the video feed but ever other frame it seems to be green. I'll look at buying another usb3 card. Thanks

**Comment by Bigfloopingcake** [comment]
Okay so I got the cameras to work but PSmoveservice keeps crashing on me.
![capture](https://cloud.githubusercontent.com/assets/20143061/16471635/94991d98-3e23-11e6-9368-96e15a5fffd4.PNG)
