### ISSUE TITLE
Two PSEye conflicting with the Rift DK2

### ISSUE THREAD

**Issue by toto5100** [cboulay/PSMoveService#75]
Hi,
I bought a second pseye in order to achieve a better tracking. But they do not work.
Both of the cameras are correctly detected, but in the configuration tool, i only have a video feed on the first camera but not the other (blank screen).
I found out that if i turn off my DK2, then the two cameras are working, and once i turn it on again, the second camera's video feed stops.

I thought it was a problem of bandwidth (with dk2 camera consuming too much), so i bought a pci express usb controller.
Then i plugged the dk2 on it, and the two others cameras are connected on one controller for each (one on the motherboard and one on the front usb). So each have his own usb controller, there should not be bandwidth problems.

But it didnt changed anything, only the first camera works, the second one is showing an empty green screen, except if i turn off my dk2. It looks like there is a conflict between the dk2 and the second camera.

I also sometimes have a "failed to open ps3eyetracker" message (then none of the cameras work).

PS : I'm not using CLEye, just the free ps3eyedriver

**Comment by cboulay** [comment]
That might be a problem on our end. Admittedly I didn't test with the DK2-camera plugged in when I was figuring out how to enumerate cameras. If OpenCV picks up the DK2 camera then it might attempt to open it instead of the other PSEye. There's supposed to be priority for PSEye cameras but I never tested that for more than 1 camera.

If you're a developer then I can point you to the code where this would happen. I don't have 2 PS Eyes and DK2 camera in the same location near a Windows machine so I'm not able to test this on my own.

**Comment by toto5100** [comment]
I'm not really a developer, i have some knowledge but i never really used visual studio and never programmed that sort of things.

Do you think using CLEye driver could help this issue ?

**Comment by HipsterSloth** [comment]
You might double check that the libusb driver is actually installed on both cameras (in Zadig). Sometimes when you change ports windows re-associates WinUSB with the camera. You might also try the trick of installing libusbk (in Zadig), and then install libusb-win32 over top.

For what it's worth I'm going to be working on improving the camera driver code this next week.

**Comment by toto5100** [comment]
The libusb0 driver is installed for both cameras. I also tried the trick with libusbk but it didnt changed anything.

**Comment by HipsterSloth** [comment]
You might check in Windows Device Manager under usb and see if the DK2 and the PS3Eye cameras share the same root hub. I would think not since you have the expansion card, but it's worth checking. I can test a DK2 next week at work. Unfortunately my DK2 at home broke.

**Comment by HipsterSloth** [comment]
@toto5100 I just uploaded alpha4. This new release won't fix camera issues (working on that next), but it does have a new test_camera.exe. Would you mind testing that and see what it shows?

**Comment by toto5100** [comment]
I swapped all the usb ports. And then i got the message "failed to open ps3eyetracker" for each cameras.

Then, I managed to get the two cameras working (with alpha3 and alpha4) by uninstalling all the USB Camera-B4.09.24.1 (Interface 1) with. It looks like the tracker tries to open the wrong camera (the first time the dk2's, and the second the Interface 1 (which is the microphone of the pseye).
Now it works, but i'm not sure if it will keep working, so i'll close the issue when doing more tests.

**Comment by toto5100** [comment]
After further tests, it looks like that if i want the pseyes to work, i have to go in usbdeview, and uninstall all the USB Camera-B4.09.24.1 (Interface 1). I have to do it each time i start the computer.

**Comment by kipoopik** [comment]
seems fine for me, i have DK2, 2 move cameras on usb2, i purchased the cl driver and multicam sdk. I renamed the supplied multicam.dll to .old and both cameras connect fine. Tracking is still giving me issues but from the setup it appears to be working

**Comment by toto5100** [comment]
It works only if i uninstall the USB Camera (Interface 1) before launching the service, but it's not a big deal so i close this issue.
