### ISSUE TITLE
PSMove Controllers invisible in alpha4

### ISSUE THREAD

**Issue by zelmon64** [cboulay/PSMoveService#77]
@HipsterSloth and @InfinateXtremer firstly the new PSEye 3d model looks great! The problem is the PSMove controller model doesn't show. The folder in the alpha4 release is actually empty so I copied the files across from the [dualshock4 branch](https://github.com/cboulay/PSMoveService/tree/dualshock4/src/openvr_plugin/resources/rendermodels/psmove_controller) but they still didn't show. I tried reinstalling the driver a couple of times but it didn't change anything.

Here's a copy of my vrserver.txt file in case there's anything useful in there:
[log1.txt](https://github.com/cboulay/PSMoveService/files/333542/log1.txt)

**Comment by toto5100** [comment]
It happens to me too. Not a big issue, as we could take custom skins from the store, but it's still there.

**Comment by InfinateXtremer** [comment]
From the look of it ds4 branch have broken/old model try using this one https://1drv.ms/f/s!AnmkZiurQJz8g6Vl-2FskxoKRx7xcA

**Comment by zelmon64** [comment]
@InfinateXtremer Yep that did it and they look outstanding! 

Just a couple of minor suggestions. Firstly the cyan looks great but would it be possible for you to make a magenta one as well so they can match in real life? Secondly, I don't know how difficult it is or what's involved but would a trigger animation like the vive controllers be possible? It's mainly just reassuring to see the trigger move to verify that it's working.

Thanks again for your contributions to this project!

**Comment by HipsterSloth** [comment]
Whoops. Looks like I messed up making the build zip last night. Fixing that now.

**Comment by HipsterSloth** [comment]
@zelmon64 @InfinateXtremer With regard to the controller model color and trigger animation, looking at the vr_controller_vive_1_5 folder it appears that we can provide a .json file that describes how the trigger should animate and which bulb should appear. 

Each component that does something special has it's own section in the json file. The trigger looks like this:

```
        "trigger": {
            "filename": "trigger.obj",
            "motion":{
                "type":"rotate",
                "controller_axis":1,
                "controller_axis_component":0,
                "value_mapping": [0.0,-17.0],
                "pivot": [0.0000, -0.016, 0.039],
                "axis": [1.0, 0.0, 0.0]
            },
            "component_local" : {
                "origin": [0.0, -0.039, 0.051],
                "rotate_xyz" : [-83.885,0.0,0.0]
            }
        },
```

This means that the trigger has to be split off into it's own model and then positioned in the right location. I think we can probably do some similar using the "visibility" property for selecting 1 of N color bulbs. It's not clear to me yet though how we would expose the bulb color to the visibility property. But I think the json would look something like this:

```
        "bulb_blue": {
            "filename": "psmove_bulb_blue.obj",
            "visibility": {
            	"default": false,
            	"bulb_color": "blue"
            }
          }
```

**Comment by HipsterSloth** [comment]
Alpha4.1 has the missing controller model files
