### ISSUE TITLE
Each tracker should have it's own color calibration

### ISSUE THREAD

**Issue by kipoopik** [cboulay/PSMoveService#78]
after cycling colour of move in test camera feed away from magenta, compute tracker pose doesn't reset the colour back so compute doesn't work as it only seems to be able to track magenta.

Also calibration should be done for each individual move, i have 4 connected and each slightly differ in shade so masked view shows artifacts

**Comment by Andalu30** [comment]
You can simply exit the ConfigTool to reset the Move, its tedious but its not like a super-bug.
However, I find it interesting your idea of individual calibration. In my opinion, its simple, we just need the two controllers to light up, so if we want to calibrate cyan, we point the  second controller to the camera.
Also, another idea i have is to be able to select the "primary" and "secundary" color. I'm having problems with my PSeye and it looks like it cant really differentiate between Magenta and Cyan. I know its just spend time in the color calibration, but I think having an option to set, for example the primary to blue, and the secondary to red, may be faster, and even will probably reduce the shake of the controllers.
However, I've not fully configured my setup so maybe this "color differentiation" is not a problem once I completely set it up.

Finally, I must say that you guys are doing awesome. The idea of affordable VR is brighter than ever. Also, as a software engenieer student, this proyect is inspiring and I would love to help but I'm pretty sure I couldnt do anything xDD. Keep it up!

**Comment by HipsterSloth** [comment]
I just checked in a fix for the first path of this issue into master. It'll be in the next release (Alpha4.6).

I renamed the issue to track the second part of the request (per controller color calibration).

**Comment by cboulay** [comment]
@HipsterSloth Can this be closed?

**Comment by Andalu30** [comment]
Under my opinion, yes sure, it was solved time ago.

**Comment by HipsterSloth** [comment]
Ah oops. I meant to close this with the last release. Closing now.
