### ISSUE TITLE
Accuracy of positional tracking in multi-cam configuration needs improvement

### ISSUE THREAD

**Issue by kipoopik** [cboulay/PSMoveService#79]
positional tracking is off when using a multicam setup, when using the single cam tracking is fine although controllers quickly disappear and reappear constantly.
I now have 2 ps3 cams either side of a 120cm wooden pole with the DK2 sensor in the middle, both cameras are tracking fine, after setup i see that the dk2 sensor & 1st camera have the correct position but the 2nd camera position is roughly 10cm forwards from where it should be. Multiple attempts to calibrate using the attach to HMD method give similar results.

**Comment by HipsterSloth** [comment]
The tracking code isn't currently undistorting the image from the camera (because I haven't written the lens calibration tool yet, see issue #51). As a result the camera calibration is almost certainly going to be off. After I get through the other camera improvement work I want to get to this.

**Comment by HipsterSloth** [comment]
I've been working on the distortion calibration tool the last few days. The front end tool is basically done now. I'm hoping to have this integrated up to master by the end of the week. I'll try to get a new build out this weekend.

**Comment by cboulay** [comment]
"Needs improvement" isn't a helpful issue right now. We know there's work to be done to improve tracking, and we are actively working on it. I'm going to close this issue. After I'm finished my housekeeping I'll see if there aren't any issues that are explicitly outlining the need for a camera calibration tool, and if there are none then I'll open one just for that.
