### ISSUE TITLE
Not working with MotionJOY sync

### ISSUE THREAD

**Issue by FA9US** [cboulay/PSMoveService#83]
I am able to connect and sync my PSmove  controller with MotionJoy using below BT dongle.
Motionjoy loads its own driver and replaces the BT driver. this way any BT dongle will work.
unable to recognize the move controller wireless Using either below BT dongle its driver or motionjoy.

Adapter MAC f8.8d.50.dd.9.0 
Manufacturer Infineon Technologies AG 
HCI Version 6.1d86 
LMP Version 6.1d86

**Comment by FA9US** [comment]
i was able to solve my issue by removing all the drivers i could find for my BT dongle and let windows10 handle it. i had to repeat this couple of times

**Comment by HipsterSloth** [comment]
It sounds like we'd have to do some custom work to interface with the MotionJoy driver. We currently just use the windows bluetooth stack directly for controller pairing and HIDAPI for getting data to and from the controller. Is there any reason you need to use the MotionJoy driver with the PSMove controller? Perhaps there is some bit of functionality we could add to PSMoveService instead?
