### ISSUE TITLE
Can't start PSMoveService

### ISSUE THREAD

**Issue by Monophobe** [cboulay/PSMoveService#84]
Hi,

I've spent all night trying to get somewhere with this but no matter what I do I get the same log when trying to run PSMoveService.exe

"[2016-06-30 02:55:59.800383]: main - Starting PSMoveService
[2016-06-30 02:55:59.803369]: main - Failed to start PSMoveService: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted"

I've tried removing everything I can from my USB ports (down to just mouse, keyboard receiver and PS3 eye). I've tried USB 2 and 3 ports. I've followed all the guides about stripping out existing drivers, etc.

The main difference from the tutorial images is that my PS3 Eye is listed as USB Camera-B4.04.27.1

Currently USBDeview shows 4 listings for VendorID/PID 1415/2000, status / device name / description as follows:

(green) USB Camera-B4.04.27.1     USB Composite Device
(grey) Port_#0004.Hub_#0003
(green) USB Camera-B4.04.27.1     USB Camera-B4.04.27.1 (Interface 0)
(green) USB Camera-B4.04.27.1     USB Audio Device

The camera works when I run test_camera.exe

Any help would be appreciated.

**Comment by HipsterSloth** [comment]
This is the critical error:
"[2016-06-30 02:55:59.803369]: main - Failed to start PSMoveService: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted"

Sounds like another application is already bound to the port psmoveservice uses, port 9512. 

Check out this tutorial to find out which application is the culprit:

http://www.howtogeek.com/howto/28609/how-can-i-tell-what-is-listening-on-a-tcpip-port-in-windows/

Are you sure you don't have a zombie psmoveservice lurking in the background?

**Comment by Monophobe** [comment]
Thanks. It was the server for Unified Remote. Might be worth adding to the Wiki/FAQ?

Since getting that working I've got my Move controllers synched via bluetooth. Will look into the calibration options tonight.
