### ISSUE TITLE
Can not use Multiple PS Eyes even with CL Eye SDK.

### ISSUE THREAD

**Issue by BogomilPetrov** [cboulay/PSMoveService#85]
Hello. I bought the CL Eye SDK so that I could use multiple PS Eyes. I have 2 and they both work great. The problem is this: If I have the standard driver installed both of them work fine. Whenever I test one it works flawlessly. If I remove the standard 1 camera driver and install the CL Eye SDK Both cameras work but only in the provided demos from CL Eye. I know that they're both detected in the CL Eye Device Manager and that theyre working as the SDK demos show the 2 cameras and their image working perfectly however PSMoveService does not recognize or use those. I have chosen the developer version of the SDK which allows for the 2 free cameras. The only way for me to make it work is to install the standard 1 camera driver but then the second camera doesnt work.

So do I have to install both the standard driver and the SDK at the same time? That only shows 1 camera. If I only have the SDK their demos work fine with the cameras but PSMoveService does not detect them at all with the SDK. What do I have to to to make PSMoveService recognize that there are cameras connected with the SDK.

OS: Windows 10 x64
Camera driver: Have both CL Eye SDK and normal CL Eye Driver
Camera: 2 PS Eyes for PS3.

What do I have to do to make PSMoveService recognise the cameras with the SDK. Simply installing it does not work and they are not recognized. The CL Eye Multicam demos work fine.

**Comment by zelmon64** [comment]
Personally I'd say give up on CL-Eye and use libusb-win32. I have three PSEyes working just fine. However, if you really want to use it, have you gone through what they say in #74? I'm reluctant to troubleshoot it myself since I'd have to break my setup in the process. HipsterSloth is working on improving the PSEye integration.

**Comment by BogomilPetrov** [comment]
Yes. I got that idea already but libUSB just simply doesn't work like I
need it to. Its 100% fine with 1 camera but as soon as I plug in the second
one and start the test again it just shows 2 green windows. Its solid
color. Both of the cameras work absolutely fine on their own but together
its just 2 green windows.

**Comment by toto5100** [comment]
Check if turning off your headset resolves the problem. If it does, then it's the same problem as me : try to plug your cameras and headset in multiple usb controllers, and switch ports if it still do not work unitl it work (that's how i got it working). Also, try to uninstall all the USB Camera-B4.09.24.1 (Interface 1) in usbdeview.
