### ISSUE TITLE
PSMoveService can stall indefinately on shut down

### ISSUE THREAD

**Issue by Bigfloopingcake** [cboulay/PSMoveService#88]
My psmoveservice keeps crashing after I use it for a little bit.
![capture](https://cloud.githubusercontent.com/assets/20143061/16526857/03e97dd6-3f79-11e6-97df-d1bd1eb876a8.PNG)

**Comment by Bigfloopingcake** [comment]
Then after it closes I launch it again and it says this.
![capture](https://cloud.githubusercontent.com/assets/20143061/16526922/52d42694-3f79-11e6-8482-6ba14c70820a.PNG)

**Comment by HipsterSloth** [comment]
Do you get any error message popup when PSMoveService crashes or does it just close?
Is there a `PSMoveService_1.log` file next to `PSMoveService.exe`? If so would you mind attaching that log here.
Also do you happen to have visual studio installed? If so I'll post some instructions on how to save out a crash dump.

**Comment by Bigfloopingcake** [comment]
The text document is blank and it just crashes also I have visual studio installed.

**Comment by Bigfloopingcake** [comment]
Now the text document is saying this.
[2016-07-01 13:19:27.986166]: main - Starting PSMoveService
[2016-07-01 13:19:27.992166]: main - Failed to start PSMoveService: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by HipsterSloth** [comment]
Aha! Yeah that's the problem. PSMoveService is shutting down right away because the port it wants to listen on is being used by another application. Someone else reported this in issue #84. Check out that issue for debugging steps. Are you running "Unified Remote" by chance?

**Comment by Bigfloopingcake** [comment]
I do not have that program but I am still having the issue
![capture](https://cloud.githubusercontent.com/assets/20143061/16533404/1864bb2a-3f9e-11e6-98a1-fbfe6c041397.PNG)

**Comment by HipsterSloth** [comment]
Is there a zombie of psmoveservice already running? That list of used ports would imply that there is already an instance of psmoveservice. When you try and open psmoveservice now it closes right away correct?

**Comment by Bigfloopingcake** [comment]
yes

**Comment by HipsterSloth** [comment]
Without starting psmoveservice, if you run CurrPorts, do you see psmoveservice registered under port 9512?

**Comment by Bigfloopingcake** [comment]
no i do not

**Comment by HipsterSloth** [comment]
And when you launch PSMoveService.exe now you still get the "Failed to start PSMoveService: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted" error message? If so I might have to add a config option that let's you set which port the service uses.

**Comment by Bigfloopingcake** [comment]
yeah I keep getting that.

**Comment by Bigfloopingcake** [comment]
My PSmoveservice will not close.

**Comment by HipsterSloth** [comment]
I'm betting you are getting the error where we the service is waiting for the camera thread to shutdown.  You can force kill PSMoveService if it gets stuck shutting down and nothing bad should happen. It sounds like because a previous instance of PSMoveService is getting stuck open you can't open the new instance of the service. I'll update the title of this issue to reflect that problem. 

Also you should give the libusb drivers a shot in the latest release (it looks like you were using the CLEye drivers). There were some changes made that made the libusb driver more reliable:
https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha4.4

**Comment by Bigfloopingcake** [comment]
Okay now the config tool will not launch after I got the new patch.

**Comment by HipsterSloth** [comment]
Does it not start at all? Does it start but not connect to the service? Are you running the 32 or the 64 bit build? What does the log window say when you attempt run the client?

**Comment by Bigfloopingcake** [comment]
I got it to work thank you.
