### ISSUE TITLE
Both my ps eye cameras show a pure green screen during test camera

### ISSUE THREAD

**Issue by pdkkid** [cboulay/PSMoveService#90]
I just recently bought two ps eye cameras, and two move controllers to get some 3d tracked controllers for my new CV1, however when i installed them, and installed the libusb drivers, and then tried to test the camera feeds, both cameras show a pure green screen.. Any Help?

Info
Windows 10 x64
Psmoveservice v0.9 alpha 4

Edit: i dont know if this will help, but heres a screenshot http://imgur.com/90v48Li
I have also tried doing the 'clean install' and changing usb hubs and ports from the troubleshooting guide, but to no avail

Also, when launching test_cameras.exe, the feed from the cameras show for about 1/2 a second, then turns green, i dont know if that helps, but im trying to give as much info about the issue as possible

**Comment by pdkkid** [comment]
After moving around the eye cam usb to different ports, it seems that one camera works just fine, but when, and wherever i put the second cam, both get a green screen

**Comment by HipsterSloth** [comment]
This is sadly a common problem with our usage of the libusb drivers. I've been working all this last week on a potential fix for this. I'm hoping to have it in by the Sunday.

**Comment by pdkkid** [comment]
okay, i will wait patiently. Amazing work so far with this project, cant wait to see more progress! (:
