### ISSUE TITLE
Oculus CV1 not being tracked during HMD tracking test in config tool

### ISSUE THREAD

**Issue by pdkkid** [cboulay/PSMoveService#91]
Just got my CV1, but its not seeming to be tracked when i test it in the config tool, any help?

Windows 10 x64
PSMoveService v0.9alpha4_2

**Comment by HipsterSloth** [comment]
Are you running steamvr? I use steamvr to get the HMD position.

**Comment by pdkkid** [comment]
That was the issue, thanks (:

**Comment by zelmon64** [comment]
@HipsterSloth Are we supposed to manually start SteamVR? It usually starts automatically when I run PSMoveConfigTool either using driver_null or VRidge.

**Comment by HipsterSloth** [comment]
@zelmon64 It usually starts automatically for me as well, but I'm testing on a Vive setup (my DK2 broke). It might be that the behavior is different on the Oculus?

**Comment by zelmon64** [comment]
@HipsterSloth That's interesting that they might react differently.

@NyanBlade Is this the case for you as well (having to start SteamVR manually)?
