### ISSUE TITLE
Test tracking will not move the 3d model in ps config tool

### ISSUE THREAD

**Issue by pdkkid** [cboulay/PSMoveService#92]
When trying to compute tracking poses, my HMD gets detected fine(since hipstersloth reminded me i need to have SteamVr running), but while doing the test with the move controller attached to my hmd, or even doing the calibration mat method, the camera will not detect the controller itself, i see it in the camera feed and the tool says that im holding it upright, but once it gets to taking samples, it sticks at 0/60

**Comment by cboulay** [comment]
Have you used the color calibration tool to make sure it's capturing the psmove sphere correctly?

**Comment by pdkkid** [comment]
took me acouple re-reads, but yes, the settings i had were not showing anything while 'masked' view was on, after tinkering with it, i figured it out(:
