### ISSUE TITLE
Usb extender on eye cam causing green flikering

### ISSUE THREAD

**Issue by pdkkid** [cboulay/PSMoveService#93]
I dont know if this can be fixed in software, but it seems using a 3ft usb 2.0 extender on my ps eye causes some green flickering. This extender works fine with other usb cameras, and devices, curious why its doing this on the ps eye. Any fixes/ideas?

Side note: i got my single ps eye setup working insanely well with my two move controllers and CV1 in steam vr, and i just want to say, Amazing job so far on this project guys, Its blowing me away how well this works with even just a single ps eye. Cant wait on a possible fix for using more then 1 cam causing pure green screens (; 
Keep up the great work!

**Comment by zelmon64** [comment]
I use three PSEyes with libusb-win32 and two of them are connected with 5m usb 2.0 cables without a problem. If you're using CL-Eye I'd recommend switching (via libusbK). Does test_camera.exe show the same problem?

**Comment by pdkkid** [comment]
using test_camera with more than 1 camera installed shows both to be a green screen. But when i use just 1 alone, its perfectly smooth until i try and add a 1m extender, then it starts flickering.. Im using the supplied dll, and libusb-win32

**Comment by zelmon64** [comment]
- When you installed the drivers for both PSEyes did you initially install libusbK on both?
- Have you tried switch usb ports in order to use a separate host controller for each PSEye?
- Does the PSEye on the extender flicker if you try other usb ports (preferably on the rear panel)?
- What do you mean by supplied dll? If you're referring to CLEyeMulticam.dll then that won't actually be doing anything when using libusb-win32 (apart from checking that there are no PSEyes using the CL-Eye driver).

**Comment by HipsterSloth** [comment]
@pdkkid I have a new experimental release for you to try: https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha4.3. This incorporates an experimental change that @rovarma came up with that halves the bandwidth needed by each camera. It's worked really well for me on my test at home. I'm curious if it helps your camera woes as well..

**Comment by pdkkid** [comment]
@HipsterSloth test_camera works for both perfectly now! Very happy right now (: Waiting for my 3rd camera to arrive in the mail to test all 3

**Comment by HipsterSloth** [comment]
@pdkkid Cool! Glad to hear that worked for you. Once this fix is back up in the master branch I'll mark this issue as resolved.
