### ISSUE TITLE
SteamVR plugin won't work with 64-bit vrserver

### ISSUE THREAD

**Issue by HipsterSloth** [cboulay/PSMoveService#99]
SteamVR just updated today (7/5/2016) making the 64-bit vrserver the default. The problem with this is that I'm not currently building 64-bit version of the plugin yet, though I'm going to fix that soon.

In the mean time do the following gross work around:

1) Go to: C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin (Or where ever your SteamVR folder lives)
2) Rename the "win64" folder to "win64_original"
3) Duplicate the "win32" folder to "win64"

This tricks SteamVR into thinking it's running the 64-bit server

**Comment by n8rockerasu** [comment]
This works for getting PSMoveService running again, but for some reason, it seems to cause a problem with my DK2. Steam gives me an error message that looks like this. 

![steamvrerror](https://cloud.githubusercontent.com/assets/6808058/16607607/84f2b0c2-4308-11e6-8adf-33687c53199b.jpg)

It appears the DK2 camera isn't recognized with the 32-bit version. I can't remember off the top of my head, but it wouldn't surprise me if Oculus required 64-bit only.

**Comment by HipsterSloth** [comment]
Dang. Well for what it's worth I'm working on making a 64-bit build of the plugin now. Should be ready in a few hours.

**Comment by n8rockerasu** [comment]
@HipsterSloth God speed, good sir. We all appreciate the hard work. If it helps motivate you at all, PSMoveService has been pretty amazing up to this point. For all the super expensive VR setups out there, I believe these types of projects will be the true building blocks for wider accessibility.

**Comment by HipsterSloth** [comment]
Fixed in Pull request #102 (Adding support for 64-bit builds). Created a new release: https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha4.4
